jsk-ros-pkg/jsk_recognition

- jsk_pcl_ros/README.md
- jsk_pcl_ros/catkin.cmake
- jsk_pcl_ros/include/jsk_pcl_ros/linemod.h
- jsk_pcl_ros/include/jsk_pcl_ros/viewpoint_sampler.h
- jsk_pcl_ros/src/linemod_nodelet.cpp
- jsk_pcl_ros/src/viewpoint_sampler.cpp
> [jsk_pcl_ros] Viewpoint sampling for linemod training

- jsk_pcl_ros/include/jsk_pcl_ros/linemod.h
- jsk_pcl_ros/launch/capture/capture_model_registration.launch
- jsk_pcl_ros/src/linemod_nodelet.cpp
avoiding pcl::RangeImage non-thread-safe function and now LINEMODTrainer is thread-safe
> [jsk_pcl_ros] Thread safe linemod trainer

- jsk_pcl_ros/README.md
- jsk_pcl_ros/include/jsk_pcl_ros/attention_clipper.h
- jsk_pcl_ros/include/jsk_pcl_ros/pcl_conversion_util.h
- jsk_pcl_ros/launch/attention_clipper_sample.launch
- jsk_pcl_ros/sample/attention_pose_set.py
- jsk_pcl_ros/src/attention_clipper_nodelet.cpp
- jsk_pcl_ros/src/pcl_conversion_util.cpp
> [jsk_pcl_ros] Support multiple interest region in AttentionClipper

- jsk_pcl_ros/cfg/RegionGrowingMultiplePlaneSegmentation.cfg
- jsk_pcl_ros/launch/laser_multiplane.launch
- jsk_pcl_ros/src/multi_plane_extraction_nodelet.cpp
> [jsk_pcl_ros] tune parameter of multi plane based object detection using spindle laser

- jsk_pcl_ros/include/jsk_pcl_ros/particle_filter_tracking.h
- jsk_pcl_ros/src/particle_filter_tracking_nodelet.cpp
trackingの初期姿勢を，BoundingBoxからも決められるようにしました．
trackingのときの基準となるframe_idをカメラのフレームだけではなく，自分自身で決めたものを使えるようにしました．
pose_stampedもresultとして出すようにしました．
> Add bounding box framed tracking

- jsk_perception/catkin.cmake
- jsk_perception/include/jsk_perception/rgb_decomposer.h
- jsk_perception/jsk_perception_nodelets.xml
- jsk_perception/src/rgb_decomposer.cpp
> [jsk_perception] Add RGBDecomposer to decompose RGB channels into separate images

- jsk_perception/catkin.cmake
- jsk_perception/include/jsk_perception/hsv_decomposer.h
- jsk_perception/include/jsk_perception/rgb_decomposer.h
- jsk_perception/jsk_perception_nodelets.xml
- jsk_perception/src/hsv_decomposer.cpp
- jsk_perception/src/rgb_decomposer.cpp
> [jsk_perception] HSV decomposer

- jsk_perception/catkin.cmake
- jsk_perception/include/jsk_perception/contour_finder.h
- jsk_perception/jsk_perception_nodelets.xml
- jsk_perception/src/contour_finder.cpp
> [jsk_perception] ContourFinder

- jsk_perception/catkin.cmake
- jsk_perception/cfg/SnakeSegmentation.cfg
- jsk_perception/include/jsk_perception/snake_segmentation.h
- jsk_perception/jsk_perception_nodelets.xml
- jsk_perception/src/snake_segmentation.cpp
> [jsk_perception] Add snake segmentation

- jsk_perception/catkin.cmake
- jsk_perception/cfg/SLICSuperPixels.cfg
- jsk_perception/include/jsk_perception/slic_superpixels.h
- jsk_perception/jsk_perception_nodelets.xml
- jsk_perception/src/slic_superpixels.cpp
* Add dynamic_reconfigure interface to SLICSuperPixels
> [jsk_perception] Add dynamic reconfigure to superpixels

- jsk_perception/catkin.cmake
- jsk_perception/cfg/SLICSuperPixels.cfg
- jsk_perception/include/jsk_perception/slic_superpixels.h
- jsk_perception/jsk_perception_nodelets.xml
- jsk_perception/src/slic_superpixels.cpp
* Support RGB8 in SLICSuperPixels
* Support single channel image, which is gray scale image
> [jsk_perception] Support non bgr in slic superpixels

- jsk_perception/Makefile.slic
- jsk_perception/catkin.cmake
- jsk_perception/cfg/SLICSuperPixels.cfg
- jsk_perception/include/jsk_perception/slic_superpixels.h
- jsk_perception/jsk_perception_nodelets.xml
- jsk_perception/src/slic_superpixels.cpp
* Publish label information as cv::Mat<int>
* Use different implementation of SLICSuperPixels to get better performance.
* now it uses my forked versoin until parent repository accept PR
> [jsk_perception] Publish label information from SLICSuperPixels

- jsk_perception/catkin.cmake
- jsk_perception/include/jsk_perception/colorize_labels.h
- jsk_perception/jsk_perception_nodelets.xml
- jsk_perception/launch/super_pixels.launch
- jsk_perception/src/colorize_labels.cpp
- jsk_perception/src/slic_superpixels.cpp
* add simple launch file as a sample of SuperPixels
> [jsk_perception] Add super pixels sample

- jsk_perception/catkin.cmake
- jsk_perception/cfg/ColorHistogramLabelMatch.cfg
- jsk_perception/cfg/SLICSuperPixels.cfg
- jsk_perception/include/jsk_perception/color_histogram_label_match.h
- jsk_perception/src/color_histogram.cpp
- jsk_perception/src/color_histogram_label_match.cpp
1. correlation
2. intersect
3. bhattacharyya
4. chi-squared
5. EMD-Manhattan
6. EMD-Euclid
> [jsk_perception] Implement 6 different methods to compare histogram

- jsk_pcl_ros/src/organized_multi_plane_segmentation_nodelet.cpp
see https://github.com/jsk-ros-pkg/jsk_recognition/issues/446
> [jsk_pcl_ros] Supress warning message from OrganizedMultiPlaneSegmentation

- jsk_perception/include/jsk_perception/color_histogram_label_match.h
- jsk_perception/src/color_histogram_label_match.cpp
> [jsk_perception] Publish coefficient image from ColorHistogramLabelMatch

- jsk_pcl_ros/README.md
- jsk_pcl_ros/cfg/HintedPlaneDetector.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/hinted_plane_detector.h
- jsk_pcl_ros/src/hinted_plane_detector_nodelet.cpp
Add density filter to remove outlier
> [jsk_pcl_ros] Add density filter to HintedPlaneDetector

- jsk_pcl_ros/README.md
- jsk_pcl_ros/include/jsk_pcl_ros/hinted_plane_detector.h
- jsk_pcl_ros/src/hinted_plane_detector_nodelet.cpp
- jsk_perception/src/color_histogram_label_match.cpp
- jsk_perception/src/slic_superpixels.cpp
0 is planned to be used as 'masked'
> [jsk_perception] Increase label index of SLICSuperPixels to avoid 0. 

- jsk_perception/README.md
- jsk_perception/catkin.cmake
- jsk_perception/include/jsk_perception/add_mask_image.h
- jsk_perception/src/add_mask_image.cpp
- jsk_perception/src/colorize_labels.cpp
> [jsk_perception] Colorize label 0 as black

- jsk_pcl_ros/README.md
- jsk_pcl_ros/catkin.cmake
- jsk_pcl_ros/include/jsk_pcl_ros/add_point_indices.h
- jsk_pcl_ros/jsk_pcl_nodelets.xml
- jsk_pcl_ros/src/add_point_indices_nodelet.cpp
> [jsk_pcl_ros] AddPointIndices

- jsk_pcl_ros/cfg/ParticleFilterTracking.cfg
> update params for tracking

- resized_image_transport/include/resized_image_transport/image_resizer_nodelet.h
- resized_image_transport/src/image_resizer_nodelet.cpp
support opencv interpolation method
http://docs.opencv.org/modules/imgproc/doc/geometric_transformations.html#resize
> add parameter to select interpolation method

- jsk_pcl_ros/catkin.cmake
- jsk_perception/catkin.cmake
Check jsk_topic_tools_SOURCE_PREFIX
> [jsk_pcl_ros, jsk_perception] Fix CmakeList for catkin build. 

- jsk_pcl_ros/catkin.cmake
- jsk_perception/catkin.cmake
- jsk_perception/include/jsk_perception/contour_finder.h
- jsk_perception/src/blob_detector.cpp
- jsk_perception/src/contour_finder.cpp
> [jsk_perception] Publish convex image from ContourFinder

- jsk_pcl_ros/src/multi_plane_extraction_nodelet.cpp
@YuOhara @mmurooka 変なところにバウンディングボックス出る問題が解決したかも
> [jsk_pcl_ros] Close convex region in MultiPlaneExtraction

- jsk_pcl_ros/launch/hinted_plane_detector.launch
- jsk_pcl_ros/src/multi_plane_extraction_nodelet.cpp
tilt laser pointcloud, revisited
> [jsk_pcl_ros] Update hinted plane detector sample, adding euclidean segmentation

- imagesift/imagefeatures.cpp.in
Now we have realtime sift detection if ROI specified well.
> [imagesift] Support mask in image features

- jsk_pcl_ros/README.md
- jsk_pcl_ros/include/jsk_pcl_ros/particle_filter_tracking.h
- jsk_pcl_ros/launch/particle_filter_localization.launch
- jsk_pcl_ros/src/particle_filter_tracking_nodelet.cpp
Add ReversedPartcieFilter based on pcl::tracking library to localize robot by tilting laser.
> [jsk_pcl_ros] Add *reversed* mode for ParticleFilterTracking and add sample to localize robot by tilt laser

- jsk_pcl_ros/launch/tracking.launch
https://github.com/jsk-ros-pkg/jsk_recognition/pull/575
で加えたオプションに対応するようにlaunchを書き換えました．
> add options for align box and change base_frame_id

- resized_image_transport/catkin.cmake
> [resized_image_transport] Fix jsk_topic_tools/nodelet.cmake path

- jsk_pcl_ros/catkin.cmake
- jsk_perception/catkin.cmake
- jsk_perception/package.xml
see http://jenkins.ros.org/job/ros-indigo-jsk-perception_binarydeb_saucy_i386/1/
> add image_view2

- jsk_recognition_msgs/CMakeLists.txt
- jsk_recognition_msgs/msg/SimpleOccupancyGrid.msg
- jsk_recognition_msgs/msg/SimpleOccupancyGridArray.msg
Add SimpleOccupancyGrid and SImpleOccupancyGridArray,  it will remove SparseOccupancyGrid*
> [jsk_recognition_msgs] Add new message for occupancy grid for more simple usage

- jsk_recognition_msgs/CMakeLists.txt
working branch for https://github.com/jsk-ros-pkg/jsk_travis/issues/48
> add CATKIN_DEPENDS

- jsk_perception/scripts/image_publisher.py
I think there should be similar script somewhere...
> [jsk_perception] Add simple script to publish image file into ros image

- resized_image_transport/include/resized_image_transport/image_processing_nodelet.h
- resized_image_transport/src/image_processing_nodelet.cpp
it does not support dst_width and dst_height
> [resized_image_transport] Publish scale information

- jsk_pcl_ros/src/hinted_stick_finder_nodelet.cpp
- jsk_pcl_ros/src/linemod_nodelet.cpp
- jsk_pcl_ros/src/resize_points_publisher_nodelet.cpp
- jsk_pcl_ros/src/torus_finder_nodelet.cpp
see https://github.com/jsk-ros-pkg/jsk_recognition/issues/698
> [jsk_pcl_ros] Add print for debug of resize header of resize_points_publisher

- jsk_pcl_ros/launch/imu_orientated_plane_rejecter.launch
plane rejection with imu_acceleration_data.
it works when #710 and #717 merged.
> add imu_orientated_plane_rejector

- jsk_pcl_ros/launch/organized_multi_plane_segmentation.launch
In pointcloud_dataserver, there is no params named "pcds"  and there is "models".
Also comment-in that params because these pcd files are not in git.
> [jsk_pcl_ros] changed miss params and comment in data_names out of git

- .travis.yml
this is using jenkins with USE_JENKINS env variable of https://github.com/jsk-ros-pkg/jsk_recognition/pull/720
> use jenkins for hydro/travis

- jsk_pcl_ros/sample/simple_edge_detector_and_tracker.launch
> add simple_edge_detector_and_tracker.launch

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/README.md
- jsk_pcl_ros/cfg/FeatureRegistration.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/feature_registration.h
- jsk_pcl_ros/jsk_pcl_nodelets.xml
- jsk_pcl_ros/src/feature_registration_nodelet.cpp
Register pointcloud using 3-D features and RANSAC.
> [jsk_pcl_ros] FeatureRegistration

- jsk_pcl_ros/README.md
- jsk_pcl_ros/include/jsk_pcl_ros/pointcloud_screenpoint.h
- jsk_pcl_ros/src/pointcloud_screenpoint_nodelet.cpp
related to https://github.com/jsk-ros-pkg/jsk_common/pull/812
> [jsk_pcl_ros] Support polygon input in PointcloudScreenPoint

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/README.md
- jsk_pcl_ros/include/jsk_pcl_ros/pointcloud_localization.h
- jsk_pcl_ros/jsk_pcl_nodelets.xml
- jsk_pcl_ros/src/pointcloud_localization_nodelet.cpp
> [jsk_pcl_ros] Add PointCloudLocalization for SLAM

- jsk_pcl_ros/include/jsk_pcl_ros/pointcloud_localization.h
- jsk_pcl_ros/src/pointcloud_localization_nodelet.cpp
> [jsk_pcl_ros] Fix PointCloudLocalization to work

- jsk_pcl_ros/cfg/TorusFinder.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/torus_finder.h
- jsk_pcl_ros/src/torus_finder_nodelet.cpp
Documentation is not yet updated.
> [jsk_pcl_ros] Add hint axis parameter for TorusFinder

- jsk_pcl_ros/include/jsk_pcl_ros/point_indices_to_mask_image.h
- jsk_pcl_ros/src/point_indices_to_mask_image_nodelet.cpp
> [jsk_pcl_ros] add approx sync mode to point indices to mask image

- resized_image_transport/src/image_resizer_nodelet.cpp
dynamic_reconfigure to use initial value of dynamic_reconfigure correctly
> [resized_image_transport] Fix ordert to read rosparam and set

- jsk_perception/src/rgb_decomposer.cpp
> Validate image message without image array (width == 0 and height == 0)

- checkerboard_detector/src/checkerboard_detector.cpp
- jsk_pcl_ros/cfg/EnvironmentPlaneModeling.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/environment_plane_modeling.h
- jsk_pcl_ros/include/jsk_pcl_ros/geo_util.h
- jsk_pcl_ros/src/environment_plane_modeling_nodelet.cpp
- jsk_pcl_ros/src/geo_util.cpp
> [jsk_pcl_ros] Refactor environment plane modeling

- jsk_pcl_ros/include/jsk_pcl_ros/environment_plane_modeling.h
- jsk_pcl_ros/include/jsk_pcl_ros/geo_util.h
- jsk_pcl_ros/src/environment_plane_modeling_nodelet.cpp
- jsk_pcl_ros/src/geo_util.cpp
and fix input pointcloud ExtractPolygonalPrismData to close loop of convex hull boundary
> [jsk_pcl_ros] Add ~input/full_cloud 

- jsk_pcl_ros/cfg/EnvironmentPlaneModeling.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/environment_plane_modeling.h
- jsk_pcl_ros/include/jsk_pcl_ros/geo_util.h
- jsk_pcl_ros/src/environment_plane_modeling_nodelet.cpp
- jsk_pcl_ros/src/geo_util.cpp
> [jsk_pcl_ros] Add morphological filtering to grid planes in EnvironmentPlaneModeling

- jsk_pcl_ros/cfg/EnvironmentPlaneModeling.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/environment_plane_modeling.h
- jsk_pcl_ros/include/jsk_pcl_ros/geo_util.h
- jsk_pcl_ros/include/jsk_pcl_ros/tf_listener_singleton.h
- jsk_pcl_ros/src/environment_plane_modeling_nodelet.cpp
- jsk_pcl_ros/src/geo_util.cpp
- jsk_pcl_ros/src/tf_listener_singleton.cpp
- jsk_pcl_ros/src/tilt_laser_listener_nodelet.cpp
* Fill footprint region based on bounding box (for example, computed from leg links)
> [jsk_pcl_ros] Fill occluded footprint region by bounding box in EnvironmentPlaneModeling

- jsk_pcl_ros/include/jsk_pcl_ros/geo_util.h
@furushchev It should solve your issue
> [jsk_pcl_ros] Do not depends geo_util.h on pcl_conversion_util.h in order not to break downstream

- jsk_pcl_ros/include/jsk_pcl_ros/environment_plane_modeling.h
- jsk_pcl_ros/include/jsk_pcl_ros/geo_util.h
- jsk_pcl_ros/src/environment_plane_modeling_nodelet.cpp
- jsk_pcl_ros/src/geo_util.cpp
C++ version of https://github.com/jsk-ros-pkg/jsk_control/pull/241
> [jsk_pcl_ros] New topic interface to snap pose stamped onto grid map in EnvironmentPlaneModeling

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/README.md
- jsk_pcl_ros/include/jsk_pcl_ros/polygon_flipper.h
- jsk_pcl_ros/jsk_pcl_nodelets.xml
- jsk_pcl_ros/src/environment_plane_modeling_nodelet.cpp
- jsk_pcl_ros/src/geo_util.cpp
- jsk_pcl_ros/src/polygon_flipper_nodelet.cpp
- jsk_pcl_ros/src/region_growing_multiple_plane_segmentation_nodelet.cpp
and fix orientation of convex among several nodelets. Force to look upwards in EnvironmentPlaneModeling
> [jsk_pcl_ros] Add PolygonFlipper

- jsk_pcl_ros/cfg/EnvironmentPlaneModeling.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/environment_plane_modeling.h
- jsk_pcl_ros/src/environment_plane_modeling_nodelet.cpp
- jsk_pcl_ros/src/geo_util.cpp
White cells are eroded (delited) grid cells
> [jsk_pcl_ros] Erode grid maps as c-space padding in EnvironmentPlaneModeling

- jsk_perception/src/edge_detector.cpp
changed timing of dynamic reconfigure
> changed order of dynamic reconfigure

- jsk_pcl_ros/src/resize_points_publisher_nodelet.cpp
Hope it solves https://github.com/jsk-ros-pkg/jsk_recognition/issues/698
> [jsk_pcl_ros] Use simple ros::Subscriber for ResizePointsPublisher

- jsk_pcl_ros/sample/simple_edge_detector_and_tracker.launch
now we can detect edges using kinect/xtion
> [jsk_pcl_ros] generalize namespace of launch value

- jsk_perception/src/sparse_image_encoder.cpp
> add encoded points rate

- jsk_pcl_ros/launch/rgbd_mapping_multisense.launch
Added a launch file for rtabmap mapping with multisense.
> Added a launch file for rtabmap mapping with multisense.

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/README.md
- jsk_pcl_ros/cfg/DepthFilter.cfg
- jsk_pcl_ros/cfg/MaskImageToDepthConsideredMaskImage.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/mask_image_to_depth_considered_mask_image.h
- jsk_pcl_ros/jsk_pcl_nodelets.xml
- jsk_pcl_ros/src/mask_image_to_depth_considered_mask_image_nodelet.cpp
input mask image, depth
output mask image which is at close range
> mask image to mask image which is at close range

- jsk_perception/CMakeLists.txt
- jsk_perception/cfg/Fisheye.cfg
- jsk_perception/include/jsk_perception/fisheye_to_panorama.h
- jsk_perception/launch/fisheye_to_panorama.launch
- jsk_perception/scripts/fisheye_ray.py
- jsk_perception/src/fisheye_to_panorama.cpp
DON'T MERGE THIS PULL REQUEST 
I STILL WORK ON THIS PR
> [jsk_perception] Add fisheye rectify

- jsk_perception/cfg/Fisheye.cfg
- jsk_perception/include/jsk_perception/fisheye_to_panorama.h
- jsk_perception/launch/fisheye_to_panorama.launch
- jsk_perception/src/fisheye_to_panorama.cpp
> [jsk_perception] update Fisheye To Panoarama

- jsk_perception/launch/fisheye_to_panorama.launch
- jsk_perception/scripts/fisheye_ray.py
> add Fisheye Ray Publisher

- jsk_pcl_ros/src/mask_image_to_depth_considered_mask_image_nodelet.cpp
> change ROS_ERROR message

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/cfg/ResizePointsPublisher.cfg
- jsk_pcl_ros/src/resize_points_publisher_nodelet.cpp
* parameter config (rosparam    ->     dynamic reconfigure)
> rosparam to dynamic-reconfigure

- jsk_pcl_ros/src/mask_image_to_depth_considered_mask_image_nodelet.cpp
When image width and height have been changed by image-resizer, region_width, region_height, region_x_off_, and region_y_off_ are still previous ones. So, i or j may be out of range.
> check if current point is in directed region

- jsk_pcl_ros/cfg/ResizePointsPublisher.cfg
- jsk_pcl_ros/launch/extract_only_directed_region_of_close_mask_image.launch
> change default parameter

- jsk_perception/cfg/Fisheye.cfg
- jsk_perception/include/jsk_perception/fisheye_to_panorama.h
- jsk_perception/src/fisheye_to_panorama.cpp
> [jsk_perception] add Fisheye Rotate parameter

- jsk_pcl_ros/launch/extract_only_directed_region_of_close_mask_image.launch
* change default input_points to /multisense/left/organized_image_points2_color
> change input image_points topic to /image_points_color

- jsk_perception/CMakeLists.txt
use `execute_process` is not good
> [jsk_perception] Download drill trained data in compiling time

- jsk_pcl_ros/src/mask_image_to_depth_considered_mask_image_nodelet.cpp
* previous version fails if selected points of raw pointcloud are all nan points.
> [jsk_pcl_ros] add pcl::removeNaNFromPointCloud

- resized_image_transport/include/resized_image_transport/log_polar_nodelet.h
- resized_image_transport/src/log_polar_nodelet.cpp
https://github.com/jsk-ros-pkg/jsk_recognition/pull/870 for logpolar
> [resized_image_transport] Fix dynamic_reconfigure name in LogPolar

- jsk_perception/src/point_pose_extractor.cpp
* add ROS_INFO
* add space to message for visibility
> add ROS_INFO

- jsk_perception/src/point_pose_extractor.cpp
> [jsk_perception/point_pose_extractor] Use OpenCV's matcher class to estimate mathcing

- jsk_pcl_ros/src/attention_clipper_nodelet.cpp
for https://github.com/jsk-ros-pkg/jsk_recognition/issues/888
> [jsk_pcl_ros] Remove nan indices from AttentionClipper

- jsk_pcl_ros/src/attention_clipper_nodelet.cpp
> [jsk_pcl_ros] fix attention clipper non nan part

- jsk_pcl_ros/src/tilt_laser_listener_nodelet.cpp
change it to always subscribe input joint states
> [jsk_pcl_ros/TiltLaserListener] Do not unsubscribe input topics if no needed

- jsk_pcl_ros/src/hinted_plane_detector_nodelet.cpp
> [jsk_pcl_ros] Check if hint convex is valid in HintedPlaneDetector

- jsk_pcl_ros/include/jsk_pcl_ros/cluster_point_indices_decomposer.h
- jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp
> [jsk_pcl_ros] Do not publish results if it failes to compute PCA in ClusterPointIndicesDecomposer

- jsk_perception/scripts/image_time_diff.py
upper_left: raw_image
upper_center: mask_image
upper_right: mask_applied_image
lower_right: hue of mask_applied_image
lower_center: stored_image
lower_left: diff of stored_image
> [jsk_perception] Publish the difference between start and current image

- jsk_perception/src/apply_mask_image.cpp
Now ApplyMask always publish RGB8 image
> [jsk_perception] Enable ApplyMask handle BGRA/RGBA image

- jsk_perception/CMakeLists.txt
- jsk_perception/cfg/ImagePublisher.cfg
- jsk_perception/scripts/image_publisher.py
flag to decide if it publishes camera_info
> [jsk_perception] Add publish_info param to image_publisher

- jsk_perception/include/jsk_perception/sliding_window_object_detector_trainer.h
- jsk_perception/launch/sliding_window_object_detector_trainer.launch
- jsk_perception/src/sliding_window_object_detector_trainer_node.cpp
Changed from reading saved dataset object/non-object from directory to using rosbag files.
> Sliding Window detector trainer updated to use rosbag files 

- jsk_perception/launch/fisheye_to_panorama.launch
- jsk_perception/scripts/fisheye_ray.py
width and height are zero if camera is not caribrated, so use sensor_msgs/Image for getting width and height data
> add subscription of image_raw

- jsk_perception/scripts/fisheye_ray.py
fix failed comment camera_info_cb
> uncomment camera_info_cb

- jsk_pcl_ros/README.md
- jsk_pcl_ros/include/jsk_pcl_ros/tilt_laser_listener.h
- jsk_pcl_ros/src/tilt_laser_listener_nodelet.cpp
Add ~not_use_laser_assembler_service parameter not to use laser_assembler service API but assemble scan
pointcloud locally
> [jsk_pcl_ros/TiltLaserListener] Add ~not_use_laser_assembler_service

- jsk_pcl_ros/README.md
- jsk_pcl_ros/include/jsk_pcl_ros/kinfu.h
- jsk_pcl_ros/include/jsk_pcl_ros/tf_listener_singleton.h
- jsk_pcl_ros/src/kinfu_nodelet.cpp
- jsk_pcl_ros/src/tf_listener_singleton.cpp
Rainbow pointcloud is registered pointcloud and RGB pointcloud is current pointcloud from stereo.
> [jsk_pcl_ros/Kinfu] Publish transformation from map to odom

- jsk_pcl_ros/src/particle_filter_tracking_nodelet.cpp
Fix for issue: Particle filter tracker is broken? #987
> Fix particle filter tracker

- jsk_pcl_ros/include/jsk_pcl_ros/normal_direction_filter.h
- jsk_pcl_ros/include/jsk_pcl_ros/normal_estimation_omp.h
- jsk_pcl_ros/include/jsk_pcl_ros/region_growing_multiple_plane_segmentation.h
- jsk_pcl_ros/src/normal_direction_filter_nodelet.cpp
- jsk_pcl_ros/src/normal_estimation_omp_nodelet.cpp
- jsk_pcl_ros/src/region_growing_multiple_plane_segmentation_nodelet.cpp
NormalEstimationOMP and RegionGrowingMultiplePlaneSegmentation
> [jsk_pcl_ros] Add diagnostics information to NormalDirectionFilter,

- jsk_pcl_ros/src/geo_util.cpp
> [jsk_pcl_ros/EnvironmentPlaneModeling] Fix to make it sure to close the

- jsk_pcl_ros/CMakeLists.txt
> [jsk_pcl_ros] Fix optimization flag

- jsk_pcl_ros/README.md
- jsk_pcl_ros/include/jsk_pcl_ros/particle_filter_tracking.h
- jsk_pcl_ros/include/jsk_pcl_ros/pcl_conversion_util.h
- jsk_pcl_ros/launch/tracking.launch
- jsk_pcl_ros/sample/marker_model_tracking.l
- jsk_pcl_ros/src/particle_filter_tracking_nodelet.cpp
> [jsk_pcl_ros] set tracking model with marker in particle_filter_tracker

- jsk_pcl_ros/launch/stereo_reconstruction.launch
fix for https://github.com/jsk-ros-pkg/jsk_recognition/pull/1010
> [jsk_pcl_ros/stereo_reconstruction.launch] Fix several remappings

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/README.md
- jsk_pcl_ros/cfg/HeightmapConverter.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/heightmap_converter.h
- jsk_pcl_ros/jsk_pcl_nodelets.xml
- jsk_pcl_ros/src/heightmap_converter_nodelet.cpp
> [jsk_pcl_ros] Add HeightmapConverter to convert pointcloud to heightmap

- jsk_pcl_ros/src/tilt_laser_listener_nodelet.cpp
joint_states of multisense on atlas head in gazebo continues to increase.
> [jsk_pcl_ros] Use fmod to detect jamp where tilt joint angle continues to inclease, such as gazebo simulation environment

- jsk_pcl_ros/launch/in_hand_recognition.launch
- jsk_pcl_ros/scripts/in_hand_recognition_manager.py
* self_filterを加えました
* 今の認識結果でICPのテンプレートを更新するようのserviceを加えました
> In hand recognition options

- jsk_perception/euslisp/kalman-filtered-objectdetection-marker.l
publish PoseWithCovarianceStamped
> [jsk_perception] pub posewithcovariancestamped

- jsk_perception/euslisp/kalman-filtered-objectdetection-marker.l
don't publish when covariance is 0
> [jsk_perception] fix pub-PoseWithCovarianceStamped

- jsk_pcl_ros/src/pose_with_covariance_stamped_to_gaussian_pointcloud_nodelet.cpp
fix show position
* before
* after
> [jsk_pcl_ros] fix flip option

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/README.md
- jsk_pcl_ros/cfg/InteractiveCuboidLikelihood.cfg
- jsk_pcl_ros/cfg/cuboid_parameter.py
- jsk_pcl_ros/include/jsk_pcl_ros/interactive_cuboid_likelihood.h
- jsk_pcl_ros/include/jsk_pcl_ros/plane_supported_cuboid_estimator.h
- jsk_pcl_ros/jsk_pcl_nodelets.xml
- jsk_pcl_ros/package.xml
- jsk_pcl_ros/sample/sample_plane_supported_cuboid_estimator.launch
- jsk_pcl_ros/src/interactive_cuboid_likelihood_nodelet.cpp
- jsk_pcl_ros/src/plane_supported_cuboid_estimator_nodelet.cpp
likelihood function of PlaneSupportedCuboidEstimator by interactive server
> [jsk_pcl_ros] Add InteractiveCuboidLikelihood to confirm behavior of

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/src/build_check.cpp.in
Should solve https://github.com/jsk-ros-pkg/jsk_recognition/issues/1080
> [jsk_pcl_ros] Link libjsk_pcl_ros_util with libjsk_pcl_ros_base

- jsk_pcl_ros/README.md
- jsk_pcl_ros/config/sample_boundingbox_occlusion_rejector.rviz
- jsk_pcl_ros/sample/sample_boundingbox_occlusion_rejector.launch
```
roslaunch sample_boundingbox_occlusion_rejector.launch
```
> [jsk_pcl_ros] Run rviz in sample_boundingbox_occlusion_rejector.launch

- jsk_pcl_ros/config/plane_supported_cuboid_estimator.rviz
- jsk_pcl_ros/include/jsk_pcl_ros/geo_util.h
- jsk_pcl_ros/include/jsk_pcl_ros/plane_supported_cuboid_estimator.h
- jsk_pcl_ros/sample/sample_plane_supported_cuboid_estimator.launch
- jsk_pcl_ros/src/geo_util.cpp
- jsk_pcl_ros/src/plane_supported_cuboid_estimator_nodelet.cpp
particles and polygons as polygon sensor measurement is updated
> [jsk_pcl_ros/PlaneSupportedCuboidEstimator] Update relationship between

- jsk_perception/package.xml
```
$ git log  | grep Author| sed 's@Author: \(.*\) <.*$@\1@' | sed 's@k-okada@Kei Okada@' | sed 's@ueda@Ryohei Ueda@' | sed 's@aginika@Yuto Inagaki@' | sed 's@inagaki@Yuto Inagaki@'| sed 's@YuOhara@Yu Ohara@' | sed 's@ohara@Yu Ohara@' | sort | uniq -ic | sort -n -r 
2238 Ryohei Ueda
287 Kei Okada
84 Yuto Inagaki
64 youhei
50 Kentaro Wada
48 tarukosu
47 Yu Ohara
46 manabu
34 Kamada Hitoshi
30 HRP2
27 iKrishneel
14 JSK applications
11 furushchev
10 iwaishi
9 h-kamada
7 wesleypchan
7 kazuto
6 eisoku9618
6 chen
5 nozawa
4 Shunichi Nozawa
4 Ryohei Ryohei Ueda
4 roseus
4 au@leus
3 Yusuke Furuta
3 wesleyc
3 terasawa
3 Satoshi Iwaishi
3 rosen
3 mmurooka
3 leus
3 Hiroaki Yaguchi
3 furuta
2 Yuki Furuta
2 Yohei Kakiuchi
2 YoheiKakiuchi
2 JSK User
2 JSK
2 cretaceous-creature
2 au
1 Yoshimaru Tanaka …
```
> [package.xml] Updatae Author

- jsk_pcl_ros/cfg/PlaneSupportedCuboidEstimator.cfg
- jsk_pcl_ros/cfg/cuboid_parameter.py
- jsk_pcl_ros/config/plane_supported_cuboid_estimator.rviz
- jsk_pcl_ros/include/jsk_pcl_ros/boundingbox_occlusion_rejector.h
- jsk_pcl_ros/include/jsk_pcl_ros/plane_supported_cuboid_estimator.h
- jsk_pcl_ros/sample/sample_plane_supported_cuboid_estimator.launch
- jsk_pcl_ros/sample/sample_simulate_tabletop_cloud.py
- jsk_pcl_ros/src/boundingbox_occlusion_rejector_nodelet.cpp
- jsk_pcl_ros/src/plane_supported_cuboid_estimator_nodelet.cpp
Sample to collaborate particle filter based PDF estimator and occlusion free region estimator.
> [jsk_pcl_ros] Add sample to collaborate particle filter based estimator and occlusion free goal sampler

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/config/sample_cube_nearest_point.rviz
- jsk_pcl_ros/include/jsk_pcl_ros/geo_util.h
- jsk_pcl_ros/sample/sample_nearest_distance.launch
- jsk_pcl_ros/sample/src/sample_cube_nearest_point.cpp
- jsk_pcl_ros/src/geo_util.cpp
> [jsk_pcl_ros/geo_util] Minimum distance to polygon and cube

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/tool/range_sensor_error_visualization.cpp
- jsk_recognition_msgs/CMakeLists.txt
- jsk_recognition_msgs/msg/PlotData.msg
> [jsk_pcl_ros] Add tool to visualize variance of raser scan

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/README.md
- jsk_pcl_ros/include/jsk_pcl_ros/polygon_array_angle_likelihood.h
- jsk_pcl_ros/include/jsk_pcl_ros/polygon_array_distance_likelihood.h
- jsk_pcl_ros/jsk_pcl_nodelets.xml
- jsk_pcl_ros/src/polygon_array_angle_likelihood_nodelet.cpp
- jsk_pcl_ros/src/polygon_array_distance_likelihood_nodelet.cpp
> [jsk_pcl_ros] Add nodelet to compte polygon likelihood based on angular difference

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/README.md
- jsk_pcl_ros/cfg/PolygonArrayAreaLikelihood.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/polygon_array_angle_likelihood.h
- jsk_pcl_ros/include/jsk_pcl_ros/polygon_array_area_likelihood.h
- jsk_pcl_ros/include/jsk_pcl_ros/polygon_array_distance_likelihood.h
- jsk_pcl_ros/jsk_pcl_nodelets.xml
- jsk_pcl_ros/src/polygon_array_angle_likelihood_nodelet.cpp
- jsk_pcl_ros/src/polygon_array_area_likelihood_nodelet.cpp
- jsk_pcl_ros/src/polygon_array_distance_likelihood_nodelet.cpp
> [jsk_pcl_ros] Add nodelet to compte polygon likelihood based on area difference

- .travis.yml
Hope it solves hanging-up on jenkins
> Decrease CPU to use in jenkins

- jsk_perception/CMakeLists.txt
- jsk_perception/scripts/download_trained_data.sh
> [jsk_perception] Do not download trained data in compilation time and

- jsk_perception/CMakeLists.txt
- jsk_perception/README.md
- jsk_perception/include/jsk_perception/polygon_array_to_label_image.h
- jsk_perception/jsk_perception_nodelets.xml
- jsk_perception/src/polygon_array_to_label_image.cpp
> [jsk_perception] Add PolygonArrayToLabelImage nodelet

- README.md
- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/package.xml
- jsk_perception/CMakeLists.txt
- jsk_recognition_utils/README.md
We may need to release new version after merging this
> [jsk_pcl_ros, jsk_perception] Fix dependency of jsk_recognition_utils for child packages like jsk_rviz_plugins

- jsk_recognition_utils/package.xml
to fix http://jenkins.ros.org/view/IbinS32/job/ros-indigo-jsk-recognition-utils_binarydeb_saucy_i386/
> add yaml-cpp

- jsk_perception/include/jsk_perception/tabletop_color_difference_likelihood.h
> [jsk_perception/TabletopColorDifferenceLikelihood] Use geo/polygon.h instead of geo_util.h

- imagesift/CMakeLists.txt
- imagesift/sample/sift_keypoints.py
- imagesift/setup.py
- imagesift/src/imagesift/__init__.py
Merge after https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/22
> [WAIT] [imagesift] Python lib to wrap siftfastpy

- .travis.yml
It may speed up test a little bit
> Do not separate build test between jsk_pcl_ros and jsk_perception, because jenkins can build them once

- jsk_pcl_ros/include/jsk_pcl_ros/hinted_handle_estimator.h
- jsk_pcl_ros/src/hinted_handle_estimator_nodelet.cpp
- jsk_recognition_msgs/CMakeLists.txt
- jsk_recognition_msgs/msg/SimpleHandle.msg
handleのestimatorの幅の情報も使いたいのでoutputを増やしました
> add new output msg for handle estimate

- jsk_pcl_ros/cfg/HeightmapConverter.cfg
for jvrc environment, the full environment size is larger than 10m.
> [jsk_pcl_ros] add max size

- doc/jsk_pcl_ros/nodes/moving_least_square_smoothing.md
- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/cfg/MovingLeastSquareSmoothing.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/moving_least_square_smoothing.h
- jsk_pcl_ros/jsk_pcl_nodelets.xml
- jsk_pcl_ros/src/moving_least_square_smoothing_nodelet.cpp
> add MovingLeastSquares Smoothing

- jsk_recognition_utils/include/jsk_recognition_utils/sensor_model/spindle_laser_sensor.h
> [jsk_recognition_utils] Fix laser model

- doc/add_img_tables_to_index.py
- doc/conf.py
> Add image gallery to readthedocs documentation

- doc/jsk_pcl_ros/nodes/depth_image_error.md
- jsk_pcl_ros/include/jsk_pcl_ros/depth_image_error.h
- jsk_pcl_ros/launch/depth_error.launch
- jsk_pcl_ros/src/depth_image_error_nodelet.cpp
Synchronize timestamp exactly for stereo camera.
> [jsk_pcl_ros/DepthImageError] Add `~approximate_sync` parameter.

- doc/jsk_pcl_ros/nodes/planarl_point_cloud_simulator.md
- doc/jsk_pcl_ros/nodes/spherical_point_cloud_simulator.md
- jsk_pcl_ros/config/laser_camera_fov_sample.rviz
- jsk_pcl_ros/sample/laser_camera_fov_sample.launch
- jsk_pcl_ros/sample/laser_camera_fov_sample.py
> [jsk_pcl_ros] Add sample to visualize FOV of laser and stereo camera

- jsk_pcl_ros/scripts/dump_depth_error.py
- jsk_pcl_ros/scripts/plot_depth_error.py
* dump_depth_error.py
Dump DepthErrorResult into csv
* plot_depth_erorr.py
Plot based on the dumped csv
> [jsk_pcl_ros] Add scripts for DepthErrorResult

- doc/jsk_pcl_ros/nodes/planarl_point_cloud_simulator.md
- doc/jsk_pcl_ros/nodes/polygon_array_transformer.md
- doc/jsk_pcl_ros/nodes/spherical_point_cloud_simulator.md
- jsk_pcl_ros/config/laser_camera_fov_sample.rviz
- jsk_pcl_ros/sample/attention_pose_set.py
- jsk_pcl_ros/sample/laser_camera_fov_sample.launch
- jsk_pcl_ros/sample/laser_camera_fov_sample.py
> [jsk_pcl_ros] Add document about PolygonArrayTransformer

- doc/jsk_pcl_ros/nodes/plane_supported_cuboid_estimator.md
- jsk_pcl_ros/cfg/PlaneSupportedCuboidEstimator.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/plane_supported_cuboid_estimator.h
- jsk_pcl_ros/src/plane_supported_cuboid_estimator_nodelet.cpp
Add ~fast_input to use laser based cloud and stereo based cloud
> [jsk_pcl_ros/PlaneSupportedCuboidEstimator] Add ~fast_input

- jsk_perception/scripts/label_image_decomposer.py
Depends on https://github.com/jsk-ros-pkg/jsk_common/pull/1182
> [jsk_perception] Debug output about params

- doc/jsk_pcl_ros/nodes/cluster_point_indices_decomposer.md
- jsk_pcl_ros/include/jsk_pcl_ros/cluster_point_indices_decomposer.h
- jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp
> [jsk_pcl_ros] Convert cluster point indices to mask and label image

- .travis.rosinstall.jade
- .travis.yml
Please wait for https://github.com/jsk-ros-pkg/jsk_travis/pull/102 to be merged
and submodules to be updated.
> Add travis test for jade

- doc/checkerboard_detector/index.md
> [chessboard_detector] Add document about number of grids in marker and add link to caliboard_sheet

- jsk_perception/package.xml
- jsk_perception/scripts/download_trained_data.sh
Depends on https://github.com/ros/rosdistro/pull/9714
> [jsk_perception] Download trained_data for apc recognition sample

- jsk_pcl_ros/src/attention_clipper_nodelet.cpp
This fixes debug box pose which won't change on rviz.
> [jsk_pcl_ros] Initialize transformed_pose_list_ in callback

- jsk_pcl_ros/CMakeLists.txt
see https://github.com/jsk-ros-pkg/jsk_recognition/pull/245#issuecomment-153711241
> 1.7.1 does not contain organized_edge_detector

- doc/jsk_perception/nodes/slic_super_pixels.md
Closes https://github.com/jsk-ros-pkg/jsk_recognition/issues/1306
> [jsk_perception] Wrong subscribing topic name

- jsk_perception/src/colorize_labels.cpp
- jsk_recognition_utils/CMakeLists.txt
- jsk_recognition_utils/include/jsk_recognition_utils/cv_utils.h
- jsk_recognition_utils/include/jsk_recognition_utils/rgb_colors.h
- jsk_recognition_utils/src/cv_utils.cpp
- jsk_recognition_utils/src/rgb_colors.cpp
> [jsk_perception] ColorizeLabels support 20->146 labels

- jsk_pcl_ros/include/jsk_pcl_ros/extract_indices.h
- jsk_pcl_ros/src/extract_indices_nodelet.cpp
This reverts commit dc615cb15ea16beb7a95b7f5b472e57611890a37.
> Revert "Use pcl::PointCloud2 for various Point types"

- doc/jsk_pcl_ros/index.rst
- doc/jsk_pcl_ros/types/bounding_box.md
- doc/jsk_pcl_ros/types/bounding_box_array.md
- doc/jsk_pcl_ros/types/cluster_point_indices.msg.md
- doc/jsk_pcl_ros/types/model_coefficients_array.md
- doc/jsk_pcl_ros/types/polygon_array.md
- doc/jsk_pcl_ros/types/time_range.md
- jsk_recognition_msgs/msg/BoundingBox.msg
- jsk_recognition_msgs/msg/BoundingBoxArray.msg
- jsk_recognition_msgs/msg/ClusterPointIndices.msg
- jsk_recognition_msgs/msg/ModelCoefficientsArray.msg
- jsk_recognition_msgs/msg/PolygonArray.msg
- jsk_recognition_msgs/msg/TimeRange.msg
See http://docs.ros.org/indigo/api/jsk_recognition_msgs/html/index-msg.html for message types
> Remove types on docs for jsk_pcl_ros

- doc/jsk_pcl_ros/nodes/normal_estimation_omp.md
- doc/jsk_pcl_ros/nodes/region_growing_multiple_plane_segmentation.md
- jsk_pcl_ros/include/jsk_pcl_ros/region_growing_multiple_plane_segmentation.h
- jsk_pcl_ros/src/normal_estimation_omp_nodelet.cpp
- jsk_pcl_ros/src/region_growing_multiple_plane_segmentation_nodelet.cpp
- jsk_recognition_utils/CMakeLists.txt
- jsk_recognition_utils/include/jsk_recognition_utils/time_util.h
- jsk_recognition_utils/src/time_util.cpp
Add utility class to measure time: jsk_recognition_utils::WallDurationTimer.
I have implemented similar function a lot of times...
> [jsk_recognition_utils, jsk_pcl_ros] Measure time to compute NormalEstimationOMP and RegionGriwongMultiplePlaneSegmentation.

- doc/jsk_pcl_ros/nodes/cluster_point_indices_decomposer.md
That needs rosparam ~publish_clouds to be true.
> [jsk_pcl_ros] Describe about ~output%02d published condition

- doc/jsk_perception/nodes/skeletonization.md
add comment about output from Skeletonization.
> [doc/jsk_perception/nodes/skeletonization.md] update document

- jsk_pcl_ros/include/jsk_pcl_ros/extract_indices.h
- jsk_pcl_ros/include/jsk_pcl_ros/pcl/extract_indices_patch.h
- jsk_pcl_ros/src/extract_indices_nodelet.cpp
- jsk_pcl_ros/test/test_euclidean_segmentation.test
> Use pcl::PointCloud2 for various Point types

- jsk_pcl_ros/include/jsk_pcl_ros/pcl/extract_indices_patch.h
I mistakenly take it as opposite negative and non negative.
I will send PR to pcl also.
> [jsk_pcl_ros] Fix flipped negative_ of ExtractIndices (bugfix)

- jsk_pcl_ros/CMakeLists.txt
> [jsk_pcl_ros] Do not compile nodelets depending on ml_classifiers if it is not found.

- jsk_perception/CMakeLists.txt
- jsk_perception/src/slic_superpixels.cpp
- jsk_perception/test/slic_super_pixels.test
- jsk_perception/test/test_label_image_decomposer_slop.test
- jsk_perception/test/test_split_fore_background.test
Depends on https://github.com/jsk-ros-pkg/jsk_common/pull/1254
> [jsk_perception] Test slop with test_topic_published.py

- doc/jsk_pcl_ros/nodes/plane_concatenator.md
- jsk_pcl_ros/cfg/PlaneConcatenator.cfg
- jsk_pcl_ros/cfg/TorusFinder.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/plane_concatenator.h
- jsk_pcl_ros/src/plane_concatenator_nodelet.cpp
- jsk_pcl_ros/src/torus_finder_nodelet.cpp
And set pcl verbosity level to WARN.
> 	[jsk_pcl_ros] More larger number of iteration in TorusFinder.  

- jsk_pcl_ros/scripts/extract_top_polygon_likelihood.py
Added:
jsk_pcl_ros/scripts/extract_top_polygon_likelihood.py
> [jsk_pcl_ros] Add script to extract one polygon which has the best likelihood field

- jsk_perception/node_scripts/extract_images_sync
- jsk_perception/node_scripts/image_saver_sync
- jsk_perception/node_scripts/publish_header
I sent PR to upstream:
- https://github.com/ros-perception/image_pipeline/pull/159
- https://github.com/ros-perception/image_pipeline/pull/163
- https://github.com/ros-perception/image_pipeline/pull/164
Added:
jsk_perception/node_scripts/extract_images_sync
jsk_perception/node_scripts/image_saver_sync
jsk_perception/node_scripts/publish_header
> [jsk_perception] Add utils to save images by request or from bagfile

- jsk_pcl_ros/CMakeLists.txt
I don't know if it makes any effect or not.
workaround for https://github.com/jsk-ros-pkg/jsk_recognition/issues/1421
> [jsk_pcl_ros] Remove ccache prefix

- .gitmodules
- jsk_perception/CMakeLists.txt
- jsk_perception/Makefile.slic
Reverts jsk-ros-pkg/jsk_recognition#1425
> Revert "[jsk_perception] slic as submodule"

- jsk_pcl_ros/scripts/install_test_data.py
Modified:
- jsk_pcl_ros/scripts/install_test_data.py
> [jsk_pcl_ros] Extract after copy in installing test data

- jsk_pcl_ros/test/test_euclidean_segmentation.test
- jsk_perception/node_scripts/bof_histogram_extractor.py
Modified:
- jsk_perception/node_scripts/bof_histogram_extractor.py
> [jsk_perception] Fix typo in bof_histogram_extractor.py

- doc/jsk_perception/nodes/label_image_decomposer.rst
- jsk_perception/node_scripts/label_image_decomposer.py
Modified:
- jsk_perception/node_scripts/label_image_decomposer.py
> [jsk_perception/label_image_decomposer.py] Can specify queue_size

- doc/jsk_perception/nodes/image_to_label.rst
- jsk_perception/CMakeLists.txt
- jsk_perception/node_scripts/image_to_label.py
- jsk_perception/test/image_to_label.test
Added:
- jsk_perception/node_scripts/image_to_label.py
> [jsk_perception] Add image_to_label.py

- jsk_perception/launch/basic_2d_features.launch
It would be good for beginners.
Added:
- jsk_perception/launch/basic_2d_features.launch
> [jsk_perception] Add basic_2d_features.launch to overview effective technique

- jsk_pcl_ros/jsk_pcl_nodelets.xml
- jsk_pcl_ros_utils/jsk_pcl_nodelets.xml
Modified:
jsk_pcl_ros/jsk_pcl_nodelets.xml
jsk_pcl_ros_utils/jsk_pcl_nodelets.xml
> [jsk_pcl_ros -> jsk_pcl_ros_utils] Left migration of PointIndicesToMaskImage

- jsk_pcl_ros/scripts/extract_top_polygon_likelihood.py
Modified:
- jsk_pcl_ros/scripts/extract_top_polygon_likelihood.py
> [jsk_pcl_ros] More useful message in extract_top_polygon_likelihood.py

- doc/jsk_perception/nodes/label_image_decomposer.rst
- jsk_perception/node_scripts/label_image_decomposer.py
- jsk_perception/test/test_label_image_decomposer_slop.test
Modified:
- jsk_perception/node_scripts/label_image_decomposer.py
> [jsk_perception] Visualize label in label_image_decomposer.py

- jsk_perception/src/colorize_labels.cpp
Modified:
- jsk_perception/src/colorize_labels.cpp
> [jsk_perception] ColorizeLabels info -> debug

- jsk_perception/node_scripts/label_image_decomposer.py
Modified:
- jsk_perception/node_scripts/label_image_decomposer.py
> [jsk_perception] Keep original encoding and scale to visualize

- doc/jsk_pcl_ros/nodes/octree_voxel_grid.md
- jsk_pcl_ros/cfg/OctreeVoxelGrid.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/octree_voxel_grid.h
- jsk_pcl_ros/src/octree_voxel_grid_nodelet.cpp
Modified:
- doc/jsk_pcl_ros/nodes/octree_voxel_grid.md
- jsk_pcl_ros/cfg/OctreeVoxelGrid.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/octree_voxel_grid.h
- jsk_pcl_ros/src/octree_voxel_grid_nodelet.cpp
> [jsk_pcl_ros] Add ~point_type parameter to octree voxel grid

- jsk_perception/CMakeLists.txt
- jsk_perception/package.xml
Modified:
- jsk_perception/CMakeLists.txt
- jsk_perception/package.xml
> [jsk_perception] Fix unconfigured cmake and manifest

- jsk_perception/node_scripts/label_image_decomposer.py
Modified:
- jsk_perception/node_scripts/label_image_decomposer.py
> [jsk_perception] Set header correctly

- doc/jsk_pcl_ros/nodes/icp_registration.md
- doc/jsk_pcl_ros/nodes/octree_voxel_grid.md
- doc/jsk_pcl_ros/nodes/torus_f_inder.md
- jsk_pcl_ros/cfg/OctreeVoxelGrid.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/icp_registration.h
- jsk_pcl_ros/include/jsk_pcl_ros/octree_voxel_grid.h
- jsk_pcl_ros/include/jsk_pcl_ros/torus_finder.h
- jsk_pcl_ros/src/icp_registration_nodelet.cpp
- jsk_pcl_ros/src/octree_voxel_grid_nodelet.cpp
- jsk_pcl_ros/src/torus_finder_nodelet.cpp
- jsk_recognition_utils/include/jsk_recognition_utils/time_util.h
> [jsk_pcl_ros] Add ~marker_color to OctreeVoxelGrid 

- jsk_pcl_ros/test/test_attention_clipper.test
- jsk_pcl_ros/test/test_euclidean_segmentation.test
- jsk_pcl_ros/test/test_extract_indices.test
Modified:
- jsk_pcl_ros/test/test_attention_clipper.test
- jsk_pcl_ros/test/test_extract_indices.test
> [jsk_pcl_ros] Better test names

- doc/jsk_pcl_ros/nodes/octree_voxel_grid.md
- jsk_pcl_ros/include/jsk_pcl_ros/octree_voxel_grid.h
Modified:
- doc/jsk_pcl_ros/nodes/octree_voxel_grid.md
- jsk_pcl_ros/include/jsk_pcl_ros/octree_voxel_grid.h
> [jsk_pcl_ros] Publish current resolution of octree

- jsk_pcl_ros/include/jsk_pcl_ros/icp_registration.h
- jsk_pcl_ros/src/icp_registration_nodelet.cpp
- jsk_pcl_ros/src/torus_finder_nodelet.cpp
Modified:
- jsk_pcl_ros/include/jsk_pcl_ros/icp_registration.h
- jsk_pcl_ros/src/icp_registration_nodelet.cpp
- jsk_pcl_ros/src/torus_finder_nodelet.cpp
> [jsk_pcl_ros] Init icp after advertise all the topics

- doc/jsk_pcl_ros/nodes/cluster_point_indices_decomposer.md
- jsk_pcl_ros/include/jsk_pcl_ros/cluster_point_indices_decomposer.h
- jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp
Modified:
- jsk_pcl_ros/include/jsk_pcl_ros/cluster_point_indices_decomposer.h
- jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp
> [jsk_pcl_ros] Support approximate sync and queue_size configuration

- jsk_pcl_ros/sample/sample_heightmap.launch
this sample is very good to learn height map
> [jsk_pcl_ros] use <arg> to pass input point cloud

- .travis.rosinstall.jade
Modified:
- .travis.rosinstall.jade
> Some packages are released on jade

- jsk_perception/sample/publish_fixed_images.launch
Modified:
- jsk_perception/sample/publish_fixed_images.launch
> [jsk_perception] Publish info in sample launch file

- jsk_pcl_ros_utils/cfg/PlaneRejector.cfg
- jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/plane_rejector.h
- jsk_pcl_ros_utils/src/plane_rejector_nodelet.cpp
Modified:
- jsk_pcl_ros_utils/cfg/PlaneRejector.cfg
- jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/plane_rejector.h
- jsk_pcl_ros_utils/src/plane_rejector_nodelet.cpp
> [jsk_pcl_ros_utils] Support inliers in plane rejector

- doc/jsk_pcl_ros/nodes/cluster_point_indices_decomposer.md
- jsk_pcl_ros/include/jsk_pcl_ros/cluster_point_indices_decomposer.h
- jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp
Modified:
- jsk_pcl_ros/include/jsk_pcl_ros/cluster_point_indices_decomposer.h
- jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp
> [jsk_pcl_ros/ClusterPointIndicesDecomposer] Publish centroid pose_array

- jsk_perception/node_scripts/solidity_rag_merge.py
Modified:
- jsk_perception/node_scripts/solidity_rag_merge.py
> [jsk_perception] Except index error on SolidityRagMerge

- doc/jsk_pcl_ros/nodes/particle_filter_tracking.md
- jsk_pcl_ros/include/jsk_pcl_ros/particle_filter_tracking.h
- jsk_pcl_ros/launch/tabletop_tracking.launch
- jsk_pcl_ros/scripts/tracker_status_info.py
- jsk_pcl_ros/scripts/tracking_info.py
- jsk_pcl_ros/src/particle_filter_tracking_nodelet.cpp
- jsk_pcl_ros_utils/jsk_pcl_nodelets.xml
- jsk_recognition_msgs/CMakeLists.txt
- jsk_recognition_msgs/msg/BoolStamped.msg
- jsk_recognition_msgs/msg/TrackerStatus.msg
- jsk_recognition_utils/include/jsk_recognition_utils/pcl_ros_util.h
- jsk_recognition_utils/src/pcl_ros_util.cpp
And add some scripts to visualize them.
> [jsk_pcl_ros] Publish current tracking status (running or idle) from     particle_fitler_tracking.

- doc/jsk_pcl_ros/nodes/plane_supported_cuboid_estimator.md
- jsk_pcl_ros/cfg/PlaneSupportedCuboidEstimator.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/plane_supported_cuboid_estimator.h
- jsk_pcl_ros/launch/door_handle_detection.launch
- jsk_pcl_ros/src/plane_supported_cuboid_estimator_nodelet.cpp
door handle
Modified:
- doc/jsk_pcl_ros/nodes/plane_supported_cuboid_estimator.md
- jsk_pcl_ros/cfg/PlaneSupportedCuboidEstimator.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/plane_supported_cuboid_estimator.h
- jsk_pcl_ros/launch/door_handle_detection.launch
- jsk_pcl_ros/src/plane_supported_cuboid_estimator_nodelet.cpp
> [jsk_pcl_ros] Update PlaneSupportedCuboidEstimator to find

- doc/jsk_pcl_ros/nodes/cluster_point_indices_decomposer.md
- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/cfg/ClusterPointIndicesDecomposer.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/cluster_point_indices_decomposer.h
- jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp
Modified:
- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/include/jsk_pcl_ros/cluster_point_indices_decomposer.h
- jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp Added:
- jsk_pcl_ros/cfg/ClusterPointIndicesDecomposer.cfg
> [jsk_pcl_ros] ClusterPointIndicesDecomposer with max/min size

- jsk_perception/euslisp/kalman-filtered-objectdetection-marker.l
* fix code
* remove unused code
> [jsk_perception] [kalman-filtered-objectdetection-marker.l] fix code

- doc/jsk_perception/nodes/apply_mask_image.md
- jsk_perception/include/jsk_perception/apply_mask_image.h
- jsk_perception/src/apply_mask_image.cpp
Modified:
- jsk_perception/include/jsk_perception/apply_mask_image.h
- jsk_perception/src/apply_mask_image.cpp
> [jsk_perception/ApplyMask] Add option to clip mask image

- jsk_recognition_utils/python/jsk_recognition_utils/visualize.py
*before*
*after*
Modified:
- jsk_recognition_utils/python/jsk_recognition_utils/visualize.py
> [jsk_recognition_utils] Tile different size images with centerization

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/package.xml
https://github.com/ros/rosdistro/pull/10420
- add me to maintainer to get jenkins notification
- remove code for groovy, ml_classifier is only available on hydro
> remove code for groovy

- jsk_perception/node_scripts/sklearn_classifier.py
Modified:
- jsk_perception/node_scripts/sklearn_classifier.py
> Fix label probabilities output message

- jsk_perception/launch/basic_2d_features.launch
> [jsk_perception] Add more 2d feature samples

- jsk_perception/CMakeLists.txt
see https://github.com/ros/rosdistro/pull/10436#issuecomment-180763393
> U and V has strange library options

- jsk_perception/src/edge_detector.cpp
> [jsk_perception] Fix variable names in edge_detector.cpp

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/cfg/Kinfu.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/kinfu.h
- jsk_pcl_ros/launch/kinfu.launch
- jsk_pcl_ros/src/kinfu_nodelet.cpp
kinfuの主要なパラメーターをdynamic_reconfigureで変えられるようにしました。
> [jsk_pcl_ros/kinfu]add cfg for change kinfu params

- jsk_perception/CMakeLists.txt
this causes -> http://build.ros.org/job/Jbin_uT64__jsk_perception__ubuntu_trusty_amd64__binary/21/consoleText
> jsk_perception/CMakeLists.txt: remove depends to rosbuild

- jsk_pcl_ros_utils/cfg/CloudOnPlane.cfg
- jsk_pcl_ros_utils/cfg/PolygonArrayAreaLikelihood.cfg
- jsk_perception/cfg/PolygonArrayColorHistogram.cfg
- jsk_perception/cfg/PolygonArrayColorLikelihood.cfg
- jsk_perception/cfg/SelectiveSearch.cfg
- jsk_perception/cfg/TabletopColorDifferenceLikelihood.cfg
- jsk_perception/package.xml
ex. http://build.ros.org/job/Jbin_uU64__jsk_perception__ubuntu_utopic_amd64__binary/28/
- remove rosbuild from run/build depend
- remove dynamic_reconfigure.parameter_generator, which only used for rosbuild
> fix to compile on build server

- jsk_perception/package.xml
Modified:
- jsk_perception/package.xml
> [jsk_perception] Remove duplicated roslint in test_depend

- jsk_perception/CMakeLists.txt
- jsk_perception/node_scripts/selective_search.py
- jsk_perception/test/selective_search.test
Closes #1565
Modified:
- jsk_perception/node_scripts/selective_search.py
jsk_perception/selective_search.py
> [jsk_perception/selective_search.py] Pass RGB image to dlib.find_candidate_object_locations

- doc/index.rst
> Make index in doc looks good

- jsk_pcl_ros/config/openni_tabletop.rviz
- jsk_pcl_ros/sample/tabletop_object_detector.launch
- jsk_pcl_ros_utils/jsk_pcl_nodelets.xml
> [jsk_pcl_ros] add jsk_pcl version of tabletop_object_detector launch/config

- resized_image_transport/CMakeLists.txt
- resized_image_transport/package.xml
- resized_image_transport/src/image_processing_nodelet.cpp
- resized_image_transport/test/image_resizer.test
> [resized_image_transport] Add test for image_resizer

- resized_image_transport/src/image_resizer_nodelet.cpp
Modified:
- resized_image_transport/src/image_resizer_nodelet.cpp
> [resized_image_transport] Add onInitPostProcess for image_resizer

- jsk_perception/scripts/sklearn_classifier_trainer.py
Previous one ignores directory path to save output file (clf).
> clf save directory fixed

- jsk_perception/CMakeLists.txt
- jsk_perception/sample/publish_fixed_images.launch
- jsk_perception/test/image_publisher.test
Added:
- jsk_perception/test/image_publisher.test
> [jsk_perception] Test image_publisher.py

- jsk_perception/CMakeLists.txt
> [jsk_perception] Condition to find OpenCV 3 (> 2.9.9)

- jsk_perception/CMakeLists.txt
- jsk_perception/test/colorize_labels.test
Modified:
- jsk_perception/CMakeLists.txt
Added:
- jsk_perception/test/colorize_labels.test
> [jsk_perception] Test colorize labels

- jsk_perception/CMakeLists.txt
- jsk_perception/test/apply_mask_image.test
Modified:
- jsk_perception/CMakeLists.txt
Added:
- jsk_perception/test/apply_mask_image.test
> [jsk_perception] Test apply mask image

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/cfg/PointcloudDatabaseServer.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/pointcloud_database_server.h
- jsk_pcl_ros/src/pointcloud_database_server_nodelet.cpp
dynamic_reconfigure for publishing duration
> [jsk_pcl_ros/PointcloudDatabaseServer] add dynamic_reconfigure in pointcloud_database_server

- doc/jsk_perception/nodes/robot_to_mask_image.md
solve https://github.com/jsk-ros-pkg/jsk_recognition/issues/1644
> [doc] fix the nodelet name in RobotToMaskImage document

- jsk_pcl_ros/include/jsk_pcl_ros/pointcloud_database_server.h
- jsk_pcl_ros/src/pointcloud_database_server_nodelet.cpp
MERGE AFTER #1624 
modify PointcloudDatabaseServer to load .stl files
> [jsk_pcl_ros/PointcloudDatabaseServer] modify to load .stl files

- jsk_perception/node_scripts/bof_histogram_extractor.py
> [jsk_perception] Support latest sklearn in BoF feature extraction

- .travis.yml
- jsk_perception/CMakeLists.txt
> Upgrade jsk_travis to 0.4.8 and fix some regressions

- jsk_pcl_ros/scripts/install_test_data.py
same as #1627 
Depends on https://github.com/jsk-ros-pkg/jsk_common/pull/1383
> [jsk_pcl_ros] Use jsk_data download_data func for test_data

- doc/jsk_pcl_ros/nodes/pointcloud_database_server.md
- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/sample/sample_pointcloud_database_server.launch
- jsk_pcl_ros/scripts/install_test_data.py
- jsk_pcl_ros/test/test_pointcloud_database_server.test
> [jsk_pcl_ros/PointcloudDatabaseServer] add PointcloudDatabaseServer doc, test and sample launch

- doc/jsk_pcl_ros_utils/nodes/pointcloud_to_pcd.rst
- jsk_pcl_ros_utils/CMakeLists.txt
- jsk_pcl_ros_utils/cfg/PointCloudToPCD.cfg
- jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/pointcloud_to_pcd.h
- jsk_pcl_ros_utils/jsk_pcl_nodelets.xml
- jsk_pcl_ros_utils/sample/sample_pointcloud_to_pcd.launch
- jsk_pcl_ros_utils/scripts/install_test_data.py
- jsk_pcl_ros_utils/src/pointcloud_to_pcd_nodelet.cpp
- jsk_pcl_ros_utils/test/test_pointcloud_to_pcd.py
- jsk_pcl_ros_utils/test/test_pointcloud_to_pcd.test
- jsk_pcl_ros_utils/test_data/.gitignore
- Copy PointCloudToPCD from pcl_ros
- modified to nodelet
- use dynamic_reconfigure
> [jsk_pcl_ros_utils] add PointCloudToPCD nodelet

- doc/install_softkinetic_camera.rst
If there is any problem or no need, please let me know.
> [doc] add reboot word to troubleshooting

- jsk_perception/CMakeLists.txt
This is necessary for https://github.com/start-jsk/jsk_apc/issues/1486
> [jsk_perception] Install trained_data all time with dependency on ALL

- jsk_perception/CMakeLists.txt
I think I have fixed this issue in somewhere....
> jsk_perception/CMakeList.sxt: eigen_INCLUDE_DIRS must be located after catkin_INCLUDE_DIRS

- jsk_perception/CMakeLists.txt
> Warnings for without test node/nodelets

- jsk_perception/src/rect_array_actual_size_filter.cpp
> [jsk_pcl_ros] Fix mistake of rect_array_actual_size_filter

- jsk_pcl_ros/src/kinfu_nodelet.cpp
child_frame_idがきちんとセットされてないと、(tfのtreeの最上位にいないと)
ｔｆの子が複数重なってしまい、ちゃんと動かないという引っかかりポイントがあったので、
それを防ぐようにしました
* kinfuでmapのframeを出すのは上級者向けで、しかも現状誰もやってないのでデフォルトで出ないようにした。
* コメントを加えた。
> allow parent frame not set

- .travis.yml
for https://github.com/jsk-ros-pkg/jsk_travis/issues/279
3 logs/job * 4 jobs = 12 logs
> Keep 12 Jenkins logs for stable testing which has same job names

- .travis_before_script_released_testing.bash
> Use apt jsk_data for testing with non-shadow-fixed

- jsk_perception/node_scripts/image_publisher.py
- Use rospy.Timer
- cv2.imread when reconfigured (in the reconfigure callback)
> Enhance image_publisher.py

- doc/jsk_pcl_ros/nodes/cluster_point_indices_decomposer.md
- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/include/jsk_pcl_ros/cluster_point_indices_decomposer.h
- jsk_pcl_ros/sample/rviz/cluster_point_indices_decomposer.rviz
- jsk_pcl_ros/sample/sample_cluster_point_indices_decomposer.launch
- jsk_pcl_ros/scripts/install_sample_data.py
- jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp
- jsk_pcl_ros/test/test_cluster_point_indices_decomposer.test
For https://github.com/start-jsk/jsk_apc/pull/1794
> Align bounding boxes with target frame in ClusterPointIndicesDecomposer

- doc/jsk_pcl_ros_utils/nodes/point_indices_to_cluster_point_indices.rst
- jsk_pcl_ros_utils/CMakeLists.txt
- jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/point_indices_to_cluster_point_indices.h
- jsk_pcl_ros_utils/jsk_pcl_nodelets.xml
- jsk_pcl_ros_utils/sample/sample_point_indices_to_cluster_point_indices.launch
- jsk_pcl_ros_utils/src/point_indices_to_cluster_point_indices_nodelet.cpp
- jsk_pcl_ros_utils/test/test_point_indices_to_cluster_point_indices.py
- jsk_pcl_ros_utils/test/test_point_indices_to_cluster_point_indices.test
ex)
- Input Indices: [0, 10, 20]
- Output Cluster Indices: [[0, 10, 20]]
> Convert point indices to cluster point indices

- doc/install_astra_camera.rst
> Use SDK uploaded to jsk server for Astra camera

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/launch/hsi_color_filter.launch
- jsk_pcl_ros/sample/sample_hsi_color_filter.launch
- jsk_pcl_ros/src/color_filter_nodelet.cpp
- jsk_pcl_ros/test/test_hsi_color_filter.test
Add keep organized to hsi_color_filter.
To solve #1751
> Keep organized for color filter

- .travis.yml
- jsk_perception/src/bounding_rect_mask_image.cpp
- jsk_perception/src/convex_hull_mask_image.cpp
Enabled to build with ros indigo, opencv-3.x.
It solves #1778
> Adjust to opencv3

- jsk_pcl_ros_utils/CMakeLists.txt
- jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/pointcloud_to_mask_image.h
- jsk_pcl_ros_utils/jsk_pcl_nodelets.xml
- jsk_pcl_ros_utils/sample/sample_pointcloud_to_mask_image.launch
- jsk_pcl_ros_utils/src/pointcloud_to_mask_image_nodelet.cpp
- jsk_pcl_ros_utils/test/test_pointcloud_to_mask_image.test
- Add new node to convert point cloud to mask image
- Do (pointcloud -> jsk_pcl/OrganizedPointCloudToPointIndices -> jsk_pcl/PointIndicesToMaskImage -> mask_image) in a node, **without any synchronization**.
> Convert point cloud to mask image in a node

- jsk_perception/src/bounding_object_mask_image.cpp
This changes the behavior a bit.
> [For Minor Release] Publish whole black mask if no contour is found

- jsk_pcl_ros/include/jsk_pcl_ros/cluster_point_indices_decomposer.h
- jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp
**Example** centroids computed in **BODY** frame
> Compute point cloud centroid after transformed

- jsk_recognition_utils/CMakeLists.txt
- jsk_recognition_utils/cfg/PoseArrayToPose.cfg
- jsk_recognition_utils/node_scripts/pose_array_to_pose.py
- jsk_recognition_utils/package.xml
> Convert PoseArray to PoseStamped with a specified index

- jsk_perception/Makefile.slic
> disable global set ssl verification  to fase

- .travis.yml
Close https://github.com/jsk-ros-pkg/jsk_recognition/issues/1759
> Set USE_DEB=true for indigo on travis for stable testing

- jsk_recognition_utils/CMakeLists.txt
- jsk_recognition_utils/cfg/PolygonArrayToPolygon.cfg
- jsk_recognition_utils/node_scripts/polygon_array_to_polygon.py
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1825
> [jsk_recognition_utils/node_scripts] add polygon_array_to_polygon.py

- jsk_perception/src/sparse_image_encoder.cpp
@furushchev It seems you changed the line before. Could you please review this?
> Fix special character for double to print

- jsk_pcl_ros_utils/test/point_indices_to_mask_image.test
To fix error sometimes on Travis.
> Retry at most three times point_indices_to_mask_image.test

- doc/jsk_pcl_ros_utils/nodes/polygon_array_unwrapper.rst
- jsk_pcl_ros_utils/CMakeLists.txt
- jsk_pcl_ros_utils/cfg/PolygonArrayUnwrapper.cfg
- jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/polygon_array_unwrapper.h
- jsk_pcl_ros_utils/src/polygon_array_unwrapper_nodelet.cpp
- jsk_pcl_ros_utils/test/polygon_array_unwrapper.test
- jsk_pcl_ros_utils/test/test_polygon_array_unwrapper.py
> [jsk_pcl_ros_utils] unwrap polygon array with likelihood

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/cfg/TargetAdaptiveTrackingConfig.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/target_adaptive_tracking.h
- jsk_pcl_ros/jsk_pcl_nodelets.xml
- jsk_pcl_ros/launch/target_adaptive_tracking.launch
- jsk_pcl_ros/sample/rviz/target_adaptive_tracking.rviz
- jsk_pcl_ros/src/target_adaptive_tracking_nodelet.cpp
> Adaptive object tracking

- jsk_perception/include/jsk_perception/histogram_of_oriented_gradients.h
- jsk_perception/src/histogram_of_oriented_gradients.cpp
> Another HOG modified and bug fix

- jsk_pcl_ros/launch/organized_multi_plane_segmentation.launch
Fixed launch file to load jsk_pr2_startup only when RUN_SELF_FILTER is true
> fixed organized_multi_plane_segmentation.launch

- .gitattributes
https://github.com/github/linguist#using-gitattributes
> Add .gitattributes file for GitHub statistics

- jsk_perception/node_scripts/label_image_decomposer.py
> Stop using scipy fromimage that is not supported by apt version

- doc/index.rst
- doc/install_realsense_camera.rst
videos:
- SR300
https://drive.google.com/a/jsk.imi.i.u-tokyo.ac.jp/file/d/0B5DV6gwLHtyJU2REemx2OVNKY0U/view?usp=sharing
- R200
https://drive.google.com/a/jsk.imi.i.u-tokyo.ac.jp/file/d/0B5DV6gwLHtyJTG4yTzZ0UzZQTjA/view?usp=sharing
> [doc] add RealSense camera doc

- jsk_pcl_ros/src/extract_indices_nodelet.cpp
Close https://github.com/jsk-ros-pkg/jsk_recognition/issues/1894
- package/jsk_pcl_ros
> Add condition to use PCL1.8 for ExtractIndices

- .travis.yml
- jsk_perception/test/bing.test
- jsk_perception/test/sklearn_classifier.test
~~For https://github.com/jsk-ros-pkg/jsk_recognition/pull/1875#issuecomment-247397627~~
> Remove no need CATKIN_TOOLS_BUILD_OPTIONS declaration

- .travis_before_script_pcl1.8.bash
- Remove no need rosinstall_generator
- Simplify wstool up
> Refine .travis_before_script_pcl1.8.bash

- jsk_perception/package.xml
> Fix order of declaration of dependencies in package.xml

- doc/jsk_perception/nodes/unapply_mask_image.md
fixed jsk_perception documentation typo.
unpply_mask_image.md->unapply_mask_image.md
> fixed typo (unpply -> unapply)

- checkerboard_detector/CMakeLists.txt
https://github.com/jsk-ros-pkg/jsk_recognition/issues/1919
> [checkerboard_detector] add dependency to cfg for checherboard_detector

- jsk_pcl_ros/package.xml
> [Major Release] Remove dependency on jsk_perception for separated build

- doc/jsk_pcl_ros/nodes/attention_clipper.md
- doc/jsk_pcl_ros/nodes/roi_clipper.md
> fixed typo in attention_clipper.md and roi_clipper.md

- .travis.yml
- jsk_pcl_ros/CMakeLists.txt
- jsk_perception/CMakeLists.txt
see https://github.com/jsk-ros-pkg/jsk_recognition/pull/1929#issuecomment-257088080
> add test to check in install settings and fix install process for #1929

- jsk_pcl_ros/scripts/install_sample_data.py
- jsk_pcl_ros/scripts/install_test_data.py
It's my careless mistake. #1926
> [jsk_pcl_ros] remove duplicated install data lines

- jsk_pcl_ros_utils/CMakeLists.txt
- jsk_pcl_ros_utils/package.xml
- jsk_pcl_ros_utils/sample/config/sample_point_indices_to_cluster_point_indices.rviz
- jsk_pcl_ros_utils/sample/data/.gitignore
- jsk_pcl_ros_utils/sample/sample_cluster_point_indices_to_point_indices.launch
- jsk_pcl_ros_utils/sample/sample_point_indices_to_cluster_point_indices.launch
- jsk_pcl_ros_utils/sample/sample_pointcloud_to_mask_image.launch
- jsk_pcl_ros_utils/sample/sample_pointcloud_to_pcd.launch
- jsk_pcl_ros_utils/sample/sample_pointcloud_to_point_indices.launch
- jsk_pcl_ros_utils/scripts/install_sample_data.py
- jsk_pcl_ros_utils/test/pointcloud_to_pcd.test
- jsk_pcl_ros_utils/test/pointcloud_to_point_indices.test
Related to https://github.com/jsk-ros-pkg/jsk_recognition/pull/1945
Seperate test into sample and test.
> [jsk_pcl_ros_utils] Removed dependencies of install_test_data.py

- jsk_perception/sample/sample_colorize_float_image.launch
- jsk_perception/src/colorize_float_image.cpp
- jsk_perception/test/colorize_float_image.test
> Fill black color to nan region in colorize_float_image

- jsk_pcl_ros/src/multi_plane_extraction_nodelet.cpp
copy header for syncronize topic
> [jsk_pcl/multi_plane_extraction] fix stamp of cloud msg

- jsk_perception/CMakeLists.txt
- jsk_perception/package.xml
- jsk_perception/sample/sample_background_subtraction.launch
- jsk_perception/sample/sample_colorize_float_image.launch
- jsk_perception/sample/sample_rect_array_actual_size_filter.launch
- jsk_perception/scripts/install_sample_data.py
- jsk_perception/test/background_subtraction.test
Sample and test are useful to make program keep work.
> Add test & sample for background_subtraction

- doc/jsk_pcl_ros/nodes/octree_voxel_grid.md
- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/include/jsk_pcl_ros/octree_voxel_grid.h
- jsk_pcl_ros/sample/rviz/octree_voxel_grid.rviz
- jsk_pcl_ros/sample/sample_octree_voxel_grid.launch
- jsk_pcl_ros/src/octree_voxel_grid_nodelet.cpp
- jsk_pcl_ros/test/test_octree_voxel_grid.test
Close https://github.com/jsk-ros-pkg/jsk_recognition/pull/1953
With suggestion here: https://github.com/jsk-ros-pkg/jsk_recognition/pull/1953#issuecomment-263188485
> Publish marker_array by octree_voxel_grid

- jsk_pcl_ros/cfg/ICPRegistration.cfg
> [jsk_pcl/ICP] change max param of icp-cfg(debug)

- .travis.rosinstall.hydro
- jsk_perception/CMakeLists.txt
> Add missing packages to find_package in CMakeLists.txt of jsk_perception

- jsk_pcl_ros_utils/package.xml
Fix https://github.com/jsk-ros-pkg/jsk_recognition/pull/1762#issuecomment-266618656
> Fix dependency of jsk_pcl_ros_utils

- jsk_pcl_ros/scripts/install_sample_data.py
> [jsk_pcl_ros/install_sample] fix md5sum

- doc/jsk_perception/nodes/apply_mask_image.md
- jsk_perception/include/jsk_perception/apply_mask_image.h
- jsk_perception/src/apply_mask_image.cpp
original image
mask image
apply_mask image
apply_negative_mask
> [jsk_perception/apply_mask_image] Add negative option

- jsk_recognition_utils/CMakeLists.txt
- jsk_recognition_utils/include/jsk_recognition_utils/geo/polyline.h
- jsk_recognition_utils/include/jsk_recognition_utils/geo_util.h
- jsk_recognition_utils/src/geo/line.cpp
- jsk_recognition_utils/src/geo/polyline.cpp
- jsk_recognition_utils/src/geo/segment.cpp
DO NOT MERGE YET
line.h / line.cpp に
FiniteLine 有限長直線
PolyLine 連続直線
のクラスとメソッドを追加しました。
> [jsk_recognition_utils] add FiniteLine and PolyLine to line.{h,cpp}

- jsk_pcl_ros/launch/openni2_remote.launch
Related to https://github.com/jsk-ros-pkg/jsk_recognition/issues/2034
> [jsk_pcl_ros] Modified openni2_remote for republish compressed image

- jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp
> [jsk_pcl_ros][cluster_point_indices_decomposer] normailize bbox orientation quaternion

- doc/tutorials/publish_static_image_topic.rst
Fix $(find ...) to $(rospack find ...) and separate first command into each terminals.
> fix command and descriptions

- doc/jsk_perception/nodes/multiply_mask_image.md
- jsk_perception/include/jsk_perception/multiply_mask_image.h
- jsk_perception/src/multiply_mask_image.cpp
Modified:
- doc/jsk_perception/nodes/multiply_mask_image.md
- jsk_perception/src/multiply_mask_image.cpp
> Add ~queue_size param to MultiplyMaskImage

- doc/jsk_perception/nodes/bounding_box_to_rect.md
> Fix typo in doc of BoundingBoxToRect

- jsk_pcl_ros/include/jsk_pcl_ros/edge_depth_refinement.h
- jsk_pcl_ros/src/edge_depth_refinement_nodelet.cpp
- jsk_recognition_msgs/CMakeLists.txt
- jsk_recognition_msgs/msg/Segment.msg
- jsk_recognition_msgs/msg/SegmentArray.msg
- jsk_recognition_msgs/msg/SegmentStamped.msg
updated PR of https://github.com/jsk-ros-pkg/jsk_recognition/pull/2032
> add Segment msg

- jsk_perception/package.xml
> Remove unexpectedly introduced torch rosdep key

- doc/jsk_recognition_utils/index.rst
- doc/jsk_recognition_utils/nodes/bounding_box_array_publisher.md
- doc/jsk_recognition_utils/nodes/polygon_array_to_polygon.md
- doc/jsk_recognition_utils/nodes/pose_array_to_pose.md
- doc/jsk_recognition_utils/nodes/static_virtual_camera.md
- jsk_recognition_utils/README.md
- jsk_recognition_utils/sample/sample_static_virtual_camera.launch
> Documentation of nodes in jsk_recognition_utils

- doc/jsk_pcl_ros/nodes/tilt_laser_listener.md
update document for https://github.com/jsk-ros-pkg/jsk_recognition/pull/2082
> [tilt_laser_listener] update document for periodic publish mode

- doc/jsk_perception/nodes/non_maximum_suppression.md
> Fix style of doc: non_maximum_suppression

- jsk_pcl_ros/src/depth_image_creator_nodelet.cpp
This is a regression by #2102 .
> Check if in image to create depth from laser scans

- .travis.rosinstall.hydro
- doc/jsk_pcl_ros/nodes/depth_image_creator.md
- jsk_pcl_ros/package.xml
- jsk_pcl_ros/sample/rviz/depth_image_creator.rviz
- jsk_pcl_ros/sample/sample_depth_image_creator.launch
- jsk_pcl_ros/src/depth_image_creator_nodelet.cpp
- jsk_pcl_ros/test/test_depth_image_creator.test
- jsk_pcl_ros_utils/CMakeLists.txt
- jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/pointcloud_xyzrgb_to_xyz.h
- jsk_pcl_ros_utils/jsk_pcl_nodelets.xml
- jsk_pcl_ros_utils/src/pointcloud_xyzrgb_to_xyz_nodelet.cpp
This is a regression by https://github.com/jsk-ros-pkg/jsk_recognition/pull/2102 .
> Support PointXYZ in DepthImageCreator	

- jsk_perception/launch/fcn_object_segmentation.launch
- jsk_perception/node_scripts/fcn_object_segmentation.py
- jsk_perception/scripts/install_trained_data.py
For https://github.com/start-jsk/jsk_apc/pull/2113
> Show deprecated warning for ~model_h5 in fcn_object_segmentation

- jsk_perception/node_scripts/label_image_decomposer.py
- Faster: because we don't use matplotlib to draw text
- Better: It overlays label on image segments
> Faster and better visualization of segmentation

- doc/jsk_pcl_ros/nodes/pointcloud_screenpoint.md
- modified one of publishing topic names based on 
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/src/pointcloud_screenpoint_nodelet.cpp#L73
- modified one of subscribing topic names based on
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/src/pointcloud_screenpoint_nodelet.cpp#L86 
I also added missing ```:``` .
If there is any problem, please let me know.
> [doc/jsk_pcl_ros] modify PointcloudScreenpoint

- jsk_perception/test/bof_histogram_extractor.test
reported in https://github.com/jsk-ros-pkg/jsk_recognition/pull/2072#issuecomment-298814492
> jsk_perception/test/bof_histogram_extractor.test: increase time-limit for test_bof_histogram_extractor

- doc/jsk_pcl_ros/nodes/depth_image_creator.md
- jsk_pcl_ros/sample/sample_depth_image_creator.launch
For https://github.com/jsk-ros-pkg/jsk_recognition/pull/2103#issuecomment-307675080
> Following change of #2103

- jsk_pcl_ros/src/supervoxel_segmentation_nodelet.cpp
For https://github.com/start-jsk/jsk_apc/issues/2157
> [WIP][jsk_pcl_ros] check size of PointCloud data size

- jsk_pcl_ros/sample/sample_icp_registration.launch
- jsk_pcl_ros/sample/sample_octree_voxel_grid.launch
- jsk_pcl_ros/sample/sample_ppf_registration.launch
- jsk_pcl_ros/scripts/install_sample_data.py
related to https://github.com/jsk-ros-pkg/jsk_common/issues/1529#issuecomment-309330761
> [jsk_pcl_ros] use smaller rosbag data for ppf registration

- doc/jsk_perception/nodes/polygon_to_mask_image.md
- jsk_perception/src/polygon_to_mask_image.cpp
I took 20 minutes to find this mistake, so add error message.
> [jsk_perception/polygon_to_mask] add error message of frame_id

- doc/jsk_pcl_ros/nodes/color_histogram.md
- doc/jsk_pcl_ros/nodes/color_histogram_classifier.md
- doc/jsk_pcl_ros/nodes/color_histogram_visualizer.md
- jsk_pcl_ros/sample/rviz/color_histogram.rviz
- jsk_pcl_ros/sample/sample_color_histogram.launch
- jsk_pcl_ros/scripts/color_histogram_visualizer.py
> [docs][color_histogram_classifier] add tutorials

- jsk_perception/node_scripts/people_pose_estimation_2d.py
- jsk_perception/package.xml
- jsk_perception/sample/config/people_pose_estimation_2d.rviz
- jsk_perception/sample/include/play_rosbag_people.xml
- jsk_perception/sample/sample_people_pose_estimation_2d.launch
- jsk_perception/scripts/install_trained_data.py
- jsk_recognition_msgs/scripts/people_pose_array_to_pose_array.py
Close #2161 
- Support 16UC1 depth image in PeoplePoseEstimation2D
- Fix AttributeError of argsort in cupy == 1.0.1
- Add script to convert people pose to pose array
> Enhance PeoplePoseEstimation2D

- jsk_recognition_msgs/CMakeLists.txt
- jsk_recognition_msgs/msg/Object.msg
- jsk_recognition_msgs/msg/ObjectArray.msg
- jsk_recognition_msgs/sample/sample_object_array_publisher.launch
- jsk_recognition_msgs/scripts/object_array_publisher.py
It would be useful if I can change this property dynamically.
For actual use, please refer to
- https://github.com/jsk-ros-pkg/jsk_visualization/pull/668
- https://github.com/start-jsk/jsk_apc/pull/2217
> Add Object, ObjectArray.msg to represent object property

- jsk_perception/scripts/install_trained_data.py
this should fix ros build firm -> http://build.ros.org/job/Ibin_uT64__jsk_perception__ubuntu_trusty_amd64__binary/123/console
> chainer can not install in ros build firm

- resized_image_transport/package.xml
https://github.com/jsk-ros-pkg/jsk_recognition/issues/2170#issuecomment-316003566
> current source code needs jsk_topic_tools >= 2.2.4

- jsk_perception/node_scripts/people_pose_estimation_2d.py
> jsk_perception: fix indent in creating people pose

- jsk_perception/include/jsk_perception/bounding_box_to_rect.h
- jsk_perception/sample/sample_bounding_box_to_rect.launch
- jsk_perception/sample/sample_rect_to_mask_image.launch
- jsk_perception/src/bounding_box_to_rect.cpp
- jsk_recognition_utils/node_scripts/rect_array_to_polygon_array.py
> Convert bounding box to mask

- doc/jsk_perception/nodes/label_image_decomposer.rst
- jsk_perception/node_scripts/label_image_decomposer.py
- jsk_perception/sample/sample_label_image_decomposer.launch
The left lower image is what is added by this PR.
>  Add option to visualize label image without sync

- doc/jsk_perception/nodes/tile_image.rst
- jsk_perception/node_scripts/tile_image.py
- jsk_perception/sample/sample_tile_image.launch
> Capability of specifying shape for tiling images

- doc/index.rst
- doc/install_astra_camera.rst
- doc/install_xtion2.rst
Add doc of `Xtion2` using by `openni2_camera`
cc. @YutoUchimi
> [doc] add install_xtion2 doc

- .travis.yml
This enables us to remove cron job from jenkins.
> Trigger the build of jsk-docs.rtd.org by travis

- jsk_perception/CMakeLists.txt
install generated template directory
> jsk_perception: install template dir

- jsk_pcl_ros/test/test_depth_image_creator.test
> test_depth_image_creator.test: increase time limit

- doc/jsk_perception/nodes/image_publisher.md
> [doc] update image_publisher doc

- jsk_pcl_ros/scripts/color_histogram_visualizer.py
axisbg is removed from matplotlib 2.2.0
`The axisbg and axis_bgcolor properties on Axes have been deprecated in favor of facecolor.`
https://matplotlib.org/api/api_changes.html
Travis build failed because of the removal.
```
[ERROR] [WallTime: 1521094126.958597] bad callback: <bound method ColorHistogramVisualizer.callback_array of <__main__.ColorHistogramVisualizer object at 0x2b4da3729b10>>
File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
cb(msg)
File "/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros/scripts/color_histogram_visualizer.py", line 79, in callback_array
self.callback(msg.histograms[self.histogram_index])
File "/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros/ …
```
> [jsk_pcl_ros/color_histogram_visualizer.py] use facecolor instead of axisbg

- jsk_pcl_ros/CMakeLists.txt
- jsk_recognition_utils/CMakeLists.txt
Close https://github.com/jsk-ros-pkg/jsk_recognition/issues/2259
> Fix build of jsk_recognition_utils (on Kinetic)

- jsk_pcl_ros/CMakeLists.txt
> Fix warnings for jsk_pcl_ros package

- jsk_perception/launch/fcn_object_segmentation.launch
- jsk_perception/sample/sample_fcn_object_segmentation.launch
Sometimes the test fails because of unexpected errors.
In that case, it is better that the test quickly finish with errors.
like #2272
> Set required=true for samples to fast finish in tests

- .travis.yml
Related to https://github.com/jsk-ros-pkg/jsk_recognition/pull/2255
> Test Kinetic on Travis

- doc/index.rst
- doc/install_chainer_gpu.rst
cc @yuki-asano
I hope this **automatically** resolves problems of new users of Chainer, Cupy for Deep Learning,  
without help, power and time of @k-okada, @wkentaro and @knorth55 for example.
> Add documentation for installation of Chainer with GPU

- jsk_pcl_ros/src/resize_points_publisher_nodelet.cpp
- jsk_pcl_ros/src/tilt_laser_listener_nodelet.cpp
Close https://github.com/jsk-ros-pkg/jsk_recognition/issues/2290
> Fix warnings about <pcl/ros/conversions.h> and printf format

- doc/jsk_perception/nodes/mask_rcnn_instance_segmentation.rst
- jsk_perception/node_scripts/mask_rcnn_instance_segmentation.py
- jsk_perception/sample/sample_mask_rcnn_instance_segmentation.launch
- jsk_perception/scripts/install_trained_data.py
I finally reproduced the performance of original work.
And it requires newer version of the pretrained model.
> Update chainer_mask_rcnn to 0.3.0

- jsk_pcl_ros/launch/openni2_remote.launch
To change namespace of openni2_remote.launch, 
I modified camera value.
> [jsk_pcl_ros] Modified openni2_remote.launch to change camera namespace

- jsk_pcl_ros/launch/openni2_remote.launch
I modified that you can change the camera source and rgb namespace.
> [jsk_pcl_ros/openni2_remote.launch] Modified namespace

- jsk_pcl_ros_utils/CMakeLists.txt
- jsk_pcl_ros_utils/scripts/install_sample_data.py
Close https://github.com/jsk-ros-pkg/jsk_recognition/pull/2303
@k-okada What about this?
> Add --pkg-path option to install_sample_data.py not to use rospack

- jsk_pcl_ros/package.xml
There is two cv_bridge in run_depend
> [jsk_pcl_ros/package.xml] Delete duplication of cv_bridge

- doc/jsk_pcl_ros/nodes/organized_edge_detector.rst
Change jsk_pcl_ros document to follow CMakeLists.txt.
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/CMakeLists.txt#L264
> [doc/jsk_pcl_ros] Fix organized_edge_detector required PCL version.

- doc/jsk_pcl_ros_utils/nodes/polygon_array_wrapper.rst
> [doc/jsk_pcl_ros_utils] Add doc of PolygonArrayWrapper

- doc/jsk_perception/nodes/mask_rcnn_instance_segmentation.rst
- jsk_perception/node_scripts/mask_rcnn_instance_segmentation.py
Publish detected rectangles and classes.
> [jsk_perception/mask_rcnn_instance_segmentation.py] Publish rects and class

- doc/jsk_pcl_ros/nodes/organized_pass_through.rst
- jsk_pcl_ros/cfg/OrganizedPassThrough.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/organized_pass_through.h
- jsk_pcl_ros/src/organized_pass_through_nodelet.cpp
This pull request includes a feature to remove NaN point from passed through point cloud.
> [jsk_pcl_ros][organized_pass_through] add remove_nan

- jsk_pcl_ros/include/jsk_pcl_ros/octomap_server_contact.h
- jsk_pcl_ros/src/octomap_server_contact_nodelet.cpp
I add following features with @mmurooka 
- callback function to insert proximity sensor pointcloud
- rosparam to select publishing unknown space marker array  
The pictures below are sample execution of this Pull Request on fetch robot.
Blue voxels are occupied and green voxels are free.
> [octomap_server_contact] add callback function to insert proximity sensor pointcloud

- doc/jsk_perception/nodes/people_pose_estimation_2d.rst
I added a link to install chainer with GPU support.
While I was trying to execute a sample in #2348, I didn't know I had to install chainer at first and how to use GPU, so I think this kind of explanation would be helpful for me.
I appreciate everyone's comment for this PR.
> [doc] modify people_pose_estimation_2d: add link to install chainer with GPU support

- doc/install_chainer_gpu.rst
related issue: #2348
I'm a super beginner, so please tell me anything if I write wrong things (it's highly possible!). 
I'm also not good at handling reST, so I will check it tomorrow. (sorry!)
I modified a doc of installation of chainer with GPU support as follows:
- Requirement: added how to check if your PC has a GPU.
- Install CUDA: added explanation of using CUDA9.2 on Ubuntu 16.04 and command `nvidia-smi`
- Install CUDNN: added navigation to deb files, example of installing cuDNN for CUDA9.2 on Ubuntu 16.04, delete explanation of getting tgz files because I couldn't find these
- Install Cupy: delete description of `~/.bashrc` because I didn't need this in my case
> [doc] modify installation of chainer with GPU support

- .travis_before_script_pcl1.8.bash
Related to https://github.com/jsk-ros-pkg/jsk_recognition/issues/2380
> set PCL_ENABLE_SSE:BOOL=FALSE in travis_before_script_pcl1.8.bash for kinetic build

- jsk_pcl_ros/src/uniform_sampling_nodelet.cpp
modified pcl version check for pcl-1.9
> Modify pcl version check for building with pcl-1.9

- doc/tips.rst
I updated doc with [your advice](https://github.com/jsk-ros-pkg/jsk_recognition/pull/2431#issuecomment-506929359)
> add 'how to generate doc on local machine' in tips.rst

- doc/jsk_pcl_ros/nodes/kinfu.md
- jsk_pcl_ros/include/jsk_pcl_ros/kinfu.h
- jsk_pcl_ros/src/kinfu_nodelet.cpp
add `~volume_size` parameter to kinfu
> add volume_size for kinfu parameter

- doc/install_xtion2.rst
- changed ROS version to be given by command
- fix SDK filename
> Fix Xtion2 Installation document

- doc/index.rst
- doc/install_structure_core.rst
- add a Structure core Installation document
> add Structure core Installatin Document

- doc/index.rst
- doc/install_pcl_from_source.md
- doc/jsk_pcl_ros/nodes/attention_clipper.md
- doc/jsk_pcl_ros/nodes/kinfu.md
add pcl build doc for sse build error and kinfu
cc. @Kanazawanaoaki
> [doc] add install pcl from source doc

- .travis.yml
- jsk_perception/node_scripts/alexnet_object_recognition.py
- jsk_perception/node_scripts/deep_sort/deep_sort_tracker.py
- jsk_perception/node_scripts/deep_sort_tracker_node.py
- jsk_perception/node_scripts/face_pose_estimation.py
- jsk_perception/node_scripts/fast_rcnn.py
- jsk_perception/node_scripts/fcn_depth_prediction.py
- jsk_perception/node_scripts/fcn_object_segmentation.py
- jsk_perception/node_scripts/hmr/net.py
- jsk_perception/node_scripts/hmr/resnet_v2_50.py
- jsk_perception/node_scripts/hmr/smpl.py
- jsk_perception/node_scripts/human_mesh_recovery.py
- jsk_perception/node_scripts/mask_rcnn_instance_segmentation.py
- jsk_perception/node_scripts/openpose/hand_net.py
- jsk_perception/node_scripts/openpose/pose_net.py
- jsk_perception/node_scripts/people_pose_estimation_2d.py
- jsk_perception/node_scripts/regional_feature_based_object_recognition.py
- jsk_perception/node_scripts/ssd_object_detector.py
- jsk_perception/node_scripts/tile_image.py
- jsk_perception/node_scripts/vgg16_object_recognition.py
- jsk_perception/sample/sample_image_cluster_indices_decomposer.launch
- jsk_perception/scripts/create_db_for_feature_based_object_recognition.py
- jsk_perception/scripts/install_trained_data.py
- jsk_perception/scripts/ssd_train_dataset.py
- jsk_perception/scripts/train_fcn.py
- jsk_perception/scripts/train_mask_rcnn.py
- jsk_perception/scripts/train_ssd.py
- jsk_perception/test/bounding_box_to_rect.test
- jsk_perception/test/image_cluster_indices_decomposer.test
```
File "/home/k-okada/ws_recognition/src/jsk_recognition/jsk_perception/node_scripts/ssd_object_detector.py", line 26, in <module>
import chainer
File "/usr/local/lib/python2.7/dist-packages/chainer/__init__.py", line 10, in <module>
from chainer import backends  # NOQA
File "/usr/local/lib/python2.7/dist-packages/chainer/backends/__init__.py", line 1, in <module>
from chainer.backends import cuda  # NOQA
File "/usr/local/lib/python2.7/dist-packages/chainer/backends/cuda.py", line 77
def shape(self) -> types.Shape:
^
SyntaxError: invalid syntax
```
c.f. https://github.com/jsk-ros-pkg/jsk_recognition/pull/2485
> show what should we do, if we have error on 'import chainer'

- jsk_pcl_ros/include/jsk_pcl_ros/icp_registration.h
- jsk_pcl_ros/src/icp_registration_nodelet.cpp
fix publishDebugCloud to set correct header.
> fix publishDebugCloud

- doc/jsk_pcl_ros/nodes/pointcloud_screenpoint.md
I updated README of `PointcloudScreenpoint` and add/remove rosparams
All of the current valid rosparams are here:
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/cfg/PointcloudScreenpoint.cfg
> [PointcloudScreenpoint] update README

- jsk_perception/scripts/ssd_train_dataset.py
This error is introduced in #2491
> more fix for #2500

- jsk_recognition_utils/cmake/FindCython.cmake
> Include cython3 when searching

- jsk_perception/scripts/install_trained_data.py
fixes http://build.ros.org/job/Nbin_uF64__jsk_perception__ubuntu_focal_amd64__binary/1/console and http://build.ros.org/job/Mbin_uB64__jsk_perception__ubuntu_bionic_amd64__binary/91/console
> check if chainer is found before check version

- .travis.yml
- jsk_perception/scripts/install_trained_data.py
> add test to check #2533 regression

- jsk_recognition_utils/node_scripts/static_virtual_camera.py
see https://github.com/jsk-ros-pkg/jsk_recognition/pull/2558
> support ~image_transport for static_virtual_camera

- jsk_perception/src/virtual_camera_mono.cpp
for https://github.com/jsk-ros-pkg/jsk_demos/issues/1322
> add more debug info for virtual_camera_info

- .travis.yml
- fix decorator version
- decorator >= 5.0.0 is only for python3 but released for python2
- https://github.com/micheles/decorator/pull/100
> Fix travis 

- jsk_perception/package.xml
> fix typo in jsk_perception/package.xml

- doc/jsk_perception/nodes/paper_finder.md
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2542 のpaper_finderのドキュメントの説明文をきちんと書きました．
- Subscribing Topicに利用されるパラメータ条件を追加．
- Parametersの説明文を追加．
遅くなってしまい申し訳ありません．
> update description of the paper_finder document

- checkerboard_detector/src/checkerboard_detector.cpp
At present, it logs 0 because of using %d. However, we want to see the actual value, so I suggest using %f.
> use %f instead of %d

- doc/jsk_perception/nodes/aws_auto_checkin_app.rst
- doc/jsk_perception/nodes/aws_detect_faces.rst
- jsk_perception/node_scripts/aws_auto_checkin_app.py
- jsk_perception/node_scripts/aws_detect_faces.py
- jsk_perception/sample/sample_aws_auto_checkin_app.launch
- jsk_perception/sample/sample_aws_detect_faces.launch
Without this change, `client.initiate_auth` has failed with `botocore.exceptions.NoCredentialsError: Unable to locate credentials`. 
This error is solved by using AWS SDK for Python, boto3.
Following changes accompanying:
- Publish rects and class results for visualization
- Update json files for JSK users, please download from [here](https://drive.google.com/drive/folders/10kVoswI3EgDG4x1tTW0iSQkqUwsJkOqg?usp=sharing)
- Update description in documantation
cc: @iory
> [jsk_perception/aws_auto_checkin_app] Use search_faces_by_image() of Amazon Rekognition

- doc/jsk_perception/nodes/fisheye_stitcher.md
- jsk_perception/config/dual_fisheye_to_panorama/high_resolution_config.yaml
- jsk_perception/config/dual_fisheye_to_panorama/low_resolution_config.yaml
- jsk_perception/include/jsk_perception/dual_fisheye_to_panorama.h
- jsk_perception/include/jsk_perception/fisheye_stitcher.cpp
- jsk_perception/include/jsk_perception/fisheye_stitcher.hpp
- jsk_perception/sample/sample_dual_fisheye_to_panorama.launch
- jsk_perception/sample/sample_insta360_air.launch
- jsk_perception/src/dual_fisheye_to_panorama.cpp
Update DualFisheyeToPanorama node to support low resolution mode.
- Parameters
+ `~blend_image_width`
- image size used for panorama blending
+ `~blend_image_height`
- image size used for panorama blending
+ `~blend_param_p_wid`
- parameter used for panorama blending
+ `~blend_image_p_x1`
- parameter used for panorama blending
+ `~blend_param_row_start`
- parameter used for panorama blending
+ `~blend_param_row_end`
- parameter used for panorama blending
+ `~output_image_width`
- output panorama image size
+ `~output_image_height`
- output panorama image size
And update sample launch files to easily set these paremeters, add a calibration file for low resolution mode.
To use with low resolution mode.
```bash
roslaunch jsk_perception sample_insta360_air.launch panorama_resolution_mode:=low …
```
> Parameterize DualFisheyeToPanorama node

- jsk_perception/sample/sample_dual_fisheye_to_panorama.launch
- jsk_perception/sample/sample_insta360_air.launch
> [jsk_perception][insta360][dual_fisheye_to_panorama] Add always subscribe arg

- jsk_pcl_ros_utils/src/pointcloud_to_pcd_nodelet.cpp
> [jsk_pcl_ros_utils] use nodelet logger and fix logging info

- doc/jsk_perception/nodes/classification_node.md
- doc/jsk_perception/nodes/vqa_node.md
I added an explanation of sending multiple questions to server when we use VQA node.
We can send multiple questions with separating semicolon.
> [doc] Add explanation of sending multiple questions in vqa_node

- jsk_pcl_ros/src/octree_voxel_grid_nodelet.cpp
this PR supports `PointXYZI` in OctreeVoxelGrid nodelet.
> support pointxyzi in octree_voxel_grid_nodelet

- audio_to_spectrogram/LICENSE
- checkerboard_detector/LICENSE
- depth_image_publisher/LICENSE
- imagesift/LICENSE
- jsk_libfreenect2/LICENSE
- jsk_pcl_ros/LICENSE
- jsk_pcl_ros_utils/LICENSE
- jsk_perception/LICENSE
- jsk_recognition/LICENSE
- jsk_recognition_msgs/LICENSE
- jsk_recognition_utils/LICENSE
- resized_image_transport/LICENSE
- sound_classification/LICENSE
see https://github.com/ros/rosdistro/pull/45724#pullrequestreview-2837989427
> add LICENSE
