- jsk_pcl_ros/src/icp_registration_nodelet.cpp
ICPでリファレンスが空っぽの時にも結果を出すようにしました。(boundingboxとセットの時のみ)
中身は、
* 名前 -> NONE
* ポーズ -> bounding_boxのpose
* score -> 0
になります。
> add none result publisher when reference is empty

- jsk_perception/catkin.cmake
- jsk_perception/include/jsk_perception/colorize_labels.h
- jsk_perception/jsk_perception_nodelets.xml
- jsk_perception/src/colorize_labels.cpp
- jsk_perception/src/slic_superpixels.cpp
Add ColorizeLabels nodelet to colorize labels of result of segmentation.
Labels should be represented by `cv::Mat_<int>`
> [jsk_perception] Colorize labels

- jsk_perception/src/color_histogram.cpp
1. Support rect message out side of image
2. Use mask image in HSV histogram calculation
> [jsk_perception] Fix ColorHistogram minor bags:

- jsk_perception/cfg/ColorHistogramLabelMatch.cfg
- jsk_perception/include/jsk_perception/color_histogram_label_match.h
- jsk_perception/src/color_histogram_label_match.cpp
Make (kind of) mask image based on histogram coefficients.
This picture is based on OTSU's method
> [jsk_perception] Mask from histogram match in ColorHistogramLabelMatch

- jsk_perception/catkin.cmake
- jsk_perception/include/jsk_perception/find_object_on_plane.h
- jsk_perception/jsk_perception_nodelets.xml
- jsk_perception/package.xml
- jsk_perception/src/find_object_on_plane.cpp
Find object region from *2D* image and *3D* plane information.
> [jsk_perception] FindObjectOnPlane: Find object on plane from 2d binary image and 3-d polygon coefficients

- jsk_pcl_ros/README.md
- jsk_pcl_ros/cfg/MultiPlaneExtraction.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/multi_plane_extraction.h
- jsk_pcl_ros/src/multi_plane_extraction_nodelet.cpp
Add maginify parameter to remove points on the edge of polygons.
> [jsk_pcl_ros] Add magnify parameter to MultiPlaneExtraction

- jsk_pcl_ros/cfg/ParticleFilterTracking.cfg
I don't know why but small number particles may cause SEGV when starting up the program.
> [jsk_pcl_ros] Increase initial number of particles to avoid SEGV

- jsk_pcl_ros/catkin.cmake
- jsk_perception/catkin.cmake
- resized_image_transport/catkin.cmake
Do not include jsk_topic_tools/nodelet.cmake
because it is exported by CFG_EXTRAS
https://github.com/jsk-ros-pkg/jsk_recognition/pull/663/files#r23526346
> [jsk_pcl_ros, jsk_perception, resized_image_transport] Do not include jsk_topic_tools/nodelet.cmake

- jsk_pcl_ros/catkin.cmake
- jsk_pcl_ros/include/jsk_pcl_ros/particle_filter_tracking.h
- jsk_pcl_ros/package.xml
- jsk_pcl_ros/src/linemod_nodelet.cpp
- jsk_pcl_ros/src/pcl_util.cpp
- resized_image_transport/package.xml
- support both yaml 0.3.0(hydro) and yaml 0.5.0(indigo), not sure if this really works, but should be ok, I had same strategy for https://github.com/jsk-ros-pkg/jsk_model_tools/blob/1c1472f373288226abb74e3f2a9806c981f1e483/euscollada/src/collada2eus.cpp
- use this to call methods, I need this to compile on indigo, but not sure if   this really works, please check if this is correct @YuOhara, @garaemon 
- depending on cv_bridge is recommended, see  http://wiki.ros.org/indigo/Migration#OpenCV
> fix for indigo

- jsk_pcl_ros/README.md
- jsk_pcl_ros/include/jsk_pcl_ros/particle_filter_tracking.h
- jsk_pcl_ros/launch/particle_filter_localization.launch
- jsk_pcl_ros/src/particle_filter_tracking_nodelet.cpp
Exprimental implementation to cache result of ANN search.
mutex lock is too heavy, so we need to implement lock-free map like [Michaels Hash Map]( http://www.research.ibm.com/people/m/michael/spaa-2002.pdf)
> [jsk_pcl_ros] Cache result o nearest-negihbor search

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/jsk_pcl_nodelets.xml
Deprecate following nodelets in order to reduce compilcation time
* NodeletImageThrottle
* NodeletPointCloudThrottle
* NodeletImageMux
* NodeletImageDemux
I cannot find any program use it and we have better implementation in jsk_topic_tools
* OrganizePointCloud
We can use `jsk_pcl/DepthImageCreator` instead of this class
> [jsk_pcl_ros] Deprecate several nodelets

- jsk_pcl_ros/README.md
- jsk_pcl_ros/include/jsk_pcl_ros/hinted_stick_finder.h
- jsk_pcl_ros/src/hinted_stick_finder_nodelet.cpp
1. Use input pointcloud with normal not to run normal estimation in
HintedStickFinder
2. Add ~not_synchronize parameter to keep processing without more hint
> [jsk_pcl_ros] Optimized HintedStickFinder

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/README.md
- jsk_pcl_ros/include/jsk_pcl_ros/organized_pointcloud_to_point_indices.h
- jsk_pcl_ros/jsk_pcl_nodelets.xml
- jsk_pcl_ros/src/organized_pointcloud_to_point_indices_nodelet.cpp
Thanks to #762, I added nodelet which will publsh indices.
In addition, I added launch file which will publish pass_throughed image as below.
> add organized_pc_to_point_indics

- jsk_pcl_ros/src/icp_registration_nodelet.cpp
- jsk_perception/src/rgb_decomposer.cpp
targetのクラウドがemptyのときにプログラム自体が動かなくなってしまっていたので，
チェックして，空の時はDBL_MAXを返しつつそれ以降の計算はしないように変更しました．
> check target cloud data ifnot invalid

- jsk_pcl_ros/cfg/EnvironmentPlaneModeling.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/environment_plane_modeling.h
- jsk_pcl_ros/include/jsk_pcl_ros/geo_util.h
- jsk_pcl_ros/src/environment_plane_modeling_nodelet.cpp
- jsk_pcl_ros/src/geo_util.cpp
Optimize GridPlane::fillCellsFromPointCloud by using pcl::ExtractPolygonalPrismData and now it's much much faster than before
> [jsk_pcl_ros] Optimize GridPlane::fillCellsFromPointCloud 

- jsk_perception/launch/sparse_image_encoder.launch
- jsk_perception/launch/sparse_image_encoder_sample.launch
- jsk_perception/src/sparse_image_encoder.cpp
add feature to print point nums when encoding sparse image.
including example launch `jsk_perception/launch/sparse_image_encoder_sample.launch`
> [jsk_perception] print number of point when encoding sparse image

- jsk_perception/CMakeLists.txt
- jsk_perception/include/jsk_perception/fisheye_to_panorama.h
- jsk_perception/jsk_perception_nodelets.xml
- jsk_perception/launch/fisheye_to_panorama.launch
- jsk_perception/src/fisheye_to_panorama.cpp
For the time being, I added the nodelet which will convert fisheye imageto panorama VERY SIMPLELY
.
I refer most of all from this page -> http://polymathprogrammer.com/2009/10/15/convert-360-degree-fisheye-image-to-landscape-mode/
> [jsk_perception] add Simple Fisheye to Panorama

- jsk_pcl_ros/README.md
- jsk_pcl_ros/include/jsk_pcl_ros/torus_finder.h
- jsk_pcl_ros/src/torus_finder_nodelet.cpp
Add `geometry_msgs/PolygonStamped` interface to TorusFinder.
@orikuma 
もしもロバスト推定が必要なら使ってください.
eusから`geometry_msgs/PolygonStamped`を出せば、そこから3次元の円を推定します。
ただ、適当に重心とかから始めたら良いとは思います。
> [jsk_pcl_ros] Add geometry_msgs/PolygonStamped input for TorusFinder

- jsk_pcl_ros/README.md
- jsk_pcl_ros/cfg/MaskImageToDepthConsideredMaskImage.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/mask_image_to_depth_considered_mask_image.h
- jsk_pcl_ros/src/mask_image_to_depth_considered_mask_image_nodelet.cpp
* use image_view2 interaction_mode:grabcut_rect
* When use_mask_region, only mask image inside grabcut_rect area is extracted.
> [jsk_pcl_ros] extract only directed region of mask image

- jsk_perception/scripts/image_publisher.py
Prevent below error message and show error message instead.
```
File "/home/inagaki/ros/hydro/src/jsk-ros-pkg/jsk_recognition/jsk_perception/scripts/image_publisher.py", line 21, in <module>
image_message = bridge.cv2_to_imgmsg(image, encoding="bgr8")
File "/opt/ros/hydro/lib/python2.7/dist-packages/cv_bridge/core.py", line 232, in cv2_to_imgmsg
img_msg.height = cvim.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'
```
instead
```
[ERROR] [WallTime: 1429271489.289614] Did you set properly ~file_name param
```
> [jsk_perception] Add attributeError message to image_publisher.py

- jsk_pcl_ros/include/jsk_pcl_ros/mask_image_to_depth_considered_mask_image.h
- jsk_pcl_ros/launch/extract_only_directed_region_of_close_mask_image.launch
- jsk_pcl_ros/src/mask_image_to_depth_considered_mask_image_nodelet.cpp
- jsk_pcl_ros/src/resize_points_publisher_nodelet.cpp
- resized_image_transport/include/resized_image_transport/image_resizer_nodelet.h
- resized_image_transport/src/image_resizer_nodelet.cpp
* If you direct region of interest in interactive view, mask image callback is called in 3 node. (mask_image_to_depth_considered_mask_image_nodelet,   resize_points_publisher_nodelet,   image_resizer_nodelet)
* If you select wide region, output image will be coarse.
> add Resize rate feedback

- jsk_pcl_ros/src/icp_registration_nodelet.cpp
ICP die when the kdtree search are passed the point which include nan points.
I think this is not so good modification, because I need to insert these lines to all kind of these.
(I need to prepare non removal nodelet?)
> [jsk_pcl_ros] remove nan point before icp kdtree search

- jsk_pcl_ros/cfg/MaskImageToDepthConsideredMaskImage.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/mask_image_to_depth_considered_mask_image.h
- jsk_pcl_ros/launch/extract_only_directed_region_of_close_mask_image.launch
- jsk_pcl_ros/src/mask_image_to_depth_considered_mask_image_nodelet.cpp
- jsk_pcl_ros/src/resize_points_publisher_nodelet.cpp
- resized_image_transport/src/image_resizer_nodelet.cpp
Usually, we should use jsk_perception/apply_mask_image.cpp for applying mask image.
But by resize-feedback, cannot use apply_mask_image node.
Instead, publish applymaskimage by mask_image_to_depth_considered_mask_image node.
> [jsk_pcl_ros]  add apply mask image publisher

- jsk_pcl_ros/src/icp_registration_nodelet.cpp
icpは，外れ値ほど大きいので，
リファレンスがNONEの時にスコア０を返さないようにしました．
> [jsk_pcl_ros]change icp result when none reference

- jsk_perception/src/point_pose_extractor.cpp
* check if pcam intrinsicMatrix is valid
intrinsicMatrix of camera_info from usb_cam node (you can exec by rosrun usb_cam usb_cam_node) is invalid.
This resulted in the failure of #873 .
> [jsk_perception] check if pcam.intrinsicMatrix is valid

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/README.md
- jsk_pcl_ros/include/jsk_pcl_ros/normal_estimation_omp.h
- jsk_pcl_ros/jsk_pcl_nodelets.xml
- jsk_pcl_ros/src/normal_estimation_omp_nodelet.cpp
`jsk_pcl/NormalEstimatinOMP` is almost same as `pcl/NormalEstimationOMP` of `pcl_ros` but it DOES handle correct timestamp.
I will send it to upstream after they merge several serious pull request about timestamp of pcl_conversions.
> [jsk_pcl_ros] Add NormalEstimationOMP like pcl_ros but it can handle timestamp correctly

- jsk_perception/CMakeLists.txt
- jsk_perception/include/jsk_perception/sliding_window_object_detector_trainer.h
- jsk_perception/launch/sliding_window_object_detector_trainer.launch
- jsk_perception/src/sliding_window_object_detector_trainer_node.cpp
This node is to train the sliding_window_object_detector nodelet using the selected feature. Currently it is fixed to HOG with OpenCV SVM as the the trainer. 
- The node outputs a trained object classifier of type ".xml".
- It also outputs a trainer manifest in ".xml" format to the working directory. 
The trainer manifest file is important, which will be used to in the sliding_window_object_detector nodelet (I will update it soon) so that the detector can be calibrated with the parameters of the trainer automatically at runtime instead of manually adjusting parameters. Parameters such as the size of the detector window, which features were used, etc.
> Node to for training the classifier for Sliding Window Object Detector

- jsk_perception/src/apply_mask_image.cpp
I fixed bug caused by https://github.com/jsk-ros-pkg/jsk_recognition/pull/918 .
That bug appears when you have BGRA/RGBA input image.
Sorrry about that.
> [jsk_perception] Fix bug in apply_mask in converting BGRA/RGBA input image

- jsk_pcl_ros/include/jsk_pcl_ros/geo_util.h
- jsk_pcl_ros/src/geo_util.cpp
- jsk_pcl_ros/src/region_growing_multiple_plane_segmentation_nodelet.cpp
Fix computation of normal to decide order of vertices by comparing normals from vertices and coefficients
Add getNormalFromVertices method to polygon
> [jsk_pcl_ros/RegionGrowingMultiplePlaneSegmentation] Fix computation of normal to decide order of vertices

- resized_image_transport/include/resized_image_transport/image_processing_nodelet.h
- resized_image_transport/src/image_processing_nodelet.cpp
Do not require synchronized input topics of camera info and image unless ~use_camera_subscriber is true
> [resized_image_transport] Do not require synchronized input topics

- jsk_perception/src/gaussian_blur.cpp
- jsk_perception/src/kmeans.cpp
出力画像のエンコードが，
BGAが正解のところを入力画像のものを使うようになっていたので，
修正しました．
@wkentaro 
修正前
修正後
> [jsk_perception] fix output image encoding in kmeans and gaussian_blur

- jsk_pcl_ros/CMakeLists.txt
Fix for issue: particle_filter_tracker dies after startup when running in Ubuntu 14.04 indigo #984
Tested working on Ubuntu 14.04 indigo, openni2_launch, with Asus Xtion Pro.
> fix c++ version mismatch problem with boost

- resized_image_transport/src/image_processing_nodelet.cpp
> [resized_image_transport] Initialize vital_checkers first

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/include/jsk_pcl_ros/pointcloud_to_stl.h
- jsk_pcl_ros/jsk_pcl_nodelets.xml
- jsk_pcl_ros/src/pointcloud_to_stl_nodelet.cpp
- jsk_pcl_ros/srv/SetPointCloud2.srv
@mmurooka 
Now I implementing pointcloud2STL.
I'm wondering what kind of service should be useful...
At this time, I prepared
- subscribe which just subscribe pointcloud and save it as STL in /tmp
- service which will export the STL and return filename
createURDF and spawnURDF is not implemented yet
What kind of the interface (rossevice call?) do you think will be good?
> [jsk_pcl_ros] add pointcloud_to_stl nodelet

- imagesift/src/imagesift.cpp
When width or height of the input mask image is 0, imagesift process die.
To avoid this, when width or height is 0, use all region of image instead of mask image region.
> [imagesift] modify mask region when mask region has no region

- jsk_pcl_ros/launch/pointcloud_screenpoint.launch
machine tag should defined in uppper launch file, for example https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_pr2_robot/jsk_pr2_startup/pr2.launch#L24
> machine tag should defined in somewhere else, not here

- jsk_pcl_ros/README.md
- jsk_pcl_ros/cfg/PoseWithCovarianceStampedToGaussianPointCloud.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/pose_with_covariance_stamped_to_gaussian_pointcloud.h
- jsk_pcl_ros/src/pose_with_covariance_stamped_to_gaussian_pointcloud_nodelet.cpp
normalize method: normalize_area and normalize_height
When you want to visualize smaller covariance, the maximum height of normal distribution will be higher
and you cannot get good visualization.
`normalize_height` is introduced to solve that situation, the height of maximum value of normal distribution will be normalized to a fixed value.
> [jsk_pcl_ros/PoseWithCovarianceStampedtoGussianPointCloud] Add new

- jsk_pcl_ros/src/attention_clipper_nodelet.cpp
1. fixing name confliction of iteration index
2. Use std::runtime_error to catch exception
> [jsk_pcl_ros/AttentionClipper] Fix compilation warning:

- jsk_perception/CMakeLists.txt
This is another PR of https://github.com/jsk-ros-pkg/jsk_recognition/pull/749
This PR is needed to execute elevator demo.
(I think now euslisp is stable enough)
> [jsk_perception] uncomment generate template

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/src/build_check.cpp.in
Check all the methods and functions are implemented compiling build_check.cpp with all the headeres except for kinfu and
point_types.h.
build_check.cpp is automatically generated with all the header neames
and build_check.cpp.in.
1. When generating shared libraries, gcc does not require implementations.
2. When loading a nodelet from shared libarries, all the functions/methods are required to be implemented.
3. When compiling exeuctable, all the functions are required to be implemented.
This test use 3. to test 2.
> [jsk_pcl_ros] Check all the methods and functions are implemented

- jsk_pcl_ros/include/jsk_pcl_ros/geo_util.h
- jsk_pcl_ros/src/geo_util.cpp
EarClip of pcl 1.7.2 (hydro) has a fatal bug and copied the latest implementation from
current master and rename it as EarClipPatched.
We cam remove the codes after we deprecate hydro.
> [jsk_pcl_ros] Fix Polygon::decomposeToTriangles.

- jsk_pcl_ros/launch/sample_select_laser_pointcloud_from_image.launch
xtionでも使えるようにしてみました．
```bash
roslaunch jsk_pcl_ros sample_select_laser_pointcloud_from_image.launch INPUT_IMAGE:=/xtion/rgb/image_raw INPUT_CAMERA_INFO:=/xtion/rgb/camera_info INPUT_POINT_CLOUD:=/xtion/depth/points
```
https://github.com/jsk-ros-pkg/jsk_common/issues/1112
> utilize arguments in sample_select_laser_pointcloud_from_image.launch

- jsk_recognition_utils/CMakeLists.txt
- jsk_recognition_utils/package.xml
to solve build error
http://jenkins.ros.org/view/HbinP32/job/ros-hydro-jsk-recognition-utils_binarydeb_precise_i386/5/console
```
[ 16%] Building CXX object CMakeFiles/jsk_recognition_utils.dir/src/grid_map.cpp.o
/usr/lib/ccache/c++   -Djsk_recognition_utils_EXPORTS -DROS_PACKAGE_NAME=\"jsk_recognition_utils\" -DROSCONSOLE_BACKEND_LOG4CXX -DUSE_OLD_YAML -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -DNDEBUG  -fPIC -I/opt/ros/hydro/include -I/opt/ros/hydro/include/opencv -I/usr/include/eigen3 -I/usr/include/pcl-1.7 -I/usr/include/ni -I/usr/include/vtk-5.8 -I/usr/include/qhull -I/tmp/buildd/ros-hydro-jsk-recognition-utils-0.3.2-0precise-20150905-0817/include    -o CMakeFiles/jsk_recognition_utils.dir/src/grid_map.cpp.o -c …
```
> [jsk_recognition_utils] Depends on visualization_msgs

- jsk_pcl_ros/CMakeLists.txt
Little bit a tricky, do not compile build_check.cpp in normal compilation because ros buildfarm looks fail
to build it (memory starvation?).
http://jenkins.ros.org/view/IbinS64/job/ros-indigo-jsk-pcl-ros_binarydeb_saucy_amd64/69/console
```
[ 56%] Building CXX object CMakeFiles/build_check.dir/build_check.cpp.o
/usr/lib/ccache/c++   -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\"jsk_pcl_ros\" -DUSE_OLD_YAML -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -D_FORTIFY_SOURCE=2   -Wno-deprecated -fopenmp -O2 -g -DNDEBUG -I/tmp/buildd/ros-indigo-jsk-pcl-ros-0.3.5-0saucy-20150910-0811/obj-x86_64-linux-gnu/devel/include -I/usr/include/vtk-5.8 -I/usr/include/opencv -I/tmp/buildd/ros-indigo-jsk-pcl-ros-0.3.5-0saucy-20150910-0811/include …
```
> [jsk_pcl_ros] Do not compile build_check.cpp in normal compilation time, just in run_tests

- jsk_pcl_ros/CMakeLists.txt
@garaemon さん，
先ほど話していたとおり
link_librariesを使っているところを
target_link_librariesを使うように戻しました．
( https://github.com/jsk-ros-pkg/jsk_recognition/commit/f13da3419e42aa6e50eff6b1f7eaf18ddc601eb5 を戻したことになると思います．)
https://github.com/jsk-ros-pkg/jsk_recognition/commit/778b35704ea6e795a72801cfdb6bfe14d871231b#diff-250fce108c6e3969cbb9873e11c10453R437 の
```
target_link_libraries(range_sensor_error_visualization jsk_pcl_ros)
```
がないと以下のエラーがでるので加えましたが合っていますでしょうか．
```
[jsk_pcl_ros] CMakeFiles/range_sensor_error_visualization.dir/tool/range_sensor_error_visualization.cpp.o: In function `publishImage(cv::Mat const&, ros::Publisher&)':
[jsk_pcl_ros] /home/leus/ros/hydro/src/jsk-ros-pkg/jsk_recognition/jsk_pcl_ros/tool[ 44%] /range_sensor_error_visualization.cpp:108: undefined reference to `ros::Time::now()' …
```
> [jsk_pcl_ros] use target_link_libraries instead of link_libraries

- doc/jsk_pcl_ros/nodes/region_growing_multiple_plane_segmentation.md
- jsk_pcl_ros/cfg/RegionGrowingMultiplePlaneSegmentation.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/region_growing_multiple_plane_segmentation.h
- jsk_pcl_ros/src/region_growing_multiple_plane_segmentation_nodelet.cpp
region growing multiplane segmentationの中でconvexと判定される面積にmin-maxの制限を書けられるようにしました．
これまでのプログラムに影響が内容にdefaultのmax_areaは100[m^2]と大きめにしました．
ご確認よろしくお願いします，
> Set min max area

- jsk_recognition_utils/python/jsk_recognition_utils/visualize.py
The error outputs is:
```
[ERROR] [WallTime: 1444865314.827458] bad callback: <bound method Subscriber.callback of <message_filters.Subscriber instance at 0x7fb424165fc8>>
File "/home/wkentaro/ros/indigo_parent/install/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
cb(msg)
File "/home/wkentaro/ros/indigo_parent/install/lib/python2.7/dist-packages/message_filters/__init__.py", line 74, in callback
self.signalMessage(msg)
File "/home/wkentaro/ros/indigo_parent/install/lib/python2.7/dist-packages/message_filters/__init__.py", line 56, in signalMessage
cb(*(msg + args))
File "/home/wkentaro/ros/indigo_parent/install/lib/python2.7/dist-packages/message_filters/__init__.py", line 225, in add
self.signalMessage(*msgs)
File …
```
> [jsk_recognition_utils] Handle canvas to get safely plot image

- jsk_pcl_ros/src/viewpoint_sampler.cpp
```
In [2]: 1.6-1.2 > 0.4
Out[2]: True
In [4]: 2.0-1.2 > 0.8
Out[4]: False
```
みたいな感じで，doubleの比較で意図と違う動作になっていて，それでposeにnanが入っていたので，
1.001倍を加えました．
（もっと良い方法がある気もしますが，)普通に使う分には1.001倍の影響がないと思います
fyi @rkoyama1623
> [jsk_pcl_ros]commit for prevventing rounding error

- jsk_pcl_ros/CMakeLists.txt
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1281 よりもこちらの方が，
pointcloud_moveit_filter.cppのコンパイルを維持したまま，
octomap関連の干渉がなくなるので良いかもしれません．
> remove moveit_ros_perception from catkin component

- jsk_pcl_ros/launch/hsi_color_filter.launch
Add suffix for manager name to enable multiple hsi_color_filter.launch.
Previously, manager name conflict occurred.
This is originally derived from https://github.com/jsk-enshu/robot-programming/pull/68.
> Add suffix for manager name to enable multiple hsi_color_filter.launch

- doc/jsk_perception/nodes/split_fore_background.rst
- jsk_perception/node_scripts/split_fore_background.py
It supports both 16UC1 and 32FC1.
> [jsk_perception] Fix supported encodings of split_fore_background.py

- jsk_pcl_ros/test/test_euclidean_segmentation.test
This test on travis fails a lot, so make the threshold lower.
> [jsk_pcl_ros] Make test for euclidean segmentation reliable

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/cfg/InteractiveCuboidLikelihood.cfg
- jsk_pcl_ros/cfg/PlaneSupportedCuboidEstimator.cfg
This commit give up to re-use definition of dynamic_reconfigure because
generate_dynamic_reconfigure_options automatically install cpp files
estimated from cfg files.
closes https://github.com/jsk-ros-pkg/jsk_recognition/issues/1401
> [jsk_pcl_ros] Remove cuboid_parameter.cfg and add InteractiveCuboidLikelihood.cfg and PlaneSupportedCuboidEstimator.cfg.

- doc/jsk_pcl_ros/nodes/plane_concatenator.md
- jsk_pcl_ros/cfg/PlaneConcatenator.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/plane_concatenator.h
- jsk_pcl_ros/src/multi_plane_extraction_nodelet.cpp
- jsk_pcl_ros/src/plane_concatenator_nodelet.cpp
- jsk_perception/src/polygon_array_color_histogram.cpp
- jsk_recognition_utils/include/jsk_recognition_utils/pcl_ros_util.h
- jsk_recognition_utils/src/pcl_ros_util.cpp
Modified:
jsk_pcl_ros/src/multi_plane_extraction_nodelet.cpp
jsk_perception/src/polygon_array_color_histogram.cpp
jsk_recognition_utils/include/jsk_recognition_utils/pcl_ros_util.h
jsk_recognition_utils/src/pcl_ros_util.cpp
>  [jsk_pcl_ros] Check header.frame_id before resolving 3-D spacially

- jsk_pcl_ros/scripts/install_test_data.py
Modified:
jsk_pcl_ros/scripts/install_test_data.py
> [jsk_pcl_ros] Cache test_data to ROS home

- jsk_perception/node_scripts/tile_image.py
- jsk_recognition_utils/python/jsk_recognition_utils/visualize.py
1. Disable approximate sync for hydro. it's not supported on hydro
2. Use PIL.Image.frombytes instead of PIL.Image.fromstring
> [jsk_perception] Fix tile_image.py for hydro.

- jsk_pcl_ros/include/jsk_pcl_ros/region_growing_multiple_plane_segmentation.h
- jsk_pcl_ros/include/jsk_pcl_ros/torus_finder.h
- jsk_pcl_ros/src/region_growing_multiple_plane_segmentation_nodelet.cpp
- jsk_pcl_ros/src/torus_finder_nodelet.cpp
Modified:
- jsk_pcl_ros/include/jsk_pcl_ros/region_growing_multiple_plane_segmentation.h
- jsk_pcl_ros/include/jsk_pcl_ros/torus_finder.h
- jsk_pcl_ros/src/region_growing_multiple_plane_segmentation_nodelet.cpp
- jsk_pcl_ros/src/torus_finder_nodelet.cpp
> [jsk_pcl_ros] Do not call callback until initialization done

- doc/jsk_perception/nodes/polygon_array_color_likelihood.md
- jsk_perception/CMakeLists.txt
- jsk_perception/include/jsk_perception/polygon_array_color_likelihood.h
- jsk_perception/package.xml
- jsk_perception/src/polygon_array_color_likelihood.cpp
…
Modified:
- doc/jsk_perception/nodes/polygon_array_color_likelihood.md
- jsk_perception/CMakeLists.txt
- jsk_perception/include/jsk_perception/polygon_array_color_likelihood.h
- jsk_perception/package.xml
- jsk_perception/src/polygon_array_color_likelihood.cpp
> [jsk_perception] Read reference color histogram from a yaml file in PolygonArrayColorLikelihood to avoid race condition between input topics

- jsk_pcl_ros_utils/CMakeLists.txt
- jsk_pcl_ros_utils/package.xml
Modified:
- jsk_pcl_ros_utils/package.xml
> [jsk_pcl_ros_utils] Remove sklearn from build_depend

- .travis.rosinstall.jade
- jsk_perception/jsk_perception_nodelets.xml
- jsk_perception/src/color_histogram.cpp
- jsk_perception/src/edge_detector.cpp
- jsk_perception/src/hough_circles.cpp
- jsk_perception/src/sparse_image_decoder.cpp
- jsk_perception/src/sparse_image_encoder.cpp
Modified:
- jsk_perception/src/color_histogram.cpp
- jsk_perception/src/edge_detector.cpp
- jsk_perception/src/hough_circles.cpp
- jsk_perception/src/sparse_image_decoder.cpp
- jsk_perception/src/sparse_image_encoder.cpp
> [jsk_perception] Stop using deprecated PLUGINLIB_DECLARE_CLASS

- jsk_pcl_ros/src/euclidean_cluster_extraction_nodelet.cpp
If input pointcloud is empty, publish empty result.
> [jsk_pcl_ros] Fix euclidean segmentation for empty input.

- doc/jsk_pcl_ros/nodes/particle_filter_tracking.md
- jsk_pcl_ros/cfg/ParticleFilterTracking.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/particle_filter_tracking.h
- jsk_pcl_ros/launch/tabletop_tracking.launch
- jsk_pcl_ros/src/particle_filter_tracking_nodelet.cpp
- jsk_recognition_utils/include/jsk_recognition_utils/pcl_util.h
- jsk_recognition_utils/include/jsk_recognition_utils/time_util.h
- jsk_recognition_utils/src/pcl_util.cpp
- jsk_recognition_utils/src/time_util.cpp
Sample launch is tabletop_tracking.launch
Now particle_filter_tracking can skip tracking when object looks stable
and difference pointcloud (which should be computed by
octree_change_detector)
are far from target object.
It can dramatically decrease computation.
>  [jsk_pcl_ros] Add new feature to skip tracking according to     background substraction.

- jsk_pcl_ros/jsk_pcl_nodelets.xml
- jsk_pcl_ros_utils/CMakeLists.txt
- jsk_pcl_ros_utils/jsk_pcl_nodelets.xml
When I run nodelets defined in jsk_pcl_ros_utils like colorize_distance_from_plane, nodelets abort with following errors. 
```
$ rosrun jsk_pcl_ros colorize_distance_from_plane
[ INFO] [1453269719.926632252]: Initializing nodelet with 4 worker threads.
[ERROR] [1453269720.344240963]: Failed to load nodelet [/colorize_distance_from_plane] of type [jsk_pcl/ColorizeDistanceFromPlane] even after refreshing the cache: MultiLibraryClassLoader: Could not create object of class type jsk_pcl_ros::ColorizeDistanceFromPlane as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[ERROR] [1453269720.344310564]: The error before refreshing the cache was: MultiLibraryClassLoader: Could not create object of class type …
```
> Use jsk pcl ros utils namespace in jsk pcl nodelets

- doc/jsk_pcl_ros/nodes/octree_voxel_grid.md
- jsk_pcl_ros/cfg/OctreeVoxelGrid.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/octree_voxel_grid.h
- jsk_pcl_ros/src/octree_voxel_grid_nodelet.cpp
- jsk_recognition_utils/include/jsk_recognition_utils/pcl_ros_util.h
- jsk_recognition_utils/src/pcl_ros_util.cpp
Modified:
- doc/jsk_pcl_ros/nodes/octree_voxel_grid.md
- jsk_pcl_ros/cfg/OctreeVoxelGrid.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/octree_voxel_grid.h
- jsk_pcl_ros/src/octree_voxel_grid_nodelet.cpp
- jsk_recognition_utils/include/jsk_recognition_utils/pcl_ros_util.h
- jsk_recognition_utils/src/pcl_ros_util.cpp
> [jsk_pcl_ros] Automatically detect point type in OctreeVoxelGrid

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/test/test_extract_indices.cpp
- jsk_pcl_ros/test/test_extract_indices.test
Do not depends on test data, just create dummy data in code on the fly.
I think original test case is unstable because of reading stdout.
> [jsk_pcl_ros] Simplify test case of ExtractIndices.

- jsk_pcl_ros/jsk_pcl_nodelets.xml
this node is moved to jsk_pcl_ros_utils
but this is necessary for compatibility.
Modified:
- jsk_pcl_ros/jsk_pcl_nodelets.xml
> [jsk_pcl_ros] List missing PointIndicesToMaskImage as nodelet

- jsk_pcl_ros/src/linemod_nodelet.cpp
Modified:
- jsk_pcl_ros/src/linemod_nodelet.cpp
> [jsk_pcl_ros] Fix indent of linemod_nodelet.cpp

- jsk_perception/node_scripts/bof_histogram_extractor.py
Modified:
- jsk_perception/node_scripts/bof_histogram_extractor.py
> [jsk_perception] Skip for empty sift features

- jsk_pcl_ros/CMakeLists.txt
- jsk_perception/CMakeLists.txt
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1528 を見ていて，
indigo以降では，
`find_package(robot_self_filter)`と`pkg_check_modules(robot_self_filter robot_self_filter QUIET)`が
両方呼ばれるようになってしまっていて，悪さをしている気がしました．
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/CMakeLists.txt#L45
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/CMakeLists.txt#L194
https://travis-ci.org/mmurooka/jsk_recognition/builds/107934581で
JSKのtravisテストは通ることは確認しましたが，
UとVのdeb用のbuildも確認することはできるでしょうか．
> [jsk_perception] Call one of find_package or pkg_check_modules for robot_self_filter

- jsk_pcl_ros/CMakeLists.txt
Following error is fixed.
```
$ catkib b jsk_pcl_ros -v -i
... 
jsk_pcl_ros] Linking CXX executable /home/leus/ros/indigo/devel/lib/jsk_pcl_ros/kinfu                                                                                                                     [495/1963]
[jsk_pcl_ros] [ 98%] Built target kinfu
[jsk_pcl_ros] Linking CXX shared library /home/leus/ros/indigo/devel/lib/libjsk_pcl_ros_base.so
[jsk_pcl_ros] [ 98%] Built target jsk_pcl_ros_base
[jsk_pcl_ros] Scanning dependencies of target jsk_pcl_ros
[jsk_pcl_ros] [100%] Building CXX object CMakeFiles/jsk_pcl_ros.dir/src/kinfu_nodelet.cpp.o
[jsk_pcl_ros] Linking CXX shared library /home/leus/ros/indigo/devel/lib/libjsk_pcl_ros_moveit.so
[jsk_pcl_ros] [100%] Built target jsk_pcl_ros_moveit
[jsk_pcl_ros] Linking CXX shared …
```
> [jsk_pcl_ros/CMakeLists.txt] Fix link libraries when building kinfu

- .travis.rosinstall.jade
Closes #1414
Because ros-jade-octomap-mapping and ros-jade-octomap-server is
released.
Modified:
- .travis.rosinstall.jade
> Remove octomap_mapping from rosinstall on travis testing

- .travis.yml
- jsk_perception/CMakeLists.txt
- jsk_perception/sample/sample_bing.launch
- jsk_perception/sample/sample_bof_object_recognition.launch
- jsk_perception/test/apply_mask_image.test
- jsk_perception/test/bing.test
- jsk_perception/test/bof_object_recognition.test
- jsk_perception/test/colorize_float_image.test
- jsk_perception/test/colorize_labels.test
- jsk_perception/test/image_cluster_indices_decomposer.test
- jsk_perception/test/kmeans.test
- jsk_perception/test/selective_search.test
- jsk_perception/test/slic_super_pixels.test
Closes #1656
This has been overlooked by https://github.com/jsk-ros-pkg/jsk_travis/issues/254 and https://github.com/jsk-ros-pkg/jsk_travis/issues/253 .
> Fix test failures of jsk_perception on Travis

- jsk_pcl_ros/CMakeLists.txt
This is from same motivation as https://github.com/jsk-ros-pkg/jsk_recognition/pull/1726.
cc @iory
> Refactor deprecated node compilation moved to jsk_pcl_ros_utils

- doc/jsk_pcl_ros/calibration.md
- add approximate_sync information in depth_error.launch 
- modified topic name ```depth_error_linear_regression``` to ```depth_error_logistic_regression```
If there is any problem, please let me know.
> [doc/jsk_pcl_ros/calibration.md] add approximate_sync information and modified depth_error_linear_regression to logistic

- doc/jsk_pcl_ros_utils/nodes/point_indices_to_mask_image.md
- jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/point_indices_to_mask_image.h
- jsk_pcl_ros_utils/src/point_indices_to_mask_image_nodelet.cpp
- jsk_pcl_ros_utils/test/test_point_indices_to_mask_image.py
- jsk_pcl_ros_utils/test/test_point_indices_to_mask_image.test
Because synchronization cause trouble sometimes, and in most cases image size is static.
> Convert point indices to mask w/o sync if it's static

- jsk_perception/node_scripts/fast_rcnn.py
To deal with size of rects_orig is equal to 0, return from callback
> [jsk_perception/fast_rcnn] Modified avoiding size of rects is 0 case

- jsk_pcl_ros/src/extract_indices_nodelet.cpp
This is necessary in order not to stop the transport pipeline which requires organized point cloud.
> Publish correct size cloud even with empty indices for ExtractIndices

- jsk_pcl_ros/src/extract_indices_nodelet.cpp
Currently the node publishes point cloud with height=0, width=0 with empty point cloud.
> Extract indices correctly with empty cloud

- jsk_pcl_ros/src/parallel_edge_finder_nodelet.cpp
advertise function defined at [here]( https://github.com/jsk-ros-pkg/jsk_common/blob/master/jsk_topic_tools/include/jsk_topic_tools/connection_based_nodelet.h#L154-L156) should be used. Otherwise, topics are never subscribed.
> [jsk_pcl_ros][BugFix] use advertise function defined in ConnectionBasedNodelet class.

- jsk_pcl_ros/src/edge_depth_refinement_nodelet.cpp
this is very complicated bug..
INPUT (before refining edge)
OUTPUT (after refining edge) (incorrect: before this PR)
edges which consists of single cluster disappear. this is bug.
OUTPUT (after refining edge) (correct: after this PR)
bug is fixed.
> [jsk_pcl_ros][BugFix] Fix duplication check edge depth refinement

- jsk_perception/src/polygon_to_mask_image.cpp
same with https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/src/polygon_array_to_label_image.cpp#L113-L115 .
> [jsk_perception] add warning message when no camera info is available.

- doc/jsk_pcl_ros_utils/nodes/cluster_point_indices_to_point_indices.rst
- jsk_pcl_ros_utils/CMakeLists.txt
- jsk_pcl_ros_utils/cfg/ClusterPointIndicesToPointIndices.cfg
- jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/cluster_point_indices_to_point_indices.h
- jsk_pcl_ros_utils/jsk_pcl_nodelets.xml
- jsk_pcl_ros_utils/src/cluster_point_indices_to_point_indices_nodelet.cpp
- jsk_pcl_ros_utils/test/cluster_point_indices_to_point_indices.test
- jsk_pcl_ros_utils/test/test_cluster_point_indices_to_point_indices.py
This node is required to get specified cluster's point cloud for later processing.
like
clusters -> point indices with index 1 -> multi plane extraction -> place can on the plane.
cc @furushchev
> Convert cluster indices to point indices with index in rosparam

- jsk_pcl_ros/CMakeLists.txt
The missing dirs are: config, launch, sample.
> Install missing dirs for jsk_pcl_ros

- jsk_pcl_ros/package.xml
This is necessary to run install script on CMakeLists.txt.
> Add missing build_depend on jsk_data

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/package.xml
rewrite #1828
1. just change the order in find_package
2. do not have to add genmsg to build_depend
3. do not add 'missing components' in find package (https://github.com/jsk-ros-pkg/jsk_recognition/pull/1828/commits/c54d279c3c689d649e0e5ce6e6423911639686f0)
by the wey, why did you add these missing components? did `catkin_lint` said so?
- Missing installation of executables
- Fix missing dependency declaration of jsk_pcl_ros
- Fix order of components in find_package of jsk_pcl_ros
> Fix configuration of jsk_pcl_ros

- jsk_pcl_ros/package.xml
Some node in jsk_perception is used in the sample launch files in jsk_pcl_ros,
and this is why jsk_perception is added as run_depend.
However, dependency on jsk_perception by jsk_pcl_ros always requires build of
jsk_perception even when the user want to use jsk_pcl_ros only.
I think this is problem, because jsk_perception is also a large package,
and recognition packages for 2D and 3D should be separated.
> Remove dependency on jsk_perception for separated build

- jsk_perception/src/sparse_image_encoder.cpp
to fix
```
In file included from /opt/ros/indigo/include/nodelet/nodelet.h:39:0,
from /home/k-okada/catkin_ws/ws_jsk_recognition/src/jsk_recognition/jsk_perception/src/sparse_image_encoder.cpp:7:
/home/k-okada/catkin_ws/ws_jsk_recognition/src/jsk_recognition/jsk_perception/src/sparse_image_encoder.cpp: In member function ‘void jsk_perception::SparseImageEncoder::do_work(const ImageConstPtr&, std::string)’:
/opt/ros/indigo/include/ros/console.h:342:176: warning: unknown conversion type character 0xa in format [-Wformat=]
::ros::console::print(filter, __rosconsole_define_location__loc.logger_, __rosconsole_define_location__loc.level_, __FILE__, __LINE__, __ROSCONSOLE_FUNCTION__, __VA_ARGS__)
^
/opt/ros/indigo/include/ros/console.h:345:5: note: in expansion of macro …
```
> sparse_image_encoder.cpp: need to escape %

- jsk_pcl_ros/package.xml
Reverts jsk-ros-pkg/jsk_recognition#1820
But is that ok to merge this before releasing 0.3.22?
It seems better to release this at 0.4.0: #1854
> Revert "Remove dependency on jsk_perception for separated build"

- jsk_perception/CMakeLists.txt
- jsk_perception/euslisp/eusmodel_template_gen_utils.l
http://build.ros.org/job/Jbin_uT64__jsk_perception__ubuntu_trusty_amd64__binary/49/console
```
09:27:16 Scanning dependencies of target eusmodel_template
09:27:16 make[4]: Leaving directory `/tmp/binarydeb/ros-jade-jsk-perception-0.3.22/obj-x86_64-linux-gnu'
09:27:16 make -f CMakeFiles/eusmodel_template.dir/build.make CMakeFiles/eusmodel_template.dir/build
09:27:16 make[4]: Entering directory `/tmp/binarydeb/ros-jade-jsk-perception-0.3.22/obj-x86_64-linux-gnu'
09:27:16 /usr/bin/cmake -E cmake_progress_report /tmp/binarydeb/ros-jade-jsk-perception-0.3.22/obj-x86_64-linux-gnu/CMakeFiles 
09:27:16 [ 31%] Generating ../sample/rimokon-pose.launch, ../sample/milktea-box.launch
09:27:16 cd /tmp/binarydeb/ros-jade-jsk-perception-0.3.22/sample && …
```
> failing at build firm

- jsk_perception/package.xml
http://build.ros.org/job/Jbin_uV32__jsk_perception__ubuntu_vivid_i386__binary/56/console
> CMakeLists.txt : jsk_data is required in build time, used in scripts/install_sample_data

- jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/plane_rejector.h
- jsk_pcl_ros_utils/src/plane_rejector_nodelet.cpp
Add allow_flip option in order to pass planes which has reversed normal vector relative to reference axis in plane_rejector.
Default value is false and it does not affect original behavior.
> [jsk_pcl_ros_utils] Add allow_flip option to plane rejector

- jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp
Empty indices [] should be inserted when skipping with max/min size rosparam specification,
because skipping removes the information about index which is necessary for example to get label value correctly.
> Preserve index of cluster_indices even with max/min size

- jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp
This is necessary for subscriber to notice which pose in `~centoid_pose_array` (geometry_msgs/PoseArray)
is invalid and should not be used.
> Set invalid centroid for empty extracted cloud with indices

- doc/jsk_perception/nodes/fcn_object_segmentation.rst
- jsk_perception/node_scripts/fcn_object_segmentation.py
This does not change the current behavior. As `~proba_threshold`, for example we can set `0.5` to get confident label output.
> Set bg label for uncertain region of FCN prediction

- checkerboard_detector/CMakeLists.txt
- checkerboard_detector/cfg/CheckerboardDetector.cfg
- checkerboard_detector/package.xml
- checkerboard_detector/src/checkerboard_detector.cpp
cv::CALIB_CB_ADAPTIVE_THRESH was effective.
http://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#findchessboardcorners
> [checkerboard_detector] enable to select option for cv::findChessboardCorners from dynamic reconfigure

- jsk_perception/launch/fcn_object_segmentation.launch
- jsk_perception/node_scripts/apply_context_to_label_probability
- jsk_perception/sample/sample_apply_context_to_label_probability.launch
- jsk_perception/sample/sample_fcn_object_segmentation.launch
- jsk_recognition_msgs/CMakeLists.txt
- jsk_recognition_msgs/srv/SetLabels.srv
We sometimes need to apply context to the object segmentation result.
```
<rosparam>
candidates:
- 0   # background
- 15  # person
</rosparam>
```
> Node to apply context to label probability

- jsk_pcl_ros/jsk_pcl_nodelets.xml
we can compile jsk_pcl_ros but we cannot load nodelets written after this typo
> [jsk_pcl_ros] fix typo in jsk_pcl_nodelets.xml

- doc/jsk_pcl_ros/nodes/image_rotate_nodelet.rst
image_rotate is now merged to ros-perception/image_pipeline
I add doc to guide ros wiki.
> [doc] add deprecated ImageRotateNodelet doc

- doc/jsk_perception/nodes/split_fore_background.rst
- jsk_perception/node_scripts/split_fore_background.py
- jsk_perception/test/split_fore_background.test
This breaks the API, so we need to merge this for next major release.
> [Major Release] Publish only masks by split_fore_background.py

- jsk_pcl_ros/CMakeLists.txt
- jsk_perception/CMakeLists.txt
- jsk_recognition_msgs/CMakeLists.txt
- jsk_recognition_msgs/package.xml
- jsk_recognition_msgs/srv/CallPolygon.srv
- jsk_recognition_msgs/srv/CallSnapIt.srv
- jsk_recognition_msgs/srv/CheckCircle.srv
- jsk_recognition_msgs/srv/CheckCollision.srv
- jsk_recognition_msgs/srv/EnvironmentLock.srv
- jsk_recognition_msgs/srv/EuclideanSegment.srv
- jsk_recognition_msgs/srv/ICPAlign.srv
- jsk_recognition_msgs/srv/ICPAlignWithBox.srv
- jsk_recognition_msgs/srv/NonMaximumSuppression.srv
- jsk_recognition_msgs/srv/PolygonOnEnvironment.srv
- jsk_recognition_msgs/srv/RobotPickupReleasePoint.srv
- jsk_recognition_msgs/srv/SetDepthCalibrationParameter.srv
- jsk_recognition_msgs/srv/SetTemplate.srv
- jsk_recognition_msgs/srv/SnapFootstep.srv
- jsk_recognition_msgs/srv/SwitchTopic.srv
- jsk_recognition_msgs/srv/TowerPickUp.srv
- jsk_recognition_msgs/srv/TowerRobotMoveCommand.srv
- jsk_recognition_msgs/srv/TransformScreenpoint.srv
- jsk_recognition_msgs/srv/UpdateOffset.srv
- jsk_recognition_msgs/srv/WhiteBalance.srv
- jsk_recognition_msgs/srv/WhiteBalancePoints.srv
Related to https://github.com/jsk-ros-pkg/jsk_recognition/pull/1827
- jsk_pcl_ros/srv -> jsk_recognition_msgs/srv
- jsk_perception/srv -> jsk_recognition_msgs/srv
TODO
- 1. Migrate current code for srv files in jsk_recognition_msgs
- 2. Remove srv files in jsk_pcl_ros and jsk_perception
> [Major Release] Copy jsk_pcl_ros/srv and  jsk_perception/srv files to jsk_recognition_msgs

- .travis_before_script_pcl1.8.bash
``` bash
% rospack depends1 jsk_pcl_ros_utils | grep pcl_conversions
pcl_conversions
% cat $(rospack find pcl_conversions)/package.xml | grep libpcl
<build_depend>libpcl-all-dev</build_depend>
<run_depend>libpcl-all</run_depend>
<run_depend>libpcl-all-dev</run_depend>
```
> Need to install pcl_conversions from source for PCL1.8

- jsk_pcl_ros/src/pointcloud_database_server_nodelet.cpp
Cloud msgs grows periodly because the same cloud is added when timer-callback is driven.
Therfore, moved to Initialization of  cloud msg.
This may be bug-fix. changed in https://github.com/jsk-ros-pkg/jsk_recognition/pull/1926
@knorth55  please check this.
> [jsk_pcl_ros/pointcloud_dataserver] remove adding unneeded cloud

- doc/jsk_pcl_ros_utils/nodes/pointcloud_xyz_to_xyzrgb.md
- jsk_pcl_ros_utils/CMakeLists.txt
- jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/pointcloud_xyz_to_xyzrgb.h
- jsk_pcl_ros_utils/jsk_pcl_nodelets.xml
- jsk_pcl_ros_utils/sample/config/sample_pointcloud_xyz_to_xyzrgb.rviz
- jsk_pcl_ros_utils/sample/sample_pointcloud_xyz_to_xyzrgb.launch
- jsk_pcl_ros_utils/scripts/install_sample_data.py
- jsk_pcl_ros_utils/src/pointcloud_xyz_to_xyzrgb_nodelet.cpp
- jsk_pcl_ros_utils/test/pointcloud_xyz_to_xyzrgb.test
For https://github.com/jsk-ros-pkg/jsk_recognition/issues/1966
`ClusterPointIndicesDecomposer` requires `PointXYZRGB` to visualize, but cloud from lasor does not have rgb.
> Add PointCloudXYZToXYZRGB utility nodelet

- checkerboard_detector/src/checkerboard_detector.cpp
do not merge yet.
I will check parameters tomorrow with other calibrated cameras (I checked only on my astra camera) and 5X4 checkerboard.
any comments are welcome.
With this PR, we can warn dual-rectification of image indicated in #1935 #1937.
However, the error often occurs because of moving cameras or checker board is not in planer place.
> [WIP] [checkerboard_detector] warn if error is big

- jsk_perception/CMakeLists.txt
Currently the node `bing` seems not used/changed frequently
because it requires opencv3, and I have no time to analyze the
unstable test on Travis/Jenkins. That's why I'm disabling it.
For #1962
> Disable bing test on Travis

- jsk_perception/package.xml
Because python-gdown-pip is installed via jsk_data
> No longer required python-gdown dependency

- jsk_perception/src/consensus_tracking.cpp
```
22:30:02
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/src/consensus_tracking.cpp:
In member function 'void
jsk_perception::ConsensusTracking::setInitialWindow(const ConstPtr&,
const ConstPtr&)':
22:30:02
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/src/consensus_tracking.cpp:97:185:
warning: format '%d' expects argument of type 'int', but argument 8 has
type 'double' [-Wformat=]
22:30:02      ROS_INFO("A window is initialized. top_left: (%d, %d),
bottom_right: (%d, %d)",
22:30:02
^
22:30:02
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/src/consensus_tracking.cpp:97:185:
warning: format '%d' expects argument of type 'int', but argument 9 has
type 'double' [-Wformat=]
22:30:02 …
```
> Fix cpp format of consensus_tracking

- jsk_pcl_ros/src/edge_depth_refinement_nodelet.cpp
- jsk_recognition_utils/include/jsk_recognition_utils/geo/segment.h
- jsk_recognition_utils/src/geo/segment.cpp
This is very complicated bug...
Before PR, the distance of edges are calculated from the distance of nearest points in lines (line has no limitation of length). In that case, two nearly-parallel but little-tilting lines are sometimes calculated to be very near even if they are not.
This PR considers the length of edges, so this bug is fixed.
- Before PR
- After PR
> Fix edge distance calculation in duplication check of edge depth refinement

- jsk_pcl_ros_utils/scripts/evaluate_voxel_segmentation_by_gt_box.py
Problem
-------
When we set `~marker_ns:=2`, it is interpreted as int, but namespace must be string.
That's why I need this change.
> Cast to string to get correctly ns from rosparam in voxel evaluation

- jsk_pcl_ros_utils/CMakeLists.txt
This is annoying, and does not show helpful information.
```
[jsk_pcl_ros_utils] util: src/bounding_box_array_to_bounding_box_nodelet.cpp
[jsk_pcl_ros_utils] util: src/normal_flip_to_frame_nodelet.cpp
[jsk_pcl_ros_utils] util: src/centroid_publisher_nodelet.cpp
[jsk_pcl_ros_utils] util: src/cloud_on_plane_nodelet.cpp
[jsk_pcl_ros_utils] util: src/tf_transform_cloud_nodelet.cpp
[jsk_pcl_ros_utils] util: src/tf_transform_bounding_box_nodelet.cpp
[jsk_pcl_ros_utils] util: src/tf_transform_bounding_box_array_nodelet.cpp
[jsk_pcl_ros_utils] util: src/normal_concatenater_nodelet.cpp
[jsk_pcl_ros_utils] util: src/polygon_array_distance_likelihood_nodelet.cpp
[jsk_pcl_ros_utils] util: src/polygon_array_area_likelihood_nodelet.cpp
[jsk_pcl_ros_utils] util: …
```
> Remove unnecessary cmake messages

- jsk_pcl_ros/src/geometric_consistency_grouping_nodelet.cpp
Error reported at #2022
```
/tmp/binarydeb/ros-kinetic-jsk-pcl-ros-1.1.0/src/geometric_consistency_grouping_nodelet.cpp:172:182:   required from here
/usr/include/flann/util/serialization.h:18:9: error: ‘class std::unordered_map<unsigned int, std::vector<unsigned int> >’ has no member named ‘serialize’
type.serialize(ar);
```
could be fixe by this issue, see https://github.com/mariusmuja/flann/issues/214 for detail
close #2022
> incldue flann before any opencv includes, fix #2022

- jsk_pcl_ros/scripts/check_depth_error/depth_error_calibration.py
Forget to change source code at https://github.com/jsk-ros-pkg/jsk_recognition/pull/1917 ?
```
Hi,
I am trying to calibrate the depth on a primensense 1.09, following the
steps described here:
https://jsk-recognition.readthedocs.io/en/latest/jsk_pcl_ros/calibration.html.
However when I run the command rosrun jsk_pcl_ros
depth_error_calibration.py --model quadratic-uv-quadratic-abs I get an
error (bellow) and are not able to proceed.
Can you let me know if you have any idea on what is the issue?
roliveira@ThinkPad-T440p:/opt/ros/indigo/share/jsk_pcl_ros/launch$
rosrun jsk_pcl_ros depth_error_calibration.py --model
quadratic-uv-quadratic-abs
File
"/opt/ros/indigo/lib/jsk_pcl_ros/check_depth_error/depth_error_calibration.py",
line 16, in <module>
from …
```
> forget to convert form jsk_pcl_ros to jsk_recognition_msgs

- jsk_recognition_utils/include/jsk_recognition_utils/geo/polygon.h
- jsk_recognition_utils/src/geo/polygon.cpp
part of #2027
distance between polygon and point.
segment version is here:
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_recognition_utils/src/geo/segment.cpp#L76-L87
I use this in https://github.com/mmurooka/jsk_recognition/blob/26d2ab230c8fd27d7e455f8be993641e45e6bda4/jsk_pcl_ros/include/jsk_pcl_ros/pcl/transformation_estimation_point_to_element.h#L134 .
> [jsk_recognition_utils/geo/Polygon] add distance method.

- doc/jsk_pcl_ros_utils/nodes/centroid_publisher.md
- jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/centroid_publisher.h
- jsk_pcl_ros_utils/src/centroid_publisher_nodelet.cpp
This pull request includes a feature to publish centroid pose of polygon in array.
- rename variable `sub_input_` to `sub_cloud_`
- add `sub_polygons_` to subscribe `PolygonArray`
- publish pose and tf as `frameXX` (XX is incremental number)
- Cleanup docs
- Update docs for support polygon array input
> [jsk_pcl_ros_utils][centroid_publisher_nodelet] support polygon array

- jsk_pcl_ros_utils/CMakeLists.txt
To suppress warning:
```bash
Starting  >>> jsk_pcl_ros_utils                                                                                 
________________________________________________________________________________________________________________
Warnings   << jsk_pcl_ros_utils:check /home/furushchev/ros/indigo/logs/jsk_pcl_ros_utils/build.check.017.log    
CMake Warning at /home/furushchev/ros/indigo/build/jsk_pcl_ros_utils/cmake/jsk_pcl_ros_utils-genmsg.cmake:3 (message):
Invoking generate_messages() without having added any message or service
file before.
You should either add add_message_files() and/or add_service_files() calls
or remove the invocation of generate_messages().
Call Stack (most recent call first):
/opt/ros/indigo/share/genmsg/cmake/genmsg-extras.cmake:307 …
```
> [jsk_pcl_ros_utils][CMakeLists.txt] Suppress warning on build

- jsk_perception/node_scripts/fcn_object_segmentation.py
- modified: jsk_perception/node_scripts/fcn_object_segmentation.py
```bash
% rp hz /fcn_object_segmentation/output -w 30 --wall-time
subscribed to [/fcn_object_segmentation/output]
average rate: 5.166
min: 0.189s max: 0.201s std dev: 0.00433s window: 5
average rate: 5.172
min: 0.183s max: 0.201s std dev: 0.00550s window: 10
average rate: 5.120
min: 0.183s max: 0.208s std dev: 0.00661s window: 15
average rate: 5.113
min: 0.180s max: 0.210s std dev: 0.00752s window: 20
average rate: 5.094
min: 0.180s max: 0.213s std dev: 0.00776s window: 25
average rate: 5.067
min: 0.180s max: 0.216s std dev: 0.00895s window: 30
average rate: 5.070
min: 0.180s max: 0.216s std dev: 0.00915s window: 30
average rate: 5.069
min: 0.180s max: 0.216s std dev: 0.00896s window: 30
^Caverage rate: 5.059
min: 0.180s …
```
> Enhance fcn_object_segmentation.py with PyTorch backend

- jsk_pcl_ros/cfg/EuclideanClustering.cfg
maximum cluster size 100000 is too small for large image.
For finding large objects from 2K image like ZED, we need more large max_size parameter.
> enlarge euclidean clustering max cluster size

- doc/jsk_perception/nodes/consensus_tracking.rst
- jsk_perception/include/jsk_perception/consensus_tracking.h
- jsk_perception/src/consensus_tracking.cpp
Modified:
- doc/jsk_perception/nodes/consensus_tracking.rst
- jsk_perception/include/jsk_perception/consensus_tracking.h
- jsk_perception/src/consensus_tracking.cpp
> Add ~approximate_sync param to ConsensusTracking

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/package.xml
Following fix in https://github.com/jsk-ros-pkg/jsk_recognition/issues/2087
> Cleanup octomap dependencies of jsk_pcl_ros

- jsk_pcl_ros/scripts/extract_top_polygon_likelihood.py
- jsk_pcl_ros/src/ppf_registration_nodelet.cpp
- jsk_perception/node_scripts/binpack_rect_array.py
- jsk_perception/node_scripts/bof_histogram_extractor.py
- jsk_perception/node_scripts/fast_rcnn.py
- jsk_perception/node_scripts/fcn_object_segmentation.py
- jsk_perception/node_scripts/image_publisher.py
- jsk_perception/node_scripts/label_image_decomposer.py
- jsk_perception/node_scripts/mask_image_to_label.py
- jsk_perception/node_scripts/solidity_rag_merge.py
- jsk_perception/node_scripts/split_fore_background.py
- jsk_perception/node_scripts/unwrap_histogram_with_range_array.py
Because it is deprecated by https://github.com/jsk-ros-pkg/jsk_common/issues/1461.
> Stop using deprecated logging func in jsk_topic_tools

- jsk_pcl_ros/src/rearrange_bounding_box_nodelet.cpp
To fix
```
WARNING: '/home/wkentaro/Projects/label_octomap/src/jsk-ros-pkg/jsk_recognition/jsk_pcl_ros/sample/data/sample_add_color_from_image_20170319.bag' exists
/home/wkentaro/Projects/label_octomap/src/jsk-ros-pkg/jsk_recognition/jsk_pcl_ros/src/rearrange_bounding_box_nodelet.cpp: In member function ‘virtual void jsk_pcl_ros::RearrangeBoundingBox::onInit()’:
/home/wkentaro/Projects/label_octomap/src/jsk-ros-pkg/jsk_recognition/jsk_pcl_ros/src/rearrange_bounding_box_nodelet.cpp:51:57: warning: ‘tf2::Quaternion::Quaternion(const tf2Scalar&, const tf2Scalar&, const tf2Scalar&)’ is deprecated (declared at /opt/ros/indigo/include/tf2/LinearMath/Quaternion.h:50) [-Wdeprecated-declarations]
q_ = tf2::Quaternion(rotate_y_, rotate_x_, rotate_z_);
^ …
```
> Fix deprecation warning on RearrangeBoundingBox

- jsk_pcl_ros/cfg/ColorBasedRegionGrowingSegmentation.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/color_based_region_growing_segmentation.h
- jsk_pcl_ros/src/color_based_region_growing_segmentation_nodelet.cpp
Fix typo in ColorBasedRegionGrowingSegmentation's parameters. #2096 
thresho**u**ld  → threshold
Could not test because was having some troubles trying to build from source, but I believe it should be fine.
> Fix typo in ColorBasedRegionGrowingSegmentation

- jsk_recognition_utils/CMakeLists.txt
Fix #2117 
I have not much knowledge about debian release, but `node_scripts` `install` section is missing, which seems the cause of the issue.
If I'm misunderstanding, please let me know.
> [jsk_recognition_utils] install node_scripts dir

- doc/jsk_perception/nodes/rect_to_mask_image.md
I think input message type is ```PointStamped```, not ```Polygon``` based on https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/src/rect_to_mask_image.cpp#L67
If there is any problem (actually I have a lot of mistakes...), please let me know.
> [jsk_perception/doc] modified input type of rect_to_mask_image

- jsk_pcl_ros/include/jsk_pcl_ros/octomap_server_contact.h
- jsk_pcl_ros/src/octomap_server_contact_nodelet.cpp
Following output is printed from octomap in every update.
https://github.com/OctoMap/octomap/blob/devel/octomap/include/octomap/OccupancyOcTreeBase.hxx#L947
define NDEBUG to suppress octomap output.
https://github.com/OctoMap/octomap/blob/cc7cddc6e5e01c2fdb1b142124a9890b949a0360/octomap/include/octomap/octomap_types.h#L62
> [jsk_pcl_ros/OctomapServerContact] Supress octomap debug message

- jsk_pcl_ros_utils/src/polygon_array_transformer_nodelet.cpp
- jsk_pcl_ros_utils/src/static_polygon_array_publisher_nodelet.cpp
When I launch 
```StaticPolygonArrayPublisher``` (node name is set to ```[/people_detection/footstep_polygon_publisher```) 
and ```PolygonArrayTransformer``` (node name is set to ```[/people_detection/polygon_array_transformer```)
of jsk_pcl_ros_utils, the warning below occurred.
```
[ WARN] [1498035213.941695751]: [/people_detection/footstep_polygon_publisher] onInitPostProcess is not yet called.
[ WARN] [1498035213.942671862]: '/people_detection/footstep_polygon_publisher' subscribes topics only with child subscribers.
[ WARN] [1498035214.353049047]: [/people_detection/polygon_array_transformer] onInitPostProcess is not yet called.
[ WARN] [1498035214.353923307]: '/people_detection/polygon_array_transformer' subscribes topics only with child subscribers.
```
If there is any comments, …
> [jsk_pcl_ros_utils/src] add onInitPostProcess for StaticPolygonArrayPublisher, PolygonArrayTransformer

- jsk_perception/node_scripts/draw_rect_array.py
When polygon_msg like below (list is empty) is published, 
```
header: 
seq: 304
stamp: 
secs: 1497531876
nsecs: 174966328
frame_id: head_rgbd_sensor_rgb_frame
polygon: 
points: []
```
this kind of error occurs.
```
File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, 
in _invoke_callback
cb(msg)
File "/opt/ros/indigo/lib/python2.7/dist-packages/message_filters/__init__.py"
, line 74, in callback
self.signalMessage(msg)
File "/opt/ros/indigo/lib/python2.7/dist-packages/message_filters/__init__.py"
, line 56, in signalMessage
cb(*(msg + args))
File "/opt/ros/indigo/lib/python2.7/dist-packages/message_filters/__init__.py"
, line 199, in add
self.signalMessage(*msgs)
File "/opt/ros/indigo/lib/python2.7/dist-packages/message_filters/_ …
```
> [jsk_perception/draw_rect_array.py] check polygon_msg list size

- doc/jsk_pcl_ros_utils/nodes/label_to_cluster_point_indices.rst
- jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/label_to_cluster_point_indices.h
- jsk_pcl_ros_utils/src/label_to_cluster_point_indices_nodelet.cpp
We'd like to fill index of cluster indices with bg_label to keep index == label_value.
> Capability of specifying background label for LabelToClusterPointIndices

- doc/jsk_pcl_ros/nodes/color_histogram.md
- doc/jsk_pcl_ros/nodes/color_histogram_classifier.md
- doc/jsk_pcl_ros/nodes/color_histogram_filter.md
- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/cfg/ColorHistogram.cfg
- jsk_pcl_ros/cfg/ColorHistogramClassifier.cfg
- jsk_pcl_ros/cfg/ColorHistogramFilter.cfg
- jsk_pcl_ros/cfg/ColorHistogramVisualizer.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/color_histogram.h
- jsk_pcl_ros/include/jsk_pcl_ros/color_histogram_classifier.h
- jsk_pcl_ros/include/jsk_pcl_ros/color_histogram_filter.h
- jsk_pcl_ros/include/jsk_pcl_ros/pcl/point_types_conversion.h
- jsk_pcl_ros/plugins/nodelet/libjsk_pcl_ros.xml
- jsk_pcl_ros/sample/sample_color_histogram.launch
- jsk_pcl_ros/scripts/color_histogram_visualizer.py
- jsk_pcl_ros/src/color_histogram_classifier_nodelet.cpp
- jsk_pcl_ros/src/color_histogram_filter_nodelet.cpp
- jsk_pcl_ros/src/color_histogram_matcher_nodelet.cpp
- jsk_pcl_ros/src/color_histogram_nodelet.cpp
- jsk_pcl_ros/test/color_histogram.test
- jsk_recognition_utils/include/jsk_recognition_utils/pcl/color_histogram.h
related https://github.com/jsk-ros-pkg/jsk_recognition/pull/2094
Below is image that iemon green tea is filtered.
> [jsk_pcl_ros_utils] Add nodelet for computing & comparing color histogram

- doc/jsk_perception/nodes/apply_context_to_label_probability.rst
- jsk_perception/node_scripts/apply_context_to_label_probability
- jsk_recognition_msgs/CMakeLists.txt
- jsk_recognition_msgs/msg/Label.msg
- jsk_recognition_msgs/msg/LabelArray.msg
To change candidates dynamically in multi-object picking challenge https://github.com/start-jsk/jsk_apc/pull/2207.
- add `Label` and `LabelArray` msg
- update candidates by topic
- set param `use_topic` `true` to enable this feature
- update doc
**Updated by @wkentaro**
> [jsk_perception] apply candidates node supports topic update

- jsk_pcl_ros/sample/sample_cluster_point_indices_decomposer.launch
- jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp
The purple bounding box does not have input planes, and this is useful for bounding box-based grasp planning.
**without pca**
**with pca**
> Support PCA even without input planes but with only ground frame

- doc/jsk_pcl_ros_utils/nodes/label_to_cluster_point_indices.rst
- jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/label_to_cluster_point_indices.h
- jsk_pcl_ros_utils/src/label_to_cluster_point_indices_nodelet.cpp
add param `~ignore_labels` in `label_to_cluster_point_indices`
indices of ignored label are replaced by `[]`
> [jsk_pcl_ros_utils] add ignore_labels in label_to_cluster_point_indices

- jsk_recognition_utils/setup.py
This is for debian package release.
Currently, `jsk_recognition_utils.chainermodels` cannot be found with debian package
> [jsk_recognition_utils] install chainermodels dir in setup.py

- docker/ros/indigo/pcl1.8/Dockerfile
To avoid pre-installed packages unexpectedly.
> Derive from ros:indigo-ros-core in ros-indigo-pcl1.8

- jsk_pcl_ros/src/fuse_images.cpp
Currently it can be passed 16UC1 depth and 32FC1 one to be fused, but it is not possible because they have different metrics: mm for 16UC1 and m for 32FC1.
Found at https://github.com/start-jsk/jsk_apc/pull/2244
> Check encoding of input topics in FuseImages

- jsk_perception/node_scripts/label_image_classifier.py
if `label_img` only have several elements like `[0, 37, 37, 0, ....]` and `ignore_labels` are set as `[0, 41]`, it occurs `out of index` error.
I pad zeros to avoid this error.
> fix bug in label_image_classifier

- doc/jsk_perception/nodes/apply_context_to_label_probability.rst
- jsk_perception/node_scripts/apply_context_to_label_probability
add `bg_label` for masked images.
if `candidates` does not contain `bg_label`, sum of masked regions would be `0`, and probability would be `nan`.
This can happen, for example, weight_candidates_publisher do not publish `__background__` as candidates.
> add bg_label in apply_context_to_label_probability

- doc/jsk_pcl_ros/nodes/cluster_point_indices_decomposer.md
- jsk_pcl_ros/include/jsk_pcl_ros/cluster_point_indices_decomposer.h
- jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp
- jsk_pcl_ros/test/test_cluster_point_indices_decomposer.test
We used this in the Grasped Region Classification at ARC2017 pick/stow task.
> Publish sorted cluster point indices in ClusterPointIndicesDecomposer

- jsk_perception/node_scripts/apply_context_to_label_probability
because it can be tuple, which causes error
> make sure candidates is list

- doc/jsk_pcl_ros/nodes/multi_plane_extraction.md
- jsk_pcl_ros/include/jsk_pcl_ros/multi_plane_extraction.h
- jsk_pcl_ros/src/multi_plane_extraction_nodelet.cpp
Addresses #2186 
If `~use_sensor_frame` is false, the z-axis of plane may be flipped on each detection and coefficients topic is never used.
I added a new option `~use_coefficients` that determines z-axis of each planes.
**NOTE** Visualization of normal arrow in rviz is not valid. (To see actual z normal axis, we must consider both polygon and coefficients)
> jsk_pcl_ros: multi_plane_extraction: add option use_coefficients

- doc/jsk_pcl_ros_utils/nodes/polygon_flipper.md
- jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/polygon_flipper.h
- jsk_pcl_ros_utils/src/polygon_flipper_nodelet.cpp
> [jsk_pcl_ros_utils] polygon_flipper: add option '~use_indices'

- doc/jsk_perception/nodes/people_pose_estimation_2d.rst
- jsk_perception/node_scripts/people_pose_estimation_2d.py
This pull request disables synchronization of camera info with images and let the node use it only once instead.
Fixes #2165
> jsk_perception: people_pose_estimation_2d.py: unsynchronize camera info

- jsk_pcl_ros/CMakeLists.txt
In my envorionment, there is a build error that it cannot find `moveit_ros_perception` header files.
cc. @mmurooka
> find moveit_ros_perception package as a catkin MODULES

- jsk_pcl_ros/src/tilt_laser_listener_nodelet.cpp
- resized_image_transport/src/image_processing_nodelet.cpp
Problem:
When a `jsk_topic_tools/standalone_complexed_nodelet` loaded `jsk_pcl/tilt_laser_listener` and `resized_image_transport/ImageResizer` in the situation where input point cloud and image topics are already published, it died with following error message.
```cpp
standalone_complexed_nodelet: /usr/include/boost/smart_ptr/shared_ptr.hpp:653: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = jsk_topic_tools::VitalChecker; typename boost::detail::sp_member_access<T>::type = jsk_topic_tools::VitalChecker*]: Assertion `px != 0' failed.
```
Proposed solution:
This error seems to be caused by initialization order of the vital checker (the pointer for a vital checker is referred in a callback function before it is initialized).
This PR …
> Fix uninitialized pointer error in some recognition nodelets

- doc/jsk_pcl_ros_utils/nodes/pointcloud_to_mask_image.rst
- jsk_pcl_ros_utils/CMakeLists.txt
- jsk_pcl_ros_utils/cfg/PointCloudToMaskImage.cfg
- jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/pointcloud_to_mask_image.h
- jsk_pcl_ros_utils/sample/config/sample_pointcloud_to_mask_image.perspective
- jsk_pcl_ros_utils/sample/sample_pointcloud_to_mask_image.launch
- jsk_pcl_ros_utils/src/pointcloud_to_mask_image_nodelet.cpp
- jsk_pcl_ros_utils/test/pointcloud_to_mask_image.test
This pull request adds a nodelet for creating mask image in the range of specified depth from sensor.
> jsk_pcl_ros_utils: add depth image for input to pointcloud_to_mask_image

- jsk_pcl_ros/cfg/MultiPlaneExtraction.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/multi_plane_extraction.h
- jsk_pcl_ros/src/multi_plane_extraction_nodelet.cpp
This closes #2202
- Added correct parameter `magnify` that synchronizes with `maginify`
- Add deprecation warning for `maginify`
> jsk_pcl_ros/multi_plane_extraction: fix typo 'maginify'

- doc/jsk_perception/nodes/face_pose_estimation.rst
Node name is not correct in the following doc.
http://jsk-docs.readthedocs.io/en/latest/jsk_recognition/doc/jsk_perception/nodes/face_pose_estimation.html
> [doc] fix node script name of face_pose_estimation.py document.

- docker/ros/indigo/pcl1.8/Dockerfile
pip install dlib takes 15 minutes, so it's better to include in docker file
> install dlib in ros-indigo-pcl1.8

- jsk_libfreenect2/src/driver_nodelet.cpp
These macros, deprecated for now 8 years, will be removed in the next ROS release (ROS Melodic)
This change will allow the code to keep compiling on future ROS versions
> update to use non deprecated pluginlib macro

- jsk_perception/node_scripts/label_image_decomposer.py
Currently, `cvtColor` raise error when `ndim=2` image (gray scale) is passed.
> [jsk_perception/label_image_decomposer.py] check img.ndim for gray scale image

- jsk_pcl_ros_utils/CMakeLists.txt
```
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:166 (message):
catkin_package() DEPENDS on 'pcl' but neither 'pcl_INCLUDE_DIRS' nor
'pcl_LIBRARIES' is defined.
Call Stack (most recent call first):
/opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
CMakeLists.txt:220 (catkin_package)
CMake Warning (dev) at CMakeLists.txt:214 (add_dependencies):
Policy CMP0046 is not set: Error on non-existent dependency in
add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
Use the cmake_policy command to set the policy and suppress this warning.
The dependency target "jsk_pcl_ros_utils_gencpp" of target
"jsk_pcl_ros_utils" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
> Fix warnings for jsk_pcl_ros_utils

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros/cfg/PointcloudScreenpoint.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/pointcloud_screenpoint.h
- jsk_pcl_ros/src/pointcloud_screenpoint_nodelet.cpp
- jsk_recognition_msgs/srv/TransformScreenpoint.srv
rebased version of #2268
```
Rewrite version of pointcloud_screenpoint using connection_based_nodelet.
This PR includes:
- Applied connection_based_nodelet that replaces the existing nodelet which always subscribe pointcloud that makes serious overhead
- Support dynamic reconfigure for changing parameters dynamically
```
> jsk_pcl_ros: support lazy mode for pointcloud_screenpoint nodelet

- imagesift/CMakeLists.txt
- imagesift/package.xml
To suppress following warnings:
**With catkin build**
```
Warnings   << imagesift:cmake /root/catkin_ws/logs/imagesift/build.cmake.000.log
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:166 (message):
catkin_package() DEPENDS on 'libsiftfast' but neither
'libsiftfast_INCLUDE_DIRS' nor 'libsiftfast_LIBRARIES' is defined.
Call Stack (most recent call first):
/opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
CMakeLists.txt:16 (catkin_package)
CMake Warning (dev) at CMakeLists.txt:71 (add_dependencies):
Policy CMP0046 is not set: Error on non-existent dependency in
add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
Use the cmake_policy command to set the policy and suppress this warning.
The dependency target …
```
> Refactor CMakeLists.txt and package.xml of jsk_perception

- jsk_perception/launch/fast_rcnn.launch
- jsk_perception/node_scripts/fast_rcnn.py
- jsk_perception/sample/sample_fast_rcnn.launch
- jsk_recognition_utils/python/jsk_recognition_utils/chainermodels/vgg16_fast_rcnn.py
- jsk_recognition_utils/python/jsk_recognition_utils/chainermodels/vgg_cnn_m_1024.py
When executing `roslaunch jsk_perception sample_fast_rcnn.launch`, I encountered the following error messages.
This PR will fix this problem.
```
[ERROR] [WallTime: 1524824331.872704] bad callback: <bound method Subscriber.callback of <message_filters.Subscriber object at 0x7f0a3a6bb6d0>>
File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
cb(msg)
File "/opt/ros/indigo/lib/python2.7/dist-packages/message_filters/__init__.py", line 74, in callback
self.signalMessage(msg)
File "/opt/ros/indigo/lib/python2.7/dist-packages/message_filters/__init__.py", line 56, in signalMessage
cb(*(msg + args))
File "/opt/ros/indigo/lib/python2.7/dist-packages/message_filters/__init__.py", line 199, in add …
```
> Fix for AssertionError in fast_rcnn.py

- imagesift/CMakeLists.txt
- imagesift/package.xml
- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros_utils/CMakeLists.txt
- jsk_perception/CMakeLists.txt
- resized_image_transport/CMakeLists.txt
- resized_image_transport/package.xml
fix regression by  https://github.com/jsk-ros-pkg/jsk_common/pull/1586
> fix for jsk-ros-pkg/jsk_common/pull/1586

- resized_image_transport/src/image_processing_nodelet.cpp
In this [PR](https://github.com/jsk-ros-pkg/jsk_common/pull/1585),
diagnostics nodelet's warn level are changable by user.
image_processing_nodelet's warn level is always ERROR.
Applying this PR, we can change the warn level by ```use_warn``` option.
> [resized_image_transport] Changed diagnostic error level

- jsk_pcl_ros/launch/openni2_remote.launch
From following PRs, user can change ImageResizer's diagnostics level.
This PR add use_warn option to openni2_remote.launch.
https://github.com/jsk-ros-pkg/jsk_common/pull/1585
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2301
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2312
> [jsk_pcl_ros/openni2_remote.launch] Add use_warn option

- jsk_pcl_ros/include/jsk_pcl_ros/depth_calibration.h
- jsk_pcl_ros/include/jsk_pcl_ros/line_segment_collector.h
- jsk_pcl_ros/include/jsk_pcl_ros/line_segment_detector.h
- jsk_pcl_ros/src/depth_calibration_nodelet.cpp
- jsk_pcl_ros/src/line_segment_collector_nodelet.cpp
- jsk_pcl_ros/src/line_segment_detector_nodelet.cpp
In jsk_pcl_ros, depth_calibration_nodelet, line_segment_detector_nodelet and line_segment_collector_nodelet are not updating diagnostics. 
Before this PR, they output error of diagnostics with "No message was set" message and
we can not change the error level.
Like this
After this PR, we can change the error level.
> [jsk_pcl_ros] Delete subclass's updateDiagnostic method

- jsk_pcl_ros/test/color_histogram.test
- jsk_pcl_ros/test/test_pointcloud_screenpoint.test
- jsk_pcl_ros_utils/CMakeLists.txt
- jsk_perception/sample/sample_bof_object_recognition.launch
- jsk_perception/scripts/install_trained_data.py
Related to #2336 
In kinetic, ```python-sklearn```'s version is 0.20.0.
I retrained bof data and upload it to google drive.
And current travis test for kinetic failed. So modified test for ```color_histogram``` and ```pointcloud_screenpoint``` and disabled ```pointcloud_to_pcd.test```(this is TODO).
close #2336
> [jsk_perception] Retrain bof data for sklearn==0.2.0 version and modified jsk_pcl_ros/utils's test for kinetic travis

- jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp
Related to #2325 
This PR modified ```publishNegativeIndices``` function to make it faster than current implementation
and add publish ```~/output/negative_indices``` when subscriber connected.
> [jsk_pcl_ros/cluster_point_indices_decomposer] Modified publishNegativeIndices to make it fast

- jsk_pcl_ros/package.xml
There is a dependency of checkerboard detector.
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/launch/depth_error.launch#L21
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/launch/pr2_pointcloud_error_visualization.launch#L10
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/launch/capture/capture_multisense.launch#L3
> [jsk_pcl_ros/package.xml] Add checkerborad_detecotr's dependency

- doc/jsk_pcl_ros/nodes/cluster_point_indices_decomposer.md
Default value of force_to_flip_z_axis in `ClusterPointIndicesDecomposer` is true.
https://github.com/jsk-ros-pkg/jsk_recognition/blob/1.2.5/jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp#L101
> Fix default of force_to_flip_z_axis in doc

- doc/jsk_perception/nodes/image_publisher.md
- jsk_perception/node_scripts/image_publisher.py
- jsk_perception/sample/sample_image_publisher.launch
I added a ```fov``` parameter (```fovx``` and ```fovy```) to  ```image_publisher.py``` .
In current ```image_publisher.py```publishes ```sensor_msgs/CameraInfo``` and its intrinsic parameters are zero values.
With this patch, we can calculate intrinsic parameter from ```fov```.
Below picture is rviz's image visualized by jsk_rviz_plugins' camera info.
> [jsk_perception/image_publisher.py] Add fov parameter for publishing valid camera info parameters

- jsk_perception/sample/sample_mask_rcnn_instance_segmentation.launch
```fps```  is not in ``image_publisher.py``'s rosparam.
> [jsk_perception/sample_mask_rcnn] Fixed typo. fps -> rate

- jsk_pcl_ros/src/multi_plane_extraction_nodelet.cpp
Related to following issue and PR.
https://github.com/jsk-ros-pkg/jsk_recognition/issues/2186
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2191
Without applying this patch, 
If ~use_sensor_frame and ~use_coefficients are false,  the z-axis of plane may be flipped on each detection. (reported a following comment https://github.com/jsk-ros-pkg/jsk_recognition/pull/2191#issuecomment-321966823)
This flipping is caused by no initialization of viewpoint. 
viewpoint was used for chaning viewpoint of  ```pcl::ExtractPolygonalPrismData<pcl::PointXYZRGB>```.
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/src/multi_plane_extraction_nodelet.cpp#L310
pcl::ExtractPolygonalPrismData's default viewpoint is [0, 0, 0]. So this PR fixes the default behavior to match …
> [jsk_pcl_ros/multi_plane_extraction] Initialize viewpoint by zeros to avoid flip of surface normal direction

- jsk_perception/node_scripts/people_pose_estimation_2d.py
When a large image is input, we cannot allocate openpose's neural network  on GPU memory.
So I added an option to resize for openpose nodelet.
> [jsk_perception/openpose] Add resize image

- doc/jsk_pcl_ros/nodes/attention_clipper.md
There was a lack of documentation about attention_clipper's publishing topics.
I added the documentation.
> [attention_clipper] add documentation about publishing topics

- jsk_pcl_ros/CMakeLists.txt
- jsk_pcl_ros_utils/CMakeLists.txt
Enable ccache if it's installed.
> [jsk_pcl_ros, jsk_pcl_ros_utils] Use ccache if installed to make it fast to generate object file

- jsk_pcl_ros/src/normal_estimation_omp_nodelet.cpp
In `normal_estimation_omp_nodelet.launch`,  the output pointcloud doesn't take over the rgb data of the input pointcloud. This pull request will solve this issue.
I tested the result with `sample_door_handle_detector.bag` and checked if it works correctly.
Input pointcloud
The left is the previous output, and the right is the one with this pull request.
> add line to preserve rgb data of pointcloud

- doc/jsk_perception/nodes/fcn_object_segmentation.rst
- doc/jsk_perception/training_scripts/train_fcn.md
- jsk_perception/node_scripts/fcn_object_segmentation.py
- jsk_perception/scripts/train_fcn.py
Network weight of FCN8s and FCN8sAtOnce are the same shape, but some parameters are different and should be distinguished.
The accuracy becomes very low if you use wrong model.
- correct
- wrong
> [jsk_perception] Support fcn8s_atonce model in fcn_object_segmentation.py

- jsk_recognition_utils/python/jsk_recognition_utils/CMakeLists.txt
This PR allows users to pass `Numpy_INCLUDIR_DIRS` externally, for example for cross compiling to a different target platform.
> Support passing Numpy_INCLUDE_DIRS externally

- jsk_recognition_utils/package.xml
`import chainer` is declared in some scripts (e.g. jsk_recognition_utils/python/jsk_recognition_utils/chainermodels/alexnet.py), but chainer was not installed even after `rosdep install` successfully finished.
This PR will resolve dependency.
> [jsk_recognition_utils] Resolve dependency for chainer

- jsk_pcl_ros/euslisp/bounding-box-to-cube.l
- jsk_pcl_ros/euslisp/display-bounding-box-array.l
This Pull Request is re-submission of https://github.com/jsk-ros-pkg/jsk_roseus/pull/584
I added a method to convert jsk_recognition_msgs/BoundingBox into cube in euslisp.
BoundingBox in Rviz
BoundingBox in euslisp
> Add method to convert jsk_recognition_msgs/BoundingBox to cube in euslisp

- imagesift/CMakeLists.txt
use https://stackoverflow.com/questions/28939652/how-to-detect-sse-sse2-avx-avx2-avx-512-avx-128-fma-kcvi-availability-at-compile to check if gcc supports sse
```
23:36:54 ccache /usr/lib/ccache/aarch64-linux-gnu-g++   -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\"imagesift\" -I/tmp/binarydeb/ros-kinetic-imagesift-1.2.7/include -I/opt/ros/kinetic/include -I/opt/ros/kinetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -isystem /opt/ros/kinetic/include/opencv-3.3.1-dev -isystem /opt/ros/kinetic/include/opencv-3.3.1-dev/opencv -I/usr/include/eigen3 -I/usr/include/pcl-1.7 -I/usr/include/ni -I/usr/include/vtk-6.2 -I/usr/include/jsoncpp -I/usr/include/libxml2 -I/usr/include/aarch64-linux-gnu -I/usr/include/freetype2 -I/usr/include/python2.7 …
```
> fix arm build regressions, closes #2396

- jsk_recognition_utils/CMakeLists.txt
will fix http://build.ros.org/job/Mbin_ds_dS64__jsk_recognition_utils__debian_stretch_amd64__binary/7/console
> add QT_LIBRARIES Qt5::Widgets to fix 'cannot find -lQt5::Widgets' error on debian stretch

- jsk_pcl_ros_utils/CMakeLists.txt
Fix #2339 
I could not reproduce the test failure described in https://github.com/jsk-ros-pkg/jsk_recognition/issues/2339#issue-366148593 on my environment (Ubuntu16.04 + kinetic + latest master branch of jsk_recognition (commit: f3ed340)).
So I re-enabled pointcloud_to_pcd.test to check why the failure occured on travis build.
If pointcloud_to_pcd.test does not fail, please merge this PR.
> Re-enable pointcloud_to_pcd.test

- jsk_pcl_ros/include/jsk_pcl_ros/pointcloud_moveit_filter.h
fix http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/bionic-travis-jsk-ros-pkg-jsk-recognition-melodic-deb-true-true/90/console
```
20:53:17    ^~~~~~~~~~~~~~~
20:53:17 /usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: note: declared here
20:53:17 In file included from /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros/src/pointcloud_moveit_filter.cpp:206:0:
20:53:17 /opt/ros/melodic/include/class_loader/class_loader.h:36:2: warning: #warning Including header <class_loader/class_loader.h> is deprecated, include <class_loader/class_loader.hpp> instead. [-Wcpp]
20:53:17  #warning Including header <class_loader/class_loader.h> is deprecated, \
20:53:17   ^~~~~~~
20:53:17 In file included from /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros/src/point …
```
> use (MOVEIT_VERSION_MAJOR == 0 and MOVEIT_VERSION_MINOR < 6), since moveit is upgraded to 1.0

- jsk_perception/node_scripts/face_pose_estimation.py
- jsk_perception/node_scripts/mask_rcnn_instance_segmentation.py
- jsk_perception/node_scripts/people_pose_estimation_2d.py
- jsk_perception/node_scripts/ssd_object_detector.py
Some functions may use GPU0 regardless of setting `~gpu` as number other than 0.
> Fix error on setting device number other than 0 on multiple gpu env.

- jsk_recognition_utils/package.xml
Needed since CMakeLists.txt tries to depend on it.
This should fix the build errors seen on the Melodic buildfarm: http://build.ros.org/view/Mbin_ubhf_uBhf/job/Mbin_ubhf_uBhf__jsk_recognition_utils__ubuntu_bionic_armhf__binary/28/consoleFull
> Add qtbase5-dev as a package.xml dependency for jsk_recognition_utils.

- jsk_pcl_ros/include/jsk_pcl_ros/pointcloud_moveit_filter.h
- jsk_pcl_ros/src/pointcloud_moveit_filter.cpp
current implementation cause build failure with `moveit` `1.0.0`.
I change to be build with `moveit` `1.0.0`.
I build Kinetic with `moveit` `1.0.2`.
> [jsk_pcl_ros/pointcloud_moveit_filter] build support moveit > 1.0.0

- doc/jsk_pcl_ros/nodes/depth_image_creator.md
- jsk_pcl_ros/include/jsk_pcl_ros/depth_image_creator.h
- jsk_pcl_ros/src/depth_image_creator_nodelet.cpp
* Add ~fill_value parameter (default is nan) to specify initial value
of depth image.
> [jsk_pcl_ros/DepthImageCreator] Add ~fill_value to specify initial value of depth image

- jsk_perception/node_scripts/label_image_decomposer.py
Since `len(colormap)` is `255`, % 256 is wrong. It can return 255, which raises IndexError.
> Fix label_id division by 256 -> 255

- jsk_pcl_ros/cfg/ClusterPointIndicesDecomposer.cfg
- jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp
When I created the simple picking program, I added on-off function of using use_pca in dynamic reconfigure. I think it is more convenient.
> add the on-off function of using use_pca in dynamic reconfigure

- doc/jsk_perception/nodes/tile_image.rst
- jsk_perception/node_scripts/tile_image.py
queue_size and slop depend on the fps of topics, so we need to change it accordingly.
> Add queue_size and slop param to TileImages

- jsk_recognition_utils/include/jsk_recognition_utils/pcl/ear_clipping_patched.h
- jsk_recognition_utils/src/pcl/ear_clipping_patched.cpp
Fix https://github.com/jsk-ros-pkg/jsk_visualization/issues/738
Current triangulation does not work correctly when concave polygon is passed.
The problem can be seen when the polygon is visualized in rviz (with `jsk_rviz_plugins`) like figures below.
This PR (based on https://github.com/PointCloudLibrary/pcl/pull/2743) will fix the problem, but there are a few differences not to use c++11.
- Do not use `cend()` for std::vector. Use `end()` instead.
- Do not use `emplace_back` for std::vector. Keep using `push_back`.
__alpha = 1.0__
__alpha = 0.5__
__alpha = 1.0__
__alpha = 0.5__
> [jsk_recognition_utils] Fix ear clipping triangulation to support concave polygon

- doc/jsk_pcl_ros/nodes/cluster_point_indices_decomposer.md
- jsk_pcl_ros/cfg/ClusterPointIndicesDecomposer.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/cluster_point_indices_decomposer.h
- jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp
Currently, each box label of output boxes of cluster_point_indices_descomposer is always 0.
With this PR, If `~align_boxes` and `~align_boxes_with_plane` are `True`, each 
box(`jsk_recognition_msgs/BoundingBox`)'s label indicates nearest plane index.
The visualized results as follows:
With this PR
Without this PR
> [jsk_pcl_ros] Add nearest plane index label to cluster_point_indices_decomposer

- .travis.yml
- checkerboard_detector/test/objectdetection_tf_publisher.test
- jsk_pcl_ros/test/test_depth_calibration.test
- jsk_pcl_ros/test/test_linemod_trainer.test
- jsk_pcl_ros_utils/test/depth_image_error.test
- jsk_perception/package.xml
- jsk_perception/test/bing.test
- jsk_perception/test/draw_classification_result.test
- jsk_perception/test/pointit.test
- jsk_recognition_msgs/test/plot_data_to_csv.test
- jsk_recognition_utils/package.xml
rewrited version of #2480 with https://github.com/ros-infrastructure/rosdep/pull/694 (support version_lt for pip)
- use https://github.com/ros-infrastructure/rosdep/pull/694 to respect  version_lt for python pip, some package requries python3
- set chainer version less than 7.0.0
> set chainer version less than 7.0.0

- audio_to_spectrogram/README.md
- audio_to_spectrogram/launch/audio_to_spectrogram.launch
- audio_to_spectrogram/package.xml
- audio_to_spectrogram/sample/sample_audio_to_spectrogram.launch
In this pull request, I did:
- Add `README.md` for usage and scripts interface (main part of this pull request)
- add arg to run `audio_capture` to `audio_to_spectrogram.launch`
I am sorry that I did not add `README.md` in the previous pull request.
> [audio_to_spectrogram] Add README for usage and scripts interface

- jsk_perception/scripts/train_ssd.py
Because of `jsk_perception/scripts/train_ssd.py` 's syntax error in l165, the error message couldn't be shown correctly. This python2 script includes `print_function` from `__future__`, so I think my style is correct. I confirmed work correctly.
Before
```bash
$ rosrun jsk_perception train_ssd.py dataset_voc/
File "/home/yoshiki/research_ws/src/jsk_recognition/jsk_perception/scripts/train_ssd.py", line 165
print 'unsuppported dataset type'
^
SyntaxError: invalid syntax
```
After
```bash
$ rosrun jsk_perception train_ssd.py dataset_voc/
Please install CuPy
sudo pip install cupy-cuda[your cuda version]
i.e.
sudo pip install cupy-cuda91
```
Thanks.
> fix print syntax in train_ssd.py

- jsk_recognition_utils/node_scripts/rect_array_to_polygon_array.py
`index` is defined by `dynamic_reconfigure` in `rect_arrray_to_polygon_array.py`, but never used.
I remove it because it is not needed.
> [jsk_recognition_utils] remove unnecessary dynamic_reconfigure in rect_array_to_polygon_array.py

- doc/jsk_recognition_utils/nodes/rect_array_to_cluster_point_indices.md
- jsk_recognition_utils/node_scripts/rect_array_to_cluster_point_indices.py
- jsk_recognition_utils/sample/sample_rect_array_to_cluster_point_indices.launch
- jsk_recognition_utils/test/rect_array_to_cluster_point_indices.test
add `rect_array_to_cluster_point_indices.py`
this node converts `RectArray` to `ClusterPointIndices`, which is useful for object detection nodes.
it is related to #2467
> [jsk_recognition_utils] add rect_array_to_cluster_point_indices.py

- doc/jsk_pcl_ros/nodes/pointcloud_screenpoint.md
I added description that `PointcloudScrennpoint` inherits `jsk_topic_tools::ConnectionBasedNodelet` in README.
This PR helps to avoid problems like https://github.com/jsk-ros-pkg/jsk_recognition/issues/2503
> [PointcloudScrennpoint] Add class inheritance description

- audio_to_spectrogram/launch/audio_to_spectrogram.launch
- audio_to_spectrogram/scripts/audio_to_spectrum.py
In this pull request, I enable multi channel audio input by retrieving single channel data, like
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/cf5948cf5a592ae6fe44ecc69c16ddba81cf6bf5/ros_speech_recognition/scripts/speech_recognition_node.py#L103
> [audio_to_spectrogram] Enable multi channel input by retrieving single channel data

- jsk_perception/setup.py
fix
```
+ /usr/bin/env PYTHONPATH=/opt/ros/melodic/lib/python2.7/dist-packages:/tmp/jsk_recognition-release/obj-x86_64-linux-gnu/lib/python2.7/dist-packages:/opt/ros/melodic/lib/python2.7/dist-packages:/home/k-okada/pynaoqi/pynaoqi-python2.7-2.5.5.5-linux64/lib/python2.7/site-packages CATKIN_BINARY_DIR=/tmp/jsk_recognition-release/obj-x86_64-linux-gnu /usr/bin/python2 /tmp/jsk_recognition-release/setup.py egg_info --egg-base /tmp/jsk_recognition-release/obj-x86_64-linux-gnu build --build-base /tmp/jsk_recognition-release/obj-x86_64-linux-gnu install --root=/tmp/jsk_recognition-release/debian/ros-melodic-jsk-perception --install-layout=deb --prefix=/opt/ros/melodic --install-scripts=/opt/ros/melodic/bin
running egg_info
creating /tmp/jsk_recognition-release/obj-x86_64-linux-gnu/jsk_percepti …
```
> remove packages=['jsk_perceptoin']

- doc/jsk_pcl_ros/nodes/depth_image_creator.md
- jsk_pcl_ros/include/jsk_pcl_ros/depth_image_creator.h
- jsk_pcl_ros/src/depth_image_creator_nodelet.cpp
depth_image_creator waits for TF transform only 0.001 second.
I change to modify this duration to a parameter, and we can change it easily.
I also update the doc.
> [jsk_pcl_ros] add tf_duration parameter in depth_image_creator

- doc/requirements.txt
Travis fails because `six` is not installed.
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2553
https://travis-ci.org/github/jsk-ros-pkg/jsk_recognition/builds/746245872
```
There is a programmable error in your configuration file:
File "/home/travis/build/jsk-ros-pkg/jsk_recognition/doc/venv/lib/python3.5/site-packages/sphinx/config.py", line 319, in eval_config_file
execfile_(filename, namespace)
File "/home/travis/build/jsk-ros-pkg/jsk_recognition/doc/venv/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 89, in execfile_
exec(code, _globals)
File "/home/travis/build/jsk-ros-pkg/jsk_recognition/doc/conf.py", line 42, in <module>
import add_img_tables_to_index
File "/home/travis/build/jsk-ros-pkg/jsk_recognition/doc/add_img_tables_to_inde …
```
> Add six==1.15.0 to doc/requirements.txt

- jsk_perception/node_scripts/alexnet_object_recognition.py
- jsk_perception/node_scripts/deep_sort/deep_sort_tracker.py
- jsk_perception/node_scripts/deep_sort_tracker_node.py
- jsk_perception/node_scripts/face_pose_estimation.py
- jsk_perception/node_scripts/fast_rcnn.py
- jsk_perception/node_scripts/fcn_depth_prediction.py
- jsk_perception/node_scripts/fcn_object_segmentation.py
- jsk_perception/node_scripts/hmr/net.py
- jsk_perception/node_scripts/hmr/resnet_v2_50.py
- jsk_perception/node_scripts/hmr/smpl.py
- jsk_perception/node_scripts/human_mesh_recovery.py
- jsk_perception/node_scripts/mask_rcnn_instance_segmentation.py
- jsk_perception/node_scripts/openpose/hand_net.py
- jsk_perception/node_scripts/openpose/pose_net.py
- jsk_perception/node_scripts/people_pose_estimation_2d.py
- jsk_perception/node_scripts/regional_feature_based_object_recognition.py
- jsk_perception/node_scripts/ssd_object_detector.py
- jsk_perception/node_scripts/vgg16_object_recognition.py
- jsk_perception/scripts/create_db_for_feature_based_object_recognition.py
- jsk_perception/scripts/install_trained_data.py
- jsk_perception/scripts/ssd_train_dataset.py
- jsk_perception/scripts/train_fcn.py
- jsk_perception/scripts/train_fcn_depth_prediction.py
- jsk_perception/scripts/train_mask_rcnn.py
- jsk_perception/scripts/train_ssd.py
- do not `sys.exit(1)` when `cupy` is not installed.
- most nodes can be run by CPU.
- fix indent from 3 spaces to 4 spaces
> [jsk_perception] do not exit if cupy is not installed

- jsk_recognition_utils/package.xml
- jsk_recognition_utils/python/jsk_recognition_utils/__init__.py
use `try` to import `chainer` depending modules.
this PR solves https://github.com/jsk-ros-pkg/jsk_visualization/issues/800
cc. @Naoki-Hiraoka
> [jsk_recognition_utils] use try to import chainer depend modules

- doc/imagesift/nodes/imagesift.rst
- imagesift/include/imagesift/imagesift.h
- imagesift/sample/imagesift_sample.launch
- imagesift/src/imagesift.cpp
example launch file
```
<launch>
<group ns="/head_camera/rgb/">
<node name="image_siftnode" pkg="imagesift" type="imagesift"
output="screen" >
<remap from="image" to="image_rect_color" />
<param name="image_transport" value="compressed" />
</node>
<node name="point_pose_extractor" pkg="jsk_perception"
type="point_pose_extractor">
<param name="child_frame_name" value="opencv_logo"/>
<param name="template_filename" value="/home/k-okada/Downloads/ubereats.png"/>
<param name="object_width" value="0.15" />
<param name="object_height" value="0.076" />
<param name="reprojection_threshold" value="10.0" />  
<param name="distanceratio_threshold" value="0.60" /> 
<param name="relative_pose" value="0 0 0 0 0 0 1" />    
-->                    
<param name="error_threshold" value="50.0" />
</node> …
```
> support _image_transport:=compress for imagesift

- jsk_pcl_ros/cfg/OrganizedMultiPlaneSegmentation.cfg
this PR change `min_size` limit of `OrganizedMulitPlaneSegmentation` to int max limit.
current number `10000` is too small for recent high resolution cameras.
cc. @tohirose
> [jsk_pcl_ros] set larger min_size limit for organized multiplane segmentation

- doc/jsk_pcl_ros/nodes/heightmap_converter.md
- jsk_pcl_ros/include/jsk_pcl_ros/heightmap_converter.h
- jsk_pcl_ros/src/heightmap_converter_nodelet.cpp
To supress 'tf lookup would require extrapolation into the future' warning of heightmap conveter, added waitfortransform() before lookupTransform()
> [jsk_pcl_ros] fix bug of lookuptransform in heightmapconverter

- jsk_perception/launch/libuvc_camera.launch
- jsk_perception/launch/usb_cam.launch
- jsk_perception/sample/sample_elp_usb_4k.launch
- jsk_perception/sample/sample_insta360_air.launch
I add `brightness` arg to camera launchs.
With the default settings, the insta360 image is very dark.
For isnta360, brightness:=128 works well with both usb_cam and libuvc_camera.
The same condition as now:
```
roslaunch jsk_perception sample_insta360_air.launch brightness:=0
```
Increase bightness:
```
roslaunch jsk_perception sample_insta360_air.launch brightness:=128
```
> Add brightness arg to camera launchs

- .github/workflows/indigo.yml
- .github/workflows/kinetic.yml
- .github/workflows/melodic-base.yml
- .github/workflows/melodic.yml
- .github/workflows/noetic-full-test.yml
- .github/workflows/noetic.yml
I fix branch name from `main` -> `master` in github workflow branch name
> fix typo in github workflow branch name

- jsk_perception/node_scripts/alexnet_object_recognition.py
- jsk_perception/node_scripts/deep_sort/deep_sort_tracker.py
- jsk_perception/node_scripts/deep_sort_tracker_node.py
- jsk_perception/node_scripts/face_pose_estimation.py
- jsk_perception/node_scripts/fast_rcnn.py
- jsk_perception/node_scripts/fcn_depth_prediction.py
- jsk_perception/node_scripts/fcn_object_segmentation.py
- jsk_perception/node_scripts/hmr/net.py
- jsk_perception/node_scripts/hmr/resnet_v2_50.py
- jsk_perception/node_scripts/hmr/smpl.py
- jsk_perception/node_scripts/human_mesh_recovery.py
- jsk_perception/node_scripts/mask_rcnn_instance_segmentation.py
- jsk_perception/node_scripts/openpose/hand_net.py
- jsk_perception/node_scripts/openpose/pose_net.py
- jsk_perception/node_scripts/people_pose_estimation_2d.py
- jsk_perception/node_scripts/regional_feature_based_object_recognition.py
- jsk_perception/node_scripts/ssd_object_detector.py
- jsk_perception/node_scripts/vgg16_object_recognition.py
as reporeted https://github.com/jsk-ros-pkg/jsk_visualization/issues/809, Sometimes we need to run `pip install cupy` and compile cupy with installed cuda version. In this case we need to check `project_name` is `cupy` or `cupy-cuda`.
```
>>> [p for p in list(itertools.chain(*[pkg_resources.find_distributions(_) for _ in sys.path])) if "cupy" in p.project_name ]
[cupy 6.7.0 (/usr/local/lib/python2.7/dist-packages)]
```
> if we install cupy with pip install cupy, instead of pip install  cupy-cudaXXX, the package name is cupy

- jsk_pcl_ros/package.xml
add missing `dynamic_reconfigure` `build_depend` in `jsk_pcl_ros`.
> [jsk_pcl_ros] add missing build_depend dynamic_reconfigure in jsk_pcl_ros

- jsk_perception/include/jsk_perception/apply_mask_image.h
- jsk_perception/src/apply_mask_image.cpp
Add a parameter `max_interval_duration` that defines the delay (in seconds) with which messages can be synchronized in message_filters.
`max_interval_duration` is same as `slop` in python message_fileters.
> [WIP] [jsk_perception] add max_interval_duration for apply_mask_image

- jsk_pcl_ros/include/jsk_pcl_ros/extract_indices.h
- jsk_pcl_ros/src/extract_indices_nodelet.cpp
issue https://github.com/jsk-ros-pkg/jsk_recognition/issues/2626 as to [ExtractIndices](https://jsk-docs.readthedocs.io/projects/jsk_recognition/en/latest/jsk_pcl_ros/nodes/extract_indices.html)
Check if Input index is out of cloud size. 
If so, output NODELET_ERROR and return ~~false~~ nothing.
> [jsk_pcl_ros] ExtractIndices debug

- doc/jsk_perception/nodes/point_pose_extractor.md
- jsk_perception/src/point_pose_extractor.cpp
Add `~broadcast_tf` param to PointPoseExtractor which enables to broadcast transform of a detected object.
> [jsk_perception] add tf broadcaster to point pose extractor

- jsk_perception/launch/libuvc_camera.launch
- jsk_perception/launch/usb_cam.launch
Enable to change frame_id of camera image/info.
> [jsk_perception] add frame_id args to libuvc_camera and usb_cam launch

- doc/jsk_recognition_utils/nodes/polygon_array_publisher.md
- jsk_recognition_utils/node_scripts/polygon_array_publisher.py
- jsk_recognition_utils/sample/sample_polygon_array_publisher.launch
- jsk_recognition_utils/test/polygon_array_publisher.test
Added option to publish coefficients array to `poygon_array_publisher` node. If the polygon is a plane, the coeffiecients array is output in the same way as the output of plane detection.
> [jsk_recognition_utils] Enable publishing coefficients array

- jsk_perception/package.xml
`sample_insta360_air.launch` use `libuvc_camera` but no dependency is written in `package.xml`.
So, we have to execute `sudo apt install ros-melodic-libuvc-camera` manually without this pull request.
Please let me know if there is any reason why `libuvc_camera` is not listed in the dependencies.
cc:@708yamaguchi
> [jsk_perception] Add libuvc_camera to dependency for sample_insta360_air.launch

- doc/jsk_perception/nodes/aws_detect_faces.rst
- jsk_perception/node_scripts/aws_detect_faces.py
- jsk_perception/package.xml
In this PR
- Add `region_name` argument for boto3.client because of the following NoRegionError. We have to set `region_name` in boto3.client.
<details>
<summary>error log </summary>
```
$ roslaunch jsk_perception sample_aws_detect_faces.launch 
... logging to /home/tsukamoto/.ros/log/80e1b0c0-b3f8-11ec-ae1b-d05099843c5d/roslaunch-tsukamoto-desktop-26099.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
WARNING: disk usage in log directory [/home/tsukamoto/.ros/log] is over 1GB.
It's recommended that you use the 'rosclean' command.
started roslaunch server http://tsukamoto-desktop:37241/
SUMMARY
========
CLEAR PARAMETERS
* /aws_detect_faces/
PARAMETERS
* /aws_detect_faces/always_subscribe: True
* /aws_detect_faces/attributes: ALL
* …
```
> [jsk_perception] Fix NoRegionError in aws_detect_faces.py

- doc/jsk_perception/nodes/hand_pose_estimation_2d.rst
- jsk_perception/launch/hand_pose_estimation_2d.launch
- jsk_perception/node_scripts/hand_pose_estimation_2d.py
- jsk_perception/sample/config/hand_pose_estimation.rviz
- jsk_perception/sample/include/play_rosbag_hand.xml
- jsk_perception/sample/sample_hand_pose_estimation_2d.launch
- jsk_perception/sample/sample_hand_pose_estimation_3d.launch
- jsk_perception/scripts/install_sample_data.py
Updated hand pose estimation to get hand pose in 3d．
Since the previous rosbag data doesn't include depth image, I replaced it with new one compatible．
`roslaunch jsk_perception sample_hand_pose_estimation_2d.launch GPU:=-1 with_depth:=true`
Cc: @iory
> Enable 3d hand pose detection

- jsk_pcl_ros/src/octomap_server_contact_nodelet.cpp
https://github.com/OctoMap/octomap_mapping/pull/40 と同じmemory leakがありました。
このmemory leakはCOLOR_OCTOMAP_SERVERオプションが定義されているときのみ発生しますが、デフォルトでは定義されていないため、普通に使っている限りはこのPR無しでもmemory leakは発生しません。
> [jsk_pcl_ros/octomap_server_contact_nodelet.cpp] fix memory leak of colors pointer

- jsk_perception/node_scripts/hand_pose_estimation_2d.py
- jsk_perception/node_scripts/people_pose_estimation_2d.py
When depth image contains 0 value, 0 is also assigned to x and y position. `np.isnan(z)` cannot deal with it.
I checked this with `/kinect_head/depth_registered/hw_registered/image_rect_raw`.
By visualizing HumanSkeletonArray, we can see this problem.
> [jsk_perception] Exclude depth z=0

- doc/jsk_perception/nodes/aws_auto_checkin_app.rst
- doc/jsk_perception/nodes/aws_detect_faces.rst
- doc/requirements.txt
now `aws_auto_checkin_app` doc is messed up because of mixed syntax of md and rst.
I fixed the typo.
this PR also fix doc build.
current: https://jsk-docs.readthedocs.io/projects/jsk-recognition/en/latest/jsk_perception/nodes/aws_auto_checkin_app.html
this PR: https://knorth55-jsk-recognition.readthedocs.io/en/aws-auto-checkin-doc/jsk_perception/nodes/aws_auto_checkin_app.html
> fix doc build and typo in aws_auto_checkin_app doc

- doc/jsk_perception/nodes/virtual_camera_mono.md
- jsk_perception/CMakeLists.txt
- jsk_perception/include/jsk_perception/virtual_camera_mono.h
- jsk_perception/plugins/nodelet/libjsk_perception.xml
- jsk_perception/src/virtual_camera_mono.cpp
Currently this node starts subscribing input topics if output image is subscribed.
~~I added `info_connect_cb` and `info_disconnect_cb` to set them to advertiseCamera defined in image_transport.~~ 
This node is useful to project robot model from overhead onto the ground. I only subscribe virtual_camera_info.
https://github.com/nakane11/teach_spot/blob/f7bdb84058f14dff8dbbe1799ff6e05dbb447b1c/launch/dynamic_footprint.launch#L11-L22
Please refer to https://github.com/jsk-ros-pkg/jsk_common/issues/1198
Another solution is to use [advertiseCamera](https://github.com/jsk-ros-pkg/jsk_common/blob/30cdff0624b253d58af2b00ccdf0277cf27d9ec1/jsk_topic_tools/include/jsk_topic_tools/connection_based_nodelet.h#L314-L341) in ConnectionBasedNodelet (DiagnosticNodelet inherits it), ~~but I don't think we …
> [jsk_perception/virtual_camera_mono] Use DiagnosticNodelet to start subscribing topics when camera_info is subscribed

- jsk_perception/node_scripts/rect_array_in_panorama_to_bounding_box_array.py
`rect_array_in_panorama_to_bounding_box_array.py` works fine even if label height is not specified.
However, even in that case, warning continue to be outputted to terminal.
Based on the issue https://github.com/jsk-ros-pkg/jsk_robot/issues/1518, I use `rospy.logdebug` when height for label is not specified.
PR for fetch branch
https://github.com/sktometometo/jsk_recognition/pull/7
> [jsk_perception] Use logdebug when height for label is not specified

- doc/jsk_perception/nodes/image_publisher.md
- jsk_perception/node_scripts/image_publisher.py
- jsk_perception/sample/sample_image_publisher.launch
- jsk_perception/test/image_publisher.test
- jsk_recognition_utils/python/jsk_recognition_utils/depth.py
In current, `image_publisher.py` not supports  bgr16, rgb16, bgra16 and rgba16 encodings and compressedDepth for 32FC1 depth image.
This PR enables them to publish.
cc: @nakane11
> [jsk_perception/image_publisher.py] Support bgr16, rgb16, bgra16 and rgba16 encodings  and compressedDepth for 32FC1 depth image

- doc/jsk_perception/nodes/robot_to_mask_image.md
- jsk_perception/include/jsk_perception/robot_to_mask_image.h
- jsk_perception/sample/sample_robot_to_mask_image.launch
- jsk_perception/src/robot_to_mask_image.cpp
I fixed image size and index for downsampled image.
When image is downsampled, width and height of camerainfo are the same as the original and we can tell the actual size with binning field.
PinholeCameraModel calculates projection matrix considering it:
```
if (binning_x > 1) {
double scale_x = 1.0 / binning_x;
K_(0,0) *= scale_x;
K_(0,2) *= scale_x;
P_(0,0) *= scale_x;
P_(0,2) *= scale_x;
P_(0,3) *= scale_x;
}
```
However, this node makes `info_msg->height` times `info_msg->width` mask image so output mask is distortedly enlarged.
```
<launch>
<arg name="gui" default="true"/>
<arg name="rosbag_play_args" default="--clock --loop" />
<include file="$(find jsk_perception)/sample/include/play_rosbag_pr2_self_see.xml">
<arg name="rosbag_play_args" value="$(arg rosbag_play_args)" /> …
```
> [jsk_perception/robot_to_mask_image] Fix image size considering binning

- sound_classification/README.md
I fixed sound_classification README about how to list up input devices.
`$ pactl list short sinks` was previously used, but this is not correct.
For input devices, `sources` option can be used.
The correct command is `$ pactl list short sources`.
https://unix.stackexchange.com/questions/260981/what-do-the-sink-and-source-keywords-mean-in-pulseaudio
@pazeshun
Thank you very much for pointing this out.
> [sound_classification] Fix pactl option to list up input devices

- jsk_pcl_ros_utils/src/colorize_distance_from_plane_nodelet.cpp
- jsk_pcl_ros_utils/src/delay_pointcloud_nodelet.cpp
- jsk_pcl_ros_utils/src/depth_image_error_nodelet.cpp
- jsk_pcl_ros_utils/src/normal_concatenater_nodelet.cpp
- jsk_pcl_ros_utils/src/polygon_appender_nodelet.cpp
- jsk_pcl_ros_utils/src/polygon_array_unwrapper_nodelet.cpp
- jsk_pcl_ros_utils/src/polygon_array_wrapper_nodelet.cpp
- jsk_perception/src/bounding_box_to_rect.cpp
- jsk_perception/src/polygon_array_color_likelihood.cpp
- jsk_perception/src/robot_to_mask_image.cpp
- resized_image_transport/src/image_processing_nodelet.cpp
- resized_image_transport/src/log_polar_nodelet.cpp
This node forgets to call `onInitPostProcess()`, so I added it.
Without calling `onInitPostProcess()` on `onInit()` method, nodelet does not subscribe on start even if param always_subscribe is set to true.
> [jsk_perception][jsk_pcl_ros_utils][resized_image_transport] Call onInitPostProcess()

- jsk_recognition_utils/CMakeLists.txt
- jsk_recognition_utils/include/jsk_recognition_utils/jsk_topic_tools_version.h.in
Related to #2712  https://github.com/jsk-ros-pkg/jsk_recognition/pull/2712#discussion_r918954846
The jsk nodes use `ConnectionBasedNodelet` and `DiagnosticsNodelet`.
If we want to write the following, we need to add a header file like this PR.
```
#if  defined(JSK_TOPIC_TOOLS_VERSION) and JSK_TOPIC_TOOLS_VERSION_MINIMUM(2,2,13))
#define jsk_topic_tools::NODLET jsk_topic_tools::ConnectionBasedNodelet
#else
#define jsk_topic_tools::NODLET jsk_topic_tools::DiagnosticNodelet
#endif```
> [jsk_recognition_utils] Add jsk_topic_tools header file to check jsk_topic_tools' version

- doc/jsk_perception/nodes/virtual_camera_mono.md
- jsk_perception/include/jsk_perception/virtual_camera_mono.h
- jsk_perception/src/virtual_camera_mono.cpp
I added `queue_size` parameter to solve the following warn.
```
[ WARN][7f06f77fe700][/virtual_camera_mono/CameraSubscriber::Impl::checkImagesSynchronized:86]: [image_transport] Topics '/kinect_head/rgb/image_rect_color' and '/kinect_head/rgb/camera_info' do not appear to be synchronized. In the last 10s:
Image messages received:      294
CameraInfo messages received: 299
Synchronized pairs:           65
```
https://github.com/jsk-ros-pkg/jsk_recognition/blob/0de1e9ac4ec9ea27c548d835c9ca5e94a6101808/jsk_perception/src/virtual_camera_mono.cpp#L83
https://github.com/ros-perception/image_common/blob/cd57529952b65d5180ff27780a0370ab7504e64d/image_transport/src/camera_subscriber.cpp#L110-L121
> [jsk_perception/VirtualCameraMono] Add queue_size param

- jsk_perception/src/apply_mask_image.cpp
From opencv version 4, cvtColor doesn't support empty matrix.
If `~clip` is true, the output mask size could be `(w, h) = (0, 0)` size.
In that case, the program dies in the `cvtColor` function for `bgra` and `rgba` image.
This PR fixes the bug.
```
In [1]: import cv2
...: import numpy as np
...: print('cv2.__version__: {}'.format(cv2.__version__))
...: cv2.cvtColor(np.empty((0, 0, 3), dtype=np.uint8), cv2.COLOR_BGR2RGB)
...:
cv2.__version__: 2.4.8
```
```
In [1]: import cv2
...: import numpy as np
...: print('cv2.__version__: {}'.format(cv2.__version__))
...: cv2.cvtColor(np.empty((0, 0, 3), dtype=np.uint8), cv2.COLOR_BGR2RGB)
...:
cv2.__version__: 3.2.0
```
```
In [1]: import cv2
...: import numpy as np
...: print('cv2.__version__: {}'.format(cv2.__version__))
...: …
```
> [jsk_perception/apply_mask] Avoid error in cvtColor when masked_image is empty

- sound_classification/README.md
- sound_classification/launch/audio_to_spectrogram.launch
- sound_classification/launch/classify_sound.launch
- sound_classification/launch/record_audio_rosbag.launch
- sound_classification/launch/save_noise.launch
- sound_classification/launch/save_sound.launch
Currently, we cannot pass some arguments (e.g., `device`, `mic_sampling_rate`) of `audio_to_spectrogram.launch` from upper launches (`record_audio_rosbag.launch`, `save_noise.launch`, `save_sound.launch`, `classify_sound.launch`).
Due to this, we have the following issues in https://github.com/jsk-ros-pkg/jsk_recognition/tree/c4be2499e01a7c67d04fdcf7059964ddc8bb2552/sound_classification#usage if we avoid creating local diffs:
- We cannot use microphones other than the default microphone of `audio_to_spectrogram.launch`:
https://github.com/jsk-ros-pkg/jsk_recognition/blob/c4be2499e01a7c67d04fdcf7059964ddc8bb2552/sound_classification/launch/audio_to_spectrogram.launch#L2-L7
- We cannot change spectrogram size from the default size of `audio_to_spectrogram.launch`: …
> [sound_classification] Enable to pass all arguments of audio_to_spectrogram.launch from upper launches

- sound_classification/README.md
- sound_classification is now in jsk_recognition repo
- Additional python packages are now managed by catkin_virtualenv
- https://docs-cupy.chainer.org/en/stable/compatibility.html is broken. I think installation guide of JSK is better
> [sound_classification] Update setup doc on README

- doc/jsk_pcl_ros/nodes/hsi_color_filter.md
HSIColorFilterのドキュメントに書いてあるparameter名に誤りがあったため、修正しました。
ドキュメントのparameter名
https://github.com/jsk-ros-pkg/jsk_recognition/blob/7e6b70416d2629a37a41f1779a52d2d05524fe37/doc/jsk_pcl_ros/nodes/hsi_color_filter.md?plain=1#L24-L30
実際のparameter名
https://github.com/jsk-ros-pkg/jsk_recognition/blob/7e6b70416d2629a37a41f1779a52d2d05524fe37/jsk_pcl_ros/cfg/HSIColorFilter.cfg#L14-L19
> [doc/hsi_color_filter.md] fix parameter name

- jsk_pcl_ros/sample/include/play_rosbag_baxter_realsense_l515.xml
- jsk_pcl_ros/scripts/install_sample_data.py
- jsk_recognition_msgs/setup.py
with out this fix, master branch fails with
```
[jsk_recognition_msgs:install] + cd /home/k-okada/catkin_ws/ws_recognition/src/jsk_recognition/jsk_recognition_msgs               
[jsk_recognition_msgs:install] + mkdir -p /home/k-okada/catkin_ws/ws_recognition/install/lib/python2.7/dist-packages              
[jsk_recognition_msgs:install] + /usr/bin/env PYTHONPATH=/home/k-okada/catkin_ws/ws_recognition/install/lib/python2.7/dist-packages:/home/k-okada/catkin_ws/ws_recognition/build/jsk_recognition_msgs/lib/python2.7/dist-packages:/home/k-okada/catkin_ws/ws_recognition/install/lib/python2.7/dist-packages:/opt/ros/melodic/lib/python2.7/dist-packages:/home/k-okada/pynaoqi/pynaoqi-python2.7-2.5.5.5-linux64/lib/python2.7/site-packages …
```
> jsk_recognition_msgs : setup.py need src/jsk_recognition_msgs

- jsk_pcl_ros_utils/src/cluster_point_indices_label_filter_nodelet.cpp
Log warnings and skip if the cluster and label sizes mismatch in `ClusterPointIndicesLabelFilter`.
> Add size check in ClusterPointIndicesLabelFilter

- jsk_perception/sample/sample_dual_fisheye_to_panorama.launch
- jsk_perception/sample/sample_insta360_air.launch
this commits are from `develop/fetch`.
it is similar to #2690 , but i don't know which is better.
@iory @708yamaguchi
> [jsk_perception] Poke in dual_fisheye_to_panorama for DiagnosticNodelet

- audio_to_spectrogram/package.xml
- audio_to_spectrogram/scripts/audio_amplitude_plot.py
- audio_to_spectrogram/scripts/audio_to_spectrum.py
- audio_to_spectrogram/scripts/spectrum_plot.py
- audio_to_spectrogram/scripts/spectrum_to_spectrogram.py
- audio_to_spectrogram/src/audio_to_spectrogram/__init__.py
- audio_to_spectrogram/src/audio_to_spectrogram/compat.py
- audio_to_spectrogram/src/audio_to_spectrogram/convert_matplotlib.py
- audio_to_spectrogram/test/audio_to_spectrogram.test
This change is by defaulting to Agg as the backend for matplotlib.
See #2759
> Fix audio to spectrogram plot and add test

- audio_to_spectrogram/README.md
- audio_to_spectrogram/scripts/spectrum_plot.py
This PR helps to display spectrum of data other than audio.
Setting `plot_amp_max` to 0.2 generates:
(Force sensor data sensing drill vibration)
Also this PR enables to set `queue_size` because generating plot is slow in my environment (`/spectrum_plot/output/viz` is less than 12Hz).
In this environment, setting `queue_size` to 1 is required if you input spectrum more than 12Hz and also want to prevent plot from being delayed more and more.
~~(Perhaps this is due to #2759 . More debug should be needed.)~~
> [audio_to_spectrogram] Enable to change spectrum plot from rosparam

- doc/jsk_perception/nodes/aws_detect_faces.rst
This PR fixes documentation of `aws_detect_faces.py`
`msg` name is wrong. (`opencv_msg` --> `opencv_apps`)
> [doc] Fix documentation of aws_detect_faces.py

- jsk_recognition_utils/package.xml
In `$ROS_PYTHON_VERSION=3` environment (noetic), it installs `cython2` force and purges `python-is-python3`. This PR avoids this situation
> [jsk_recognition_utils] add cython3 depend when ROS_PYTHON_VERSION==3

- jsk_perception/CMakeLists.txt
- jsk_perception/include/jsk_perception/split_image.h
- jsk_perception/node_scripts/split_image.py
- jsk_perception/plugins/nodelet/libjsk_perception.xml
- jsk_perception/sample/sample_split_image.launch
- jsk_perception/src/split_image.cpp
Improvement of https://github.com/jsk-ros-pkg/jsk_recognition/pull/2573.
Before this PR (Python version):
The CPU usage of `split_image.py` is about 112% and hz of `/split_image/output/vertical00/horizontal00` is about 38.
After this PR (cpp version):
The CPU usage of `split_image` is about 40% and hz of `/split_image/output/vertical00/horizontal00` is about 60.
You can try this benchmark to change `jsk_perception/sample/sample_split_image.launch` 's line
```xml
<node type="split_image" pkg="jsk_perception" name="split_image" output="screen">
```
to
```xml
<node type="split_image.py" pkg="jsk_perception" name="split_image" output="screen">
```
> [split_image] add cpp version of split_image

- jsk_perception/sample/sample_dual_fisheye_to_panorama.launch
- jsk_perception/sample/sample_insta360_air.launch
This change was made in response to https://github.com/jsk-ros-pkg/jsk_recognition/pull/2770.
I tested on fetch15 and I have confirmed that cpu usage becomes lower when I use this patch.
- before
- after
> [jsk_perception] Use cpp version of split_image in sample_insta360_air.launch

- jsk_perception/src/jsk_perception/vil_inference_client.py
I updated the output of `/classification/visualize` string of `classification_node.py`, because it was difficult to understand.
| Before  | After |
| ------------- | ------------- |
| ![Screenshot from 2023-10-12 17-34-50](https://github.com/jsk-ros-pkg/jsk_recognition/assets/38127823/8cf610ee-09f2-46d5-973a-3078eaad35dd) | ![Screenshot from 2023-10-13 18-51-16](https://github.com/jsk-ros-pkg/jsk_recognition/assets/38127823/c8ac1210-495d-43d1-926e-c852dd85d881) |
In the result message of `classification_node.py`, `label_proba` shows the cosine similarity between input image and each text label, and `probabilities` are the classification probabilities for each text label, in the order of the text labels in `label_names`. 
Cosine similarity should be in the range -1~1, so the display in the …
> [jsk_perception] Fix Cosine Similarity description in visualize  string msg of classification_node 

- doc/install_chainer_gpu.md
Sorry, I forgot checking broken links.
In this PR, links are rewritten as markdown format to make hyperlinks work.
Also I changed the link to bionic nvidia-cuda-dev package because packages.ubuntu.com removes its page.
(FYI: These days, jsk_recognition readthedocs build fails. https://readthedocs.org/projects/jsk-recognition/builds/)
> [doc] Fix links to markdown format in install_chainer_gpu

- jsk_perception/launch/classification.launch
- jsk_perception/launch/vqa.launch
- jsk_perception/src/jsk_perception/vil_inference_client.py
I added `image_transport` arg to use compressed image topic.
This PR will reduce heavy network traffic when we send images to vil server frequently.
> [jsk_perception] Support compressed type image in vil_inference_client.py

- jsk_recognition_msgs/package.xml
So that we can get to `ROS_DISTRO` at build time.
See: https://github.com/lopsided98/nix-ros-overlay/issues/406
> Add ros_environment

- jsk_pcl_ros/include/jsk_pcl_ros/cluster_point_indices_decomposer.h
- jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp
currently, ClusterPointIndicesDecomposer assume that there is `XYZRGB` field,
so I see this warning when we use point cloud format `XYZI` again and again
```
Failed to find match for field 'rgb'.                                                                                                    
Failed to find match for field 'rgb'.                                                                                                    
Failed to find match for field 'rgb'.                                                                                                                                                                                                                                             
Failed to find match for field 'rgb'. …
```
> use xyz instead of xyzrgb in ClusterPointIndicesDecomposer

- jsk_recognition_utils/CMakeLists.txt
- jsk_recognition_utils/package.xml
The current CMake implementation of `jsk_recognition_utils` does not propagate the need for OpenCV downstream, so I fixed it.
Create the package like
package.xml
```xml
<?xml version="1.0"?>
<package format="2">
<name>test_utils</name>
<version>0.0.0</version>
<description>The test_utils package</description>
<maintainer email="obinata@todo.todo">obinata</maintainer>
<license>TODO</license>
<depend>jsk_recognition_utils</depend>
<buildtool_depend>catkin</buildtool_depend>
</package>
```
CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.0.2)
project(test_utils)
find_package(catkin REQUIRED COMPONENTS jsk_recognition_utils)
catkin_package()
include_directories(
include
${catkin_INCLUDE_DIRS}
)
link_directories(
${catkin_LIBRARY_DIRS}
)
message(STATUS "catkin_INCLUDE_DIRS: …
```
> [jsk_recognition_utils] add OpenCV to catkin_depends

- doc/jsk_pcl_ros/nodes/hinted_plane_detector.md
- jsk_pcl_ros/cfg/HintedPlaneDetector.cfg
- jsk_pcl_ros/include/jsk_pcl_ros/hinted_plane_detector.h
- jsk_pcl_ros/src/hinted_plane_detector_nodelet.cpp
The HintedPlaneDetector nodelet originally only accepts synchronized input of a Pointcloud and a hint.
This pull request is to allow input of a hind cloud at any point without synchronization.
The default behavior will not be changed at all.
> Add option 'synchronize' to hinted_plane_detector_nodelet

- audio_to_spectrogram/package.xml
- imagesift/package.xml
- jsk_pcl_ros/package.xml
- jsk_pcl_ros_utils/package.xml
- jsk_perception/package.xml
- jsk_recognition_utils/package.xml
Any package that evaluates `ROS_VERSION`, `ROS_DISTRO` or `ROS_PYTHON_VERSION` at build time should add ros_environment as a dependency.
> Add missing ros_environment dependency to package.xml

- audio_to_spectrogram/CMakeLists.txt
I found another issue of https://github.com/jsk-ros-pkg/jsk_recognition/pull/2743 other than https://github.com/jsk-ros-pkg/jsk_recognition/pull/2851.
Conditional branch for `catkin_install_python` is wrong only in `audio_to_spectrogram`.
Correct (`jsk_recognition_msgs`):
https://github.com/jsk-ros-pkg/jsk_recognition/blob/c80a511340cd9b9fb112be70056632fd07b58964/jsk_recognition_msgs/CMakeLists.txt#L145-L163
On indigo, `catkin_install_python` is not used.
Wrong (`audio_to_spectrogram`):
https://github.com/jsk-ros-pkg/jsk_recognition/blob/c80a511340cd9b9fb112be70056632fd07b58964/audio_to_spectrogram/CMakeLists.txt#L20-L38
***Not*** on indigo, `catkin_install_python` is not used.
> [audio_to_spectrogram] Fix when to use catkin_install_python

- doc/jsk_perception/nodes/vqa_node.md
When I executed the below command following https://jsk-docs.readthedocs.io/projects/jsk_recognition/en/latest/jsk_perception/nodes/vqa_node.html#run-inference-container-on-another-host-or-another-terminal
```
kochigami@kochigami-ThinkPad-P16-Gen-1:~/catkin_ws/src/jsk_recognition/jsk_perception/docker$ ./run_jsk_vil_api --port 8888 --ofa_task caption --ofa_model_scale huge
```
I got the following error:
```
usage: run_jsk_vil_api [-h] [-p PORT] [--ofa_task OFA_TASK] [--ofa_model_scale {base,large,huge}] {ofa,clip}
run_jsk_vil_api: error: the following arguments are required: model
```
It seems that we need to set a model argument, but it seems that doc forgets it.
Thus, I added an explanation about model argument.
I'm not sure whether it is a good explanation, so please check this. …
> [jsk_perception/doc/vqa_node] add explanation about model argument

- jsk_perception/package.xml
- sound_classification/CMakeLists.txt
- sound_classification/package.xml
add std_mgs build_depends, to fix obase-build (maybe and others)
```
2025-01-03T00:50:28.1527201Z -- BUILD_SHARED_LIBS is on
2025-01-03T00:50:28.2543412Z -- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
2025-01-03T00:50:28.2568008Z -- Could NOT find std_msgs (missing: std_msgs_DIR)
2025-01-03T00:50:28.2569369Z -- Could not find the required component 'std_msgs'. The following CMake error indicates that you\
either need to install the package with the same name or change your environment so that it can be found.
2025-01-03T00:50:28.2584407Z CMake Error at /usr/share/catkin/cmake/catkinConfig.cmake:82 (find_package):
2025-01-03T00:50:28.2585511Z   Could not find a package configuration file provided by "std_msgs" with any
2025-01-03T00:50:28.2586306Z   of the …
```
> fix for ROS-O

- jsk_recognition_utils/include/jsk_recognition_utils/tf_listener_singleton.h
Otherwise, the copy constructor returns void which is invalid.
> Delete copy constructor of TfListenerSingleton

- jsk_pcl_ros/include/jsk_pcl_ros/pcl/particle_cuboid.h
This PR implements the ⁠`weightedAverage` method in the ⁠`ParticleCuboid` class, as required by changes in PCL ([PointCloudLibrary/pcl#5538](https://github.com/PointCloudLibrary/pcl/pull/5538)).
Prior to these changes, a ⁠tracker class did not have this method. This PR adds a minimal implementation to restore the functionality to its state before the aforementioned changes, ensuring compatibility with the newer PCL API (I checked it works with PCL 1.16 / Ubuntu noble).
As an advanced update considering RPY (Roll, Pitch, Yaw) in multiple parts of the class might be beneficial for future development. This PR focuses on the minimal change to restore functionality.
> [ROS-O] Add ParticleCuboid::weightedAverage method

- jsk_perception/node_scripts/draw_rects.py
- jsk_recognition_utils/python/jsk_recognition_utils/put_text.py
sample/sample_aws_auto_checkin_app.launch uses 
```
<node name="draw_rects"
pkg="jsk_perception" type="draw_rects.py"
output="screen"
clear_params="true" >
<remap from="~input" to="$(arg INPUT_IMAGE)" />
<remap from="~input/rects" to="output/rects" />
<remap from="~input/class" to="output/class" />
<rosparam subst_value="true">                                                                                     
font_path: $(find jsk_recognition_utils)/font_data/NotoSansJP-Regular.otf                                       
use_classification_result: true                                                                                 
label_size: 16                                                                                                  
approximate_sync: true …
```
> use cv2.putText if font is not found

- jsk_pcl_ros/include/jsk_pcl_ros/organized_statistical_outlier_removal.h
- jsk_pcl_ros/src/organized_statistical_outlier_removal_nodelet.cpp
this PR supports several point cloud type as `xyzirt`.
now this nodes only support `xyzrgb`.
> [jsk_pcl/OrganizedStatisticalOutlierRemoval] support several pointcloud type

- jsk_perception/node_scripts/tile_image.py
`collections.Sequence` is deprecate in latest ubuntu python version
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
collections.Sequence
```
> fix tile_image for 24.04

- jsk_pcl_ros/plugins/nodelet/libjsk_pcl_ros.xml
- jsk_pcl_ros/src/uniform_sampling_nodelet.cpp
- add UniformSampling in nodelet xml.
- now indices are not correctly registered.
- `uniform_sampling.getIndices()` returns all indices
- we need to get the indices from `all_indices - removed_indices`.
- ref: https://github.com/PointCloudLibrary/pcl/blob/2f9dc390c6769fbd821fafa0e16f4707ed7c5d79/tools/uniform_sampling.cpp#L104-L116
> Fix uniform sampling

- jsk_perception/node_scripts/tile_image.py
the bug is introduced in https://github.com/jsk-ros-pkg/jsk_recognition/pull/2857/commits/e1615fb94c352992c04e5efff7206fc10803b4b2
`imgmsg` is not assigned if `self.pub_img.get_num_connections() == 0`
> fix tile image

- imagesift/CMakeLists.txt
- imagesift/include/imagesift/imagesift.h
- imagesift/src/imagesift.cpp
- imagesift/test/test_two_imagesift.test
close #2860 
`libsiftfast` has so many static global variables, so it is not thread-safe when called from multiple nodelets. This PR adds a global mutex to restrict the access to those variables to make it thread-safe.
Since the entire mutex is taken, if n imagesift nodelet are loaded, the time required to compute each feature is n times longer. But I think it is fine because the node is implemented with ConnectionBasedNodelet. If the user doesn't subscribe, the slow calculation doesn't occur.  Making the user code work is much important.
The clean method is to make [libsiftfast](https://github.com/jsk-ros-pkg/jsk_3rdparty/tree/master/3rdparty/libsiftfast) thread-safe, but I think we should write it from scratch or use OpenCV if we do so. 
You can try the bug occurs just reverting …
> Fix https://github.com/jsk-ros-pkg/jsk_recognition/issues/2860

- jsk_pcl_ros_utils/src/bounding_box_array_to_bounding_box_nodelet.cpp
When input `BoundingBoxArray`'s `boxes` size is zero, topic will be subscribed with the initial value (such as `dimensions.x = 0`).
This PR stop publishing when input size is zero.
> do not publish when array_size is zero
